### ISSUE TITLE
yarn should regard the `prefix` settings or use a proper name for the environment variable

### ISSUE THREAD

**Issue by leomao** [yarnpkg/yarn#1040]
**Do you want to request a _feature_ or report a _bug_?**
feature

**What is the current behavior?**
`yarn global bin` use the directory of the binary `node` or the path specified by `PREFIX` or `DESTDIR`.

**What is the expected behavior?**
I think `yarn` should regard the `prefix`settings in the config. If `prefix` is set to be `/path/to/somewhere`, then it should link binaries to `/path/to/somewhere/bin`.

Or it should use environment variables named like `YARN_PREFIX`, which is prefixed with `YARN_`.

**Please mention your node.js, yarn and operating system version.**

```
> node -v
v6.8.0
> npm -v
3.10.8
> yarn --version
0.15.1
```

OS/distro: Arch Linux with kernel 4.7.6

**Comment by FLGMwt** [comment]
If it helps, `PREFIX` is respected. : D

**Comment by leomao** [comment]
@FLGMwt yes, I have mentioned in the original comment. I just think it should be prefixed with something like `YARN_`.

Or, just regarding the `prefix` setting may be better.

**Comment by dflock** [comment]
This behaviour is somewhat confusing and I'm not sure if this is documented anywhere except in the code, but this is how it appears to work. [AFAICT, this is the code](https://github.com/yarnpkg/yarn/blob/add0a6cb70fbe03cee7a23563fa25291bcb959ee/src/cli/commands/global.js):

```js
function getGlobalPrefix(): string {
  if (process.env.PREFIX) {
    return process.env.PREFIX;
  } else if (process.platform === 'win32') {
    // c:\node\node.exe --> prefix=c:\node\
    return path.dirname(process.execPath);
  } else {
    // /usr/local/bin/node --> prefix=/usr/local
    let prefix = path.dirname(path.dirname(process.execPath));

    // destdir only is respected on Unix
    if (process.env.DESTDIR) {
      prefix = path.join(process.env.DESTDIR, prefix);
    }

    return prefix;
  }
}
```

My case is: running on linux, with yarn installed via the apt repo, and neither `DESTDIR` or `PREFIX` set:

```console
 ➜ node --version
v6.9.0
 ➜ yarn --version
0.16.0
➜ which yarn
/usr/bin/yarn
➜ yarn global bin
/usr/bin
➜ env | egrep '^DESTDIR|^PREFIX'

```

As implied by the code, the behaviour is slightly different depending on which env var you use:

```console
 ➜ yarn global bin
/usr/bin
 ➜ PREFIX=~/tmp; yarn global bin
/home/duncan/tmp/bin
 ➜ DESTDIR=~/tmp; yarn global bin
/home/duncan/tmp/usr/bin

```

If I set `DESTDIR` to a relative path, yarn just effectively does `$(pwd)/$DESTDIR/$(yarn global bin)`. For example, if I'm currently in a folder called `/home/duncan/dev` when I run `yarn global bin`, I get this:

``` console
➜ DESTDIR=test; yarn global bin
/home/duncan/dev/test/usr/bin
```

In order to get yarn to put the binaries where I wanted it to (`~/.yarn-config/global/bin`) - and make them available to run - I set things like this in my `~/.bashrc`:

```bash
#
# Yarn stuff
#

# Run 'yarn global add' without sudo, set yarn global bin somewhere else
# https://github.com/yarnpkg/yarn/issues/1040
export PREFIX=~/.yarn-config/global
PATH="$PREFIX/bin":$PATH
```

and then (for the benefit of both yarn & npm), I have this relative path set in my $PATH:

```bash
# also preferentially run stuff from the current/local node_modules folder
PATH="./node_modules/.bin":$PATH
```

**Comment by joseluisq** [comment]
:+1:

**Comment by vitorgalvao** [comment]
> If it helps, `PREFIX` is respected.

Not on my setup. Similarly, the new `--prefix` option [also does nothing](https://github.com/yarnpkg/yarn/issues/1877).

**Comment by markstos** [comment]
I think this issue can closed now. Since this issue was reported,  a `prefix` option [was added](7038bdc29570a72975d62cb8fed51a94033a210e)  to the `global` command.

You can see it's still in use now: 
https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/global.js#L71

[There is a separate issue open in the documentation queue about documenting the `prefix` config key.](https://github.com/yarnpkg/website/issues/376)
