### ISSUE TITLE
Can yarn remove all modules?

### ISSUE THREAD

**Issue by monkindey** [yarnpkg/yarn#1048]
When I input the command 

```shell
yarn remove
```
But it warned me 

> error Not enoguh arguments, expected at least 1

So Does the yarn support the **remove all**?

#### PS

```shell
yarn remove *
```

it doesn't work!

#### Thanks

**Comment by DevJMD** [comment]
Sure thing!

`$ yarn remove *` 

will remove all dependencies.

**Comment by troydemonbreun** [comment]
@kittens Is this a feature you'd like to have in yarn?  npm does not appear to support it, but might be nice to have if there is not a landmine in implementing such a thing.

**Comment by chuwik** [comment]
What would the scenario be for wanting to remove all dependencies? In my opinion having 'yarn remove' removing all packages could be a bit dangerous, since you could enter that by mistake and end up removing all...

'yarn remove *' would be a better syntax in my opinion, as @monkindey suggests, but again not sure if this is something that people do in their day to day work enough that it'd be worth supporting it.

I'm not a main contributor in the project, but here's my 2 cents in any case :)

**Comment by troydemonbreun** [comment]
@chuwik I'm not suggesting the no-arg route, just the functionality in general, probably with --all.  There appears to be some interest on StackOveflow, for [local](http://stackoverflow.com/questions/19106284/how-do-you-uninstall-all-dependencies-listed-in-package-json-npm) and [global](http://stackoverflow.com/questions/9283472/command-to-remove-all-npm-modules-globally).

**Comment by monkindey** [comment]
we can use the command like
```shell
yarn remove `ls -1 node_modules | tr '/\n' ' '`
```
to uninstall all

http://stackoverflow.com/questions/19106284/how-do-you-uninstall-all-dependencies-listed-in-package-json-npm

**Comment by troydemonbreun** [comment]
@monkindey Yes, but supposedly doesn't work for Windows

**Comment by samccone** [comment]
based on the decision in #1284 I am going to close this. If you feel strongly about this solution. Please open an issue here https://github.com/yarnpkg/rfcs

thanks everyone!

**Comment by yorch** [comment]
I was looking for a way to remove all global packages I have installed and found out this thread.

Ended up using:

```bash
yarn global remove $(yarn global list | grep info | sed 's/^info "\(.*\)@.*".*$/\1/')
```
