### ISSUE TITLE
Installing on Codeship throws error: yarn.js:33

### ISSUE THREAD

**Issue by nateritter** [yarnpkg/yarn#1078]
**Which operating system are you using:**
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
```

**Please describe the steps you took when trying to install Yarn and what went wrong:**

Since we don't have sudo privileges on Codeship, I installed using `npm install --global yarn`. 

`yarn --version` or `yarn` throws the following:

```
/home/rof/.yarn/bin/yarn.js:33
  throw new Error('Node version ' + ver + ' is not supported');
        ^
Error: Node version 0.10.47 is not supported
    at Object.<anonymous> (/home/rof/.yarn/bin/yarn.js:33:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/rof/.yarn/bin/yarn:2:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by Daniel15** [comment]
Hello @nateritter! This error message is correct - Yarn needs Node 4.0 or higher. Node.js 0.10 is very old now.

According to Codeship's documentation at https://documentation.codeship.com/languages/nodejs/, they do support newer versions. It looks like you can either configure the version of Node.js in your `package.json` file, or use "nvm install" to get a newer Node.js version.

Going to close this out as it's an environment-specific thing rather than an issue with Yarn. Thanks for trying Yarn! 😄

**Comment by nateritter** [comment]
Haha. That's what's on Codeship. Sad. Ok. Thanks for that.

**Comment by thejameskyle** [comment]
We should improve this error message. Expected errors should not leave stack traces

**Comment by busches** [comment]
Additionally, no where in the installation instructions does it mention the minimum node version.

**Comment by Jivings** [comment]
Since this is the top Google result for Codeship + Yarn, I'll add that these are the lines I needed to put in my Test Setup configuration to get Yarn working;

```bash
nvm use 4
npm i -g yarn
yarn
```
