### ISSUE TITLE
Install from github master cause broken result. How to test latest features & bugfixes? Just from new releases?

### ISSUE THREAD

**Issue by johnunclesam** [yarnpkg/yarn#1152]
**THIS IS a BUG.**

Installing on Windows 10 x64 with `npm i -g yarnpkg/yarn`:

```
$ yarn
C:\Users\user\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js:48
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\user\AppData\Roaming\npm\node_modules\yarn\lib\cli\index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.Module._extensions..js (module.js:578:20)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js:40:22)
```

**Comment by Daniel15** [comment]
Hi @johnunclesam! Please try using the Windows installer (https://yarnpkg.com/latest.msi) instead, npm is only designed to be used a a fallback and should not be used as the primary method of installing Yarn.

**Comment by johnunclesam** [comment]
I need to test the latest features (strict-ssl false and others) and also with exe installer nothing. I need also the "npm" version of yarn, not exe one (for various reasons). I will wait for next release. Thanks.

**Comment by puzrin** [comment]
That's not windows-specific issue. The same in Ubuntu LTS 14.04. It worth clarify topic to something like "Install from github master cause broken result".

@Daniel15 it would be convenient to install latest version from master via `npm i yarnpkg/yarn -g`. For example to test latest features & bugfixes.

**Comment by rops** [comment]
Got same issue on OSX. I'm using npm to test latest version of yarn. Is that a better way?

**Comment by Daniel15** [comment]
Ahh, I see. You're installing directly from Git? If you want to use the very latest release from Git, you need to clone the repo and build it yourself (`npm install && npm run build`). Soon we'll have official "nightly" releases to make it easier to use the very latest version of Yarn. This will allow you to download a tarball of the very latest Yarn code, or install it as a Debian/Ubuntu package. In the meantime, the only supported option for bleeding-edge builds is to clone the Git repo and build it.

Closing this issue, but please feel free to ask questions if you have any. Thanks for trying Yarn! 😄

**Comment by rops** [comment]
Yes I was installing it with `npm install yarn@https://github.com/yarnpkg/yarn`. Being a regular npm package, shouldn't it just work?

**Comment by Daniel15** [comment]
> Being a regular npm package, shouldn't it just work?

The code in Git is the source code. It uses newer ES7/ES2016 features and thus needs to be compiled via Babel to be able to execute under Node.js. You can't run it directly from Git without compiling it first :)

**Comment by rops** [comment]
That I understand :) I hoped there was some magic post-install hooks in place that was building and  transpiling, but I don't see any indeed :) I guess it gets built/transpiled before publishing

**Comment by puzrin** [comment]
@Daniel15

1. if we expect node 6+ to be used (and there are no much need to support old nodes in fresh projects), only `import` seems incompatible. I don't see big reasons to use `import` instead of `require` for CLI and loose ability to install by url.
2. It's possible to add post-install script to run build if directory not exists.

I don't insist, but it would be nice if global install from repo head could be more simple for foreign users. So, it's my personal opinion and the rest is on your choice. Thanks for yarn!

**Comment by Daniel15** [comment]
> It's possible to add post-install script to run build if directory not exists.

I could be wrong, but I think it's not ideal to force users of Yarn to have to compile it themselves. This means the user has to install all dev dependencies of Yarn, rather than just installing Yarn itself.

I'm going to make it easier to download latest/unstable/nightly builds of Yarn, but at the moment the easiest way is to grab them from CircleCI (go to https://circleci.com/gh/yarnpkg/yarn/tree/master, click the latest successful build, click the "artifacts" tab, download the tarball eg. `yarn-v0.16.2-20161006.1834.tar.gz`). Eventually we'll have some URL like `yarnpkg.com/latest-nightly.tar.gz` that you could `wget` to get the very latest tarball.
