### ISSUE TITLE
npm rebuild [package-name] equivalent

### ISSUE THREAD

**Issue by nicksp** [yarnpkg/yarn#1163]
Hi,

Is the equivalent for `npm rebuild node-sass` command? I'd like to rebuils that package depending on the environment it's used. How can i achieve it in `yarn`. Is running `yarn add node-sass` does the trick of reinstalling already installed package?

**Comment by markstos** [comment]
There's a related ticket open in the website project to document the rebuild equivalent there:
https://github.com/yarnpkg/website/issues/192

**Comment by starInEcust** [comment]
+1

**Comment by manuel-reil** [comment]
+1

**Comment by kittens** [comment]
Don't +1 issues. GitHub adding reactions for a reason. The equivalent command is:

```
$ yarn install --force
```

**Comment by dudeinthemirror** [comment]
I'm confused:
```
Running 'docker exec -it web_11 yarn install --force node-sass ...
yarn install v0.16.0
error `install` has been replaced with `add` to add new dependencies. Run "yarn add node-sass" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Which one is it now ?

**Comment by markstos** [comment]
@dudeinthemirror As the docs [1] [2], `add` is for adding a new dependency, while `install` is for installing *all* dependencies. Trying to `install` a single package doesn't make sense with yarn. The docs show that the `add` commands take a package name argument, while the `install` commands don't, since they work on *all* dependencies. 

 1. https://yarnpkg.com/en/docs/cli/install
 2. https://yarnpkg.com/en/docs/cli/add

**Comment by dudeinthemirror** [comment]
Ah, got it. Just started implementing yarn in our project today, so total greenhorn still :) Thanks much @markstos for the info !

**Comment by tdmalone** [comment]
What if you don't want to add a dependency but you need to rebuild because of an upstream dependency? node-sass needs to be rebuilt after I upgraded Node, and it's an upstream dependency of one of my other packages. I tried `yarn --force` but wasn't able to resolve it, in the end `rm -rf node_modules && yarn` resolved it, but ideally I wouldn't want to result to that and wait for it all :)

**Comment by jchook** [comment]
For anyone visiting this old thread, this worked for me:

```
yarn add --force node-sass
```

**Comment by BerekHalfhand** [comment]
> For anyone visiting this old thread, this worked for me:
> 
> ```
> yarn add --force node-sass
> ```

Tried this and now I ended up with an endless loop:

`remote:        [4/4] Rebuilding all packages...
remote:        success Saved lockfile.
remote:        success Saved 1 new dependency.
remote:        info Direct dependencies
remote:        └─ node-sass@4.11.0
remote:        info All dependencies
remote:        └─ node-sass@4.11.0
remote:        $ yarn add --force node-sass
remote:        yarn add v1.5.1
remote:        [1/4] Resolving packages...`

**Comment by mike-marcacci** [comment]
Sadly, `yarn install --force` does not seem to have the desired effect when using workspaces.

**Comment by akhilalekha** [comment]
> For anyone visiting this old thread, this worked for me:
> 
> ```
> yarn add --force node-sass
> ```

yeah this isn't working for me - new error :
```$ yarn add --force node-sass
yarn add v1.22.5
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you wan
t - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
