### ISSUE TITLE
[feature] Ability to disable caching for Docker builds

### ISSUE THREAD

**Issue by andrewmclagan** [yarnpkg/yarn#1178]
**Do you want to request a *feature* or report a *bug*?**

*feature*

**What is the current behavior?**

Yarn always caches packages during `yarn install`

**What is the expected behavior?**

Have a flag the disables the caching of packages during install for Docker builds where it is not needed and only bloats the final image. e.g.

`yarn install --no-cache`

**Please mention your node.js, yarn and operating system version.**

````
>> yarn --version
0.15.1
>> node --version
v6.3.1
Alpine Linux 3.x.x
````

**Comment by joscha** [comment]
I tried working around by using `yarn cache clean` for that, but it has its own problems: #1137

**Comment by eugene1g** [comment]
To elaborate on the use-case: the application is packaged into an immutable Docker container, and this container will never change and or be reused. That is, `yarn install` will never run again, so caching downloaded files on the filesystem increases the shippable size of the container (in our case by ~150mb). We can't download the files outside and then inject them into the container because dependencies might have binaries that should be compiled on the system system where they will run (i.e. in the container).

**Comment by victornoel** [comment]
Duplicate of #986 :)

**Comment by andrewmclagan** [comment]
closing in favour of #986
