### ISSUE TITLE
[infra] make hombrew release automatic

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#1202]
Use something like https://www.npmjs.com/package/brew-publish to update formula and send PR.

**Comment by bestander** [comment]
PR welcome

**Comment by Daniel15** [comment]
`brew-publish` is just [a tiny shell script](https://github.com/jasonkarns/brew-publish/blob/master/bin/brew-publish), we could add our own script to the `scripts` directory that does the same thing rather than adding another dependency

This could be something very similar to what we do for Chocolatey ([build-chocolatey.ps1](https://github.com/yarnpkg/yarn/blob/master/scripts/build-chocolatey.ps1)) and for the Debian/RPM repo ([update-and-push.sh](https://github.com/yarnpkg/releases/blob/gh-pages/update-and-push.sh) and [update.sh](https://github.com/yarnpkg/releases/blob/gh-pages/update.sh)). Basically:
 - Hit `https://yarnpkg.com/latest-version` to get latest version number
 - Hit Homebrew to check version Homebrew is using
 - If (latest version number > Homebrew version number) { update homebrew }

Then run it as a post-release webhook from CircleCI, or just make it a cronjob.

**Comment by MikeMcQuaid** [comment]
Use the Homebrew provided `brew bump-formula-pr` script for this.

**Comment by Daniel15** [comment]
@MikeMcQuaid Does that run on Windows or Linux, or do we need to run it on Mac OS?

**Comment by MikeMcQuaid** [comment]
It'll likely run on Linux.

**Comment by voxsim** [comment]
@Daniel15 is this resolved? I am asking for two reasons:
* I saw the script called  https://github.com/yarnpkg/yarn/blob/master/scripts/update-homebrew.sh
* but in homebrew we still have 0.23.4 (https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb)

Am I missing something? Can I help in some way?

**Comment by Daniel15** [comment]
Yes, it is. 0.23.4 is currently the latest release. We don't publish
release candidates to Homebrew.

**Comment by voxsim** [comment]
ok thanks @Daniel15 :)
