### ISSUE TITLE
Support for npm@4's new prepublish behavior

### ISSUE THREAD

**Issue by Kovensky** [yarnpkg/yarn#1323]
npm@4 was [released a few minutes ago](https://github.com/npm/npm/releases/tag/v4.0.0), and it deprecates the `prepublish` verb, renaming it to `prepare`, and adding a `prepublishOnly` (which runs only on publish).

In yarn's case, the only changes should be also running `prepare` wherever `prepublish` ran and `prepublishOnly` on publish (if yarn can publish?). `prepublish` should still be run, but probably should get a deprecation warning.

npm@5 is expected to stop running `prepublish` entirely on `npm install` and `npm pack` (i.e. run only on `npm publish`), and then an npm@>=6 should deprecate `prepublishOnly` by renaming it to `prepublish`.

**Comment by SamHH** [comment]
I'm happy to take this one.

What's Yarn's approach to compatibility with older versions of npm (or is that a non-issue regards how Yarn works?)? I ask because if we change the publish script to prepublishOnly then you lose support for npm <4. If we keep prepublish, then there's no point in adding prepublishOnly as it will be renamed back to prepublish eventually as you said, and presumably in the meantime for npm 4+5 prepublish as an alias for prepare will still do whatever prepublishOnly does.

So for the time being all I've done is add prepare after prepublish in the install phase, the only other place where prepublish appears. And I think that's all that needed doing?

Do correct me if I'm wrong, first contribution to Yarn. :-)

**Comment by timoxley** [comment]
@SamHH you may want to investigate https://github.com/yarnpkg/yarn/pull/1499

**Comment by Kovensky** [comment]
Oh, yeah, feel free to take over that PR/branch. I've been kinda out of time to update it :cry:

**Comment by timoxley** [comment]
@Kovensky @SamHH appears they're asking for an RFC https://github.com/yarnpkg/rfcs

**Comment by SamHH** [comment]
Just started a new job, not convinced I'll have the time to do this anymore. If anyone else does have the time do grab it :-)

**Comment by bestander** [comment]
Done in https://github.com/yarnpkg/yarn/pull/3004
