### ISSUE TITLE
"yarn remove" doesn't work for GitHub repos

### ISSUE THREAD

**Issue by joshkel** [yarnpkg/yarn#1506]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

When used with a GitHub repo, "yarn add" installs the package off of GitHub as expected, but "yarn remove doesn't remove it.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
yes '' | yarn init
yarn add brehaut/color-js
yarn ls
# Package is installed, as desired.
yarn remove brehaut/color-js
yarn ls
# Package is still installed.
```

**What is the expected behavior?**

Running "yarn remove" with a GitHub repo should remove a package, just like running "yarn add" with a GitHub repo add it.

The workaround is to use the package name, not the GitHub repo name (`yarn remove color-js` in this example).

**Please mention your node.js, yarn and operating system version.**

Observed in Yarn 0.16.1 on Node 4.6.1 on Ubuntu 14.04 and in Yarn 0.16.0 on Node 6.8.1 on Windows 10.

**Comment by wyze** [comment]
Tested on `master` and got a different result:

```sh
$ yarn remove brehaut/color-js
[1/2] Removing module brehaut/color-js...
error This module isn't specified in a manifest.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
```

**Comment by wyze** [comment]
After working on allowing this functionality it seems more of an enhancement than a bug. Regardless of the install method used, whether it was npm registry, github, local file, in the end they still have a package name, which is the key that ends up under `dependencies` in package.json.

The `remove` command expects just the package name. I'll submit a PR to open discussion for this and see if the other team wants it, because it also adds some tests around the `remove` command.

*Note: `npm remove` doesn't handle this functionality.*

**Comment by joshkel** [comment]
Thanks for the quick reply. Yarn 0.16.1 acts like it's removing a package but doesn't actually do so, which I'd consider a bug. Since `master` can correctly clue the user in that something is wrong, I agree that this is an enhancement (and have no problem with being told "just use the package name instead").

**Comment by wyze** [comment]
After thinking about this a little more I think the current functionality is fine. On master, and in the next release, you will get an error when the package isn't found instead of appearing successful. I'm going to modify my PR to remove the functionality and update it to just contain tests.

Thanks for the report!

**Comment by kallada1978** [comment]
I'm still getting this error:
$ yarn remove eact-router-redux
yarn remove v0.27.5
warning package.json: No license field
[1/2] Removing module eact-router-redux...
error This module isn't specified in a manifest.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.

**Comment by tirli** [comment]
@kallada1978 You have no such package in your repo. You have a typo. It should be `react-router-redux`, not `eact-router-redux`
