### ISSUE TITLE
`yarn outdated` shouldn't show a package@next

### ISSUE THREAD

**Issue by octref** [yarnpkg/yarn#1562]
yarn v0.16.1

![image](https://cloud.githubusercontent.com/assets/4033249/19839392/f434fe40-9e9d-11e6-9135-58649873b186.png)

I have this in my `dependencies`:

```
    "vuex-router-sync": "next"
```

3.0.0 is apparently not outdated compared to 2.1.1.

**Comment by goenning** [comment]
I always found that to be very confusing. It turns out that `npm outdated` will give you the same output.

According to [src/cli/commands/outdated.js](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/outdated.js), it'll be hide from list only if `current === latest`. 

Not sure if Yarn is supposed to follow NPM on this, but IMO `outdated` should hide packages that `current >= latest`.

**Comment by pluma** [comment]
Intuitively "outdated" means "lower than latest", so "greater than latest" shouldn't be shown as outdated. Such a comparison should be trivial using the `semver` package but of course it's a bit slower than using a simple equality check.
