### ISSUE TITLE
Request: package up progress bar 

### ISSUE THREAD

**Issue by joeybaker** [yarnpkg/yarn#1624]
That's a pretty nice progress bar you've got there! ![](https://cloudup.com/c08G7uDD4SZ+) 😃 

It's a pretty pretty reliable implementation and there's a dearth 🗑 of good terminal progress bars in the JS package community. 

It would be great if it was split off into a separate package! 📦

**Comment by kittens** [comment]
We'll eventually split Yarn up into multiple packages like we did with Babel but we're pretty far out from that. We have enough work supporting the growing Yarn ecosystem and users let alone also supporting a bajillion micromodules. We'll come back to this in the future once we're more stable. It's easier for us to move fast by making it internal instead of dealing with lots of different packages and cross organisation of them.
