### ISSUE TITLE
Why does yarn use ^ versions by default?

### ISSUE THREAD

**Issue by appsforartists** [yarnpkg/yarn#1676]
**Do you want to request a *feature* or report a *bug*?**
feature?

**What is the current behavior?**
`yarn add` uses `^` versions in `package.json`

**If the current behavior is a bug, please provide the steps to reproduce.**
```
echo "{}" > package.json
yarn add typescript
cat package.json
{
  "dependencies": {
    "typescript": "^2.0.7"
  }
}
```

**What is the expected behavior?**
```
{
  "dependencies": {
    "typescript": "2.0.7"
  }
}
```
Yarn prides itself on deterministic installs.  Keeping with that philosophy, it ought to depend on a specific version in `package.json`.

**Please mention your node.js, yarn and operating system version.**
macOS 10.11.6
node v6.2.1
yarn v0.16.1

**Comment by ljharb** [comment]
Because semver ranges are the correct default - it's also what npm uses as the default.

Why would you not want a `^` semver range, especially when you have `yarn.lock` to lock down the dependency graph?

**Comment by appsforartists** [comment]
I know it's what `npm` uses by default; isn't that how `npm` ended up with the determinism problem in the first place?  

My package depends on a `^` version of some dependency, which depends on a `^` version of some dependency.  One of them accidentally makes a change that breaks my app and publishes it as a minor version.  The next guy comes along to install my project, everything looks broken, and nobody can figure out what broke.

As I understand, `yarn.lock` solves this problem if everyone downstream uses `yarn`, but if somebody uses `npm`, they still risk ending up in determinism hell.

I naïvely expected a project that values determinism enough to write a whole new package manager based on it to use strict versions; then again, that would put you at risk of having 11 patch versions of the same module.  So I guess you let `package.json` use `^`s, and hope everyone downstream uses `yarn`?

**Comment by ljharb** [comment]
No, that's not how npm ended up with a determinism problem - pinning versions in package.json doesn't pin subdependencies.

Since yarn.lock only matters when in a top-level app, there's nobody downstream - if you have a published reusable module, your yarn.lock will be ignored, and your consumers *want* the `^` so they can dedupe.

The benefits of semver come at a cost, and that cost is that if there's an unintentional breaking change, people might be broken. It's the final consumer's decision if they want to protect against that by using shrinkwrap or yarn - it's not the responsibility of the package author to handle that.
