### ISSUE TITLE
Yarn is deleting bower_components directory (which is making yarn unusable)

### ISSUE THREAD

**Issue by raghav135** [yarnpkg/yarn#1681]
We are using "private bower" along with "sinopia". Some repositories are private and others are public.

In our app, when we use yarn, the behavior is to just empty contents of bower_components directory :(

Am I missing something? Because of this issue, we are not able to use yarn.

Is there any way to tell yarn not to delete bower_components?

os : ubuntu 16.04.1
node.js : 4.2.6

**Comment by ericmdantas** [comment]
Hey, @raghav135.

This is a dup of https://github.com/yarnpkg/yarn/issues/616.

The workaround, for now, seems to have the following in your package.json:

```json
"scripts": {
   "postinstall": "bower install"
}
```

For more info, check the linked issue.

**Comment by raghav135** [comment]
Not able to understand how the other issue is closed, am I missing something?
I am still getting issue with latest release.

**Comment by kittens** [comment]
We've removed support for Bower, see #1441.

**Comment by Promixius** [comment]
I am in the exact same boat at @raghav135 
I already knew support for Bower was removed which in itself I get due to how bower is however there are packages we need from bower for front end and mostly we are using yarn/npm for dev tools but when ever I run yarn upgrade it cleans the directory of bower_components no matter where I make bower place the files it pulls down, this leads me to thinking that you missed something when removing support for bower.
So I for one do not understand why you closed this issue as it is not resolved in any shape or form.

**Comment by wyze** [comment]
The fix that removed support for Bower hasn't been released yet.

**Comment by raghav135** [comment]
May I request a release? Or may I know the date of next release?
Thanks.

**Comment by wyze** [comment]
I'm not sure when the next stable release is, but if you would like, you could try out the nightly release by doing the following:

```
wget https://yarnpkg.com/install.sh
chmod +x install.sh
./install.sh --nightly
```
