### ISSUE TITLE
Question: how to guide users of `npm install` to `yarn install` in development projects

### ISSUE THREAD

**Issue by graingert** [yarnpkg/yarn#1732]
**Do you want to request a *feature* or report a *bug*?**
Feature-ish, probably docs change

**What is the current behavior?**
running `npm install` ignores the yarn lock

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
running `npm install` should complain and ask the user to run `yarn install`

**Please mention your node.js, yarn and operating system version.**
nodejs 7.0.0

**Comment by alexanderwallin** [comment]
A `prepublish` script could echo something to the console, but not prevent the installation from happening. `prepublish` won't be run on a local `npm install` from npm@5, though.

**Comment by graingert** [comment]
@alexanderwallin can I get a preinstall script that won't run under yarn?

**Comment by kittens** [comment]
We aren't planning on adding any features that disallow packages to be installed with npm. We'd be forking the ecosystem and that's not something we want to consider at this time.

**Comment by graingert** [comment]
@kittens I don't mean packages on npm, only for local dev.

**Comment by alexanderwallin** [comment]
@graingert Maybe something like this would be useful to add as a dev dependency?

https://github.com/alexanderwallin/use-yarn-instead

**Comment by graingert** [comment]
I'd rather something with no deps...

**Comment by graingert** [comment]
@alexanderwallin that looks like it will still run if installed as a 3rd party package

**Comment by alexanderwallin** [comment]
Yeah, you'll see it when you first add it to the project. But since you're the one introducing it that doesn't really matter.

**Comment by rafayepes** [comment]
@kittens how do you use yarn inside teams? I'm trying to come up with a workflow for our team and I don't see how that could work if I can't make sure that every dependency is modified through yarn and I can avoid making changes on package.json via npm or via manual modification. Any thoughts?

**Comment by graingert** [comment]
I think you can run yarn install on CI then check if yarn.lock changed

**Comment by adjohnson916** [comment]
@alexanderwallin @graingert:
I've just released a module that includes a CLI to do this (useful for `preinstall` scripts): https://github.com/adjohnson916/use-yarn

Stay tuned, as I may have more ideas coming, especially around CI.

**Comment by adjohnson916** [comment]
@alexanderwallin @graingert 
I've also just released a helper for [Danger](http://danger.systems/js/) to check this on CI:
https://github.com/adjohnson916/danger-yarn-lock

**Comment by JasonKleban** [comment]
Am I missing something?  Now we have two lock files that can get out of sync with each other (it is not clear to me how to git merge the various lock files either, or what behavior we can expect when one of the lock files is behind the other).  npm install takes too long to run and [sometimes there is corruption between them](https://github.com/npm/npm/issues/17105).  Yarn is cool, but with node installed, there's always A version of NPM present, we still need it for publishing and script running.  It seems to me like a damn mess - but maybe I'm just not understanding.

If our team could reliably disable `npm install` and `npm install package` (because it's easy to forget and impact everyone) in favor of `yarn` then the workflow would be more clear.

BTW, this only works for `npm install` but not `npm install package`:

```js
    "preinstall": "node -e \"if (process.env.npm_execpath.indexOf('yarn') === -1) { console.log('\u001b[31mPlease use yarn for installing\u001b[0m'); process.exit(1); }\""
```

... and the error message is ugly with the full stack dump.

**Comment by graingert** [comment]
Fyi yarn automatically handles merge conflicts

**Comment by nghenglim** [comment]
FYI, in ubuntu, preinstall script does not stop from using `npm` if you use `npm install somepackage`.

I end up using `sudo mv /usr/local/bin/npm /usr/local/bin/unsafe_npm` :)
