### ISSUE TITLE
Add package without saving to package.json

### ISSUE THREAD

**Issue by whitecolor** [yarnpkg/yarn#1743]
It seem there is no possibility to install package using yarn without touching package.json? (like npm install without --save params). Shouldn't such feature be added?

**Comment by hpurmann** [comment]
No, this feature was left out intentionally. It's considered dangerous to install a package without being reflected in the package.json. Why do you wan't such a thing to exist?

From the [Facebook announcement](https://code.facebook.com/posts/1840075619545360)
> We removed the “invisible dependency” behavior of npm install <name> and split the command. Running `yarn add <name>` is equivalent to running `npm install --save <name>`.

**Comment by reallistic** [comment]
I use to used that feature pretty often to test things. Especially when I'm working with a library that I maintain and need to install a local version (which creates a `file:` dep) just to test out my changes before creating a release.

While I agree npm's implementation to do it by default was a poor choice, I think this is something that can come in handy when used explicitly.

**Comment by whitecolor** [comment]
Yeah I think allowing it to do with explicit flag would be nice to have,  currently for this one can still use `npm i` =) but just to get rid of npm need.

**Comment by kittens** [comment]
We explicitly don't support this as it's an imperative change to `node_module` that would be wiped with subsequent `yarn install`s since we consider `package.json` and `yarn.lock` to be the source of truth.

**Comment by GuillaumeLeclerc** [comment]
We have a dependency that can't be installed easily on windows (libxslt) so:

- For windows: developers unzip it in their node_modues
- For linux: developers install it without save (if it's in package.json then developers using windows can't perform any install because build will fail)

Is there a clean way to do it using yarn (or any better way to achieve this result) ?

**Comment by jbucaran** [comment]
@GuillaumeLeclerc What about `yarn add -D xxx` and remove the entry from the package.json yourself?

**Comment by GuillaumeLeclerc** [comment]
It will be removed the next time another package is added ? Won't it ?


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Jorge Bucaran <notifications@github.com> Date : 08.02.17  09:43  (GMT+01:00) À : yarnpkg/yarn <yarn@noreply.github.com> Cc : Guillaume Leclerc <guillaume.leclerc.work@gmail.com>, Mention <mention@noreply.github.com> Objet : Re: [yarnpkg/yarn] Add package without saving to package.json (#1743) 
@GuillaumeLeclerc What about yarn add -D xxx and remove the entry from the package.json yourself?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yarnpkg/yarn","title":"yarnpkg/yarn","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/yarnpkg/yarn"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jbucaran in #1743: @GuillaumeLeclerc What about `yarn add -D xxx` and remove the entry from the package.json yourself? "}],"action":{"name":"View Issue","url":"https://github.com/yarnpkg/yarn/issues/1743#issuecomment-278266262"}}}

**Comment by jbucaran** [comment]
@GuillaumeLeclerc Unfortunately, yes.

**Comment by reallistic** [comment]
@GuillaumeLeclerc You might want to clean up your comment...

**Comment by themadcreator** [comment]
Please add an argument like `yarn add --no-save` so that I can install a module without altering my package.json or yarn.lock. I often find myself needing to test modules before committing to them.

I can't use normal `npm install` because I get "Maximum call stack size exceeded". So yarn is the only viable way to install.

Please don't make me revert changes to package.json yarn.lock!

**Comment by viveleroi** [comment]
For me, this is biting me because I'm trying to install a peerDep. Yarn has no way to install peer deps during `install` so I have to manually do it. I can't `yarn add <package>` without having it get added to the package.json/yarn.lock. I'm stuck.

**Comment by hpurmann** [comment]
@viveleroi this sounds totally correct. Why would you want to install the peer dependency without adding it to your `package.json`?

**Comment by viveleroi** [comment]
@hpurmann Because it's duplicating my `peerDependencies` into`dependencies` (or `devDependencies` if I use `--dev`). If that's what's intended then it's certainly not intuitive.

**Comment by loading-wyn** [comment]
@hpurmann I want to public a react component, so react shoulde be a peerDep. However, I need to install react in the project to develop it.

**Comment by khalid-elabbadi** [comment]
just add --no-save => it is so important
i need to skip a particular optional dependecy for a specific package. i can not do that with your yarn. may be with --no-save option i can work it arround

**Comment by kavi87** [comment]
Because `yarn link local-pkg` does not install the dependencies of local-pkg in the host app I would like to install them directly but not save them to the app package.json since they will be brought by local-pkg once it is published.

**Comment by OoDeLally** [comment]
I don't understand why the owners are so opiniated about this. If you see a usage of it doesn't mean there is none. I believe if people ask for it, it means they need it, and they are not necessarely stupid.
Adding a optional `--no-save` option would solve some people's problem and bring no drawback at all.

**Comment by simoncpu** [comment]
I'm trying to use Yarn for a NodeJS project that's run on AWS Lambda. I'm kindda surprised why this feature isn't supported. My use case is that I need to install aws-sdk on my local dev environment, but I don't want it to saved in `package.json` because AWS Lambda already have this installed on their environment. Including aws-sdk means that our final package would be bloated.

**Comment by namgk** [comment]
yarn link and yarn add cannot live together. yarn add depends on package.json while yarn link just links the local packages over to another location. 

Suppose you're developing a package X that depends on Y, you're both the developer of X and Y so you keep X and Y locally and link Y into the directory of X. When you do yarn add in X, it wipes out the link to Y.

How do you get around this?

**Comment by PutziSan** [comment]
For such cases you could simply use the npm-commands to install without creating a footprint on package json or yarn.lock:

`npm install [packages ...] --no-save --no-package-lock`

**Comment by namgk** [comment]
ok so now I can't live without npm then

**Comment by heikomat** [comment]
I was using `npm install` in one of my scripts that installs dependencies of local sub-modules to the main node_modules. This is working fine with npm4, but is completely broken with npm5, as npm5 just decides to nuke some packages during install -.- (see https://github.com/npm/npm/pull/18921)

For that reason, i was trying to replace the `npm install` in my script with yarn, but i can't really do that, if yarn always touches the package.jsons of the local submodules during installation, at least not without my script getting quiet messy and "cleaning up" after yarn

**Comment by alexindigo** [comment]
You already have `--no-lockfile` option, so it's makes node_modules folder out of think,
but devs still need to have workarounds to keep package.json immutable.

Thank you.

**Comment by bigeasy** [comment]
I like how every time someone explains their peculiar use case for installing a module but not recording it the maintains come back in and recite their shibboleth. Makes it easy to feel confident in your obstinance if you can couch this same request from many different people as suffering from a moral failing. As a compromise, maybe we could name the switch `--i-am-a-heritic-and-a-bad-programmer`?

**Comment by alexindigo** [comment]
And in my case I wanted to use it as a workaround for #4297 issue :)
Artificially limiting developers to do things might render your product unusable in certain situations.

**Comment by Qix-** [comment]
Wait are you kidding me? This is a travesty. Please stop dictating how every developer workflow should work, ever. This is exactly why NPM didn't suit us and we moved to Yarn. This ideology that "package.json and yarn.lock should be source of truth" is nonsensical. Packages should be install-able without modifying the source code. Simple as that.

Come on, maintainers. It's obvious there's a real need for this by the community. Please stop shutting down intelligent conversation with unfiltered and misplaced philosophy.

**Comment by bigeasy** [comment]
Now I finding that `yarn` breaks my tests because I have modules where I need to test `require` and in order to test require I commit an example module into `./node_modules` . Yarn is deleting the example modules when I run `yarn install`. More "source of truth" pedantry, I assume.

**Comment by ggranum** [comment]
use case: Tool *I* use requires a package. Team doesn't use that tool. Team (justifiably) doesn't want that package installed.

**Comment by jgerstle** [comment]
This is seriously frustrating I use codelyzer for angular style guide, but the rest of my team does not and it has no affect on code functionality. The only way to get it to work now, is to add it to my yarn lock and just assume my yarn lock hasn't actually change, or to use npm even though my team uses yarn. Both of these are horrible options.

**Comment by simoncpu** [comment]
It's 2018 already but this feature hasn't been added yet despite the numerous valid use cases.

**Comment by erikmueller** [comment]
Just to give another example why this might be useful: 

We have a script that automatically updates dependencies by installing the new version, running the tests and THEN saving it to the `package.json`/`*.lock` and committing that change OR rolling back if there was an error. It's way easier to just run `yarn` again instead of remembering the old version and explicitly `adding` that again. 

Moreover it feels cleaner to not mutate your single point of truth (`package.json`) before "absolutely" being sure that you are able to really update this dependency without breaking a test. For now you end up with a `package.json` (even if it's temporarily) containing a dependency that breaks your code.

**Comment by LoveIsGrief** [comment]
There are many valid use-cases for this issue. Would the yarnpkg maintainers be willing to accept a PR if one were to be created?

**Comment by accnops** [comment]
In the meantime, I use following script in the `scripts` section of `package.json`:

    "scripts": {
      "install-sneaky-package": "npm install -g sneaky-package && cp -r $(npm root -g)/sneaky-package ./node_modules/sneaky-package"
    }

**Comment by alexindigo** [comment]
There is no alternative, npm5 is messy as my life.

And don’t forget to copy symlinks in .bin folder. ;)

**Comment by HyperBrain** [comment]
For me `chmod 444 package.json` and `yarn add XXXX --no-lockfile` at least works around the issue for local development and testing.
The add ends up with an (expected) permission error, but the added module is present in node_modules afterwards and I am able to test with peer dependencies locally installed but not persisted in the package.json but as peer dependency.

**Comment by mhelvens** [comment]
I sometimes require a debugging library temporarily, like `why-is-node-running`. I know I'll want to get rid of it after a single use, and a `--no-save` option would allow me to install-and-forget, without running the risk of polluting my dependencies.

**Comment by brendan-hurley** [comment]
I'm using Lerna, and I really just want to install _only_ Lerna in one of my CI steps, for the publish stage, as the project is already built in a previous step and artefacts carried over. Is that a valid scenario?

**Comment by Legends** [comment]
It would save me some steps, if this feature would be available.
My `node_modules` is in .gitignore anyways.

**Instead of:**
```
git clone external-package (needed for temp testing only)
yarn install
yarn link
```

go back to my original repo
`yarn link external-package`

**just:**
original-repo:
`yarn install external-package --no-save`

**Comment by dbsanfte** [comment]
As part of our build pipelines, we need to install nsp and run it, exporting a dependency-check.xml. 

I don't see why this simple tool install needs to be reflected in the package list, it just means I now need to do a `git checkout ${BRANCH_NAME}` to undo the modifications before I can push tags.

I'm not trying to modify the source. I don't want to and it isn't my business, that's up to the dev team. You're making my life a little bit harder for some abstract philosophy. Stop it.

**Comment by HyperBrain** [comment]
Any idea, why this issue has been closed? Has the `--no-save` switch been added in a PR?

**Comment by amphro** [comment]
There are times I want to change a module's version that is brought in from a dependency. For example, `@types/sinon` brought in by another dev dependency recently broke my tsc. I don't want `@types/sinon` to my dev dependencies but I want to manually change the version with `yarn add @types/sinon@4.3.3 --no-save` so I can keep working. Instead, I just switch back to npm. Super frustrating.

**Comment by JasonKleban** [comment]
I have a production only dependency (appdynamics) that is very much a hack itself of platform-specific binaries.  Turns out we don't even need it on the dev machines.  Adding the `yarn add ... --no-save` would let us deploy cleanly without the script endangering the package.json (especially since package.json, obnoxiously, can't have comments explaining the purpose of each script or dependency)

**Comment by Qix-** [comment]
cc @kittens 

Please either address this incredibly popular issue or lock it as resolved. It would be highly appreciated to have a concrete answer in response to all of the criticisms raised above.

**Comment by alexindigo** [comment]
And community is ready to provide the feature, just let us know if you'd accept such pull request. Thank you.

**Comment by SilencerWeb** [comment]
haha, still not implemented, niiiiice

**Comment by erikmueller** [comment]
>  Why do you want such a thing to exist?

Was the exact same thing people said about JSX when it first came out mixing templates and logic. If it's possible and has its usecases, the correct question should be why not? I mean it's a flag, it's not default behaviour so you are telling yarn explicitely (aka I know what I'm doing).

**Comment by VrajSolanki** [comment]
@kittens @hpurmann 
I have multiple packages in based on react and these have sub-module dependencies over on another. so I have react and react-dom as a peer-dep but when I need to build these packages individually I do need react and react-dom. 
I guess this would be an apt use-case for installing packages locally without having them added ad dep.
I would not like to have npm for such a trivial use in my project.
Any updates, waiting for something similar to `--no-save`.
I guess there is no harm adding a feature if the community demands, assuming the developer is aware of its side effects(loosing the local packages as soon as you run yarn install.)
Thanks

**Comment by leonaves** [comment]
Oh I didn't realise the yarn maintainers were pompous dickholes. Noted.

**Comment by olstenlarck** [comment]
Handy trick is `yarn add --dev pkg && yarn remove pkg`. It does the same thing. THe lockfile stays as it was before that, so untouched.

**Comment by wuservices** [comment]
> No, this feature was left out intentionally. It's considered dangerous to install a package without being reflected in the package.json. Why do you want such a thing to exist?

@hpurmann if you're depending on a Git repository AND reference a specific revision, this seems fairly safe.

In my case, I'm trying to depend on a Git repo that just has some assets in it. It doesn't make sense for that repo to have a `package.json`, and let's just assume I don't even control that repository. If I want to depend on a specific branch or commit hash of that Git repo, why shouldn't I be able to just because it doesn't have a `package.json`?

**Comment by silentorb** [comment]
This was mentioned by @Legends earlier but is worth emphasizing:

One workaround for some cases is to install the needed package in a separate folder and `yarn link` the needed package to wherever it would have otherwise been added.  It's not ideal but can help.
```
cd /third-party
yarn add foo
cd node_modules/foo
yarn link

cd /my-project
yarn link foo
```

**Comment by tunnckoCore** [comment]
@silentorb definitely not worth, imho. The `add + remove` is exactly what is done with the `--no-save` in npm. It does not mess with the system links and is not touching the lockfile in a bad way - meaning it's the same after the `yarn remove`.
Not to mention that if you want to do that thing programmatically then definitely creating dirs, linking and etc is not the way to go.

>  some cases 

For example? Pretty weir ones for sure?

**Comment by 18steps** [comment]
@hpurmann @kittens 

So what is the recommended practice for developing a package with peer dependencies?

If I have e.g. React as a peerDependency in my package, should I add it as a devDependency as well in order to get imports resolved?

**Comment by alexindigo** [comment]
@18steps check out https://www.npmjs.com/install-peers

**Comment by suyanhanx** [comment]
There is some situations to use this feature. 

Just like in CI lifecycle I added some coverage reporter. But I can't bring them to `package.json` then affects to publish `NPM`. 

Save or no save, I think this choice should be up to the developers themselves not the tool.

**Comment by mhelvens** [comment]
Alright, let's try to look at this from the maintainers' perspective. I can definitely see downsides to a naive `--no-save` solution. We didn't get a very thorough explanation here, but I'll try to construct a steel man. Maybe they can correct me. Maybe we can find a compromise. @kittens @hpurmann

(Sorry, this ended up longer than I intended.)

Dependency management for modern Node- and web-applications is a bit chaotic. And yet, we want a system that gives us both reliable automation and a certain level of control and predictability, with features like deduplication and reproducible builds.

To get a handle on the complexity, we need to know what's installed and why, and we need a single source of truth to resolve any inconsistency. At the risk of stating the obvious, `node_modules` itself can't fulfil either of those roles. It's too slow to traverse, too large to transmit, too fine-grained to version-control, and it can't encode the 'why' aspect. That's why we have `package.json` and `yarn.lock`.

Yarn encapsulates the complexity of `node_modules` by giving us restricted access through an interface. If we promise not to break encapsulation, we get certain guarantees in return, like deduplication and reproducible builds. If we install things in `node_modules` without a corresponding change in `package.json` and `yarn.lock`, we lose those guarantees.

Moreover, that's an unspoken contract that many developers aren't explicitly aware of. When they break it, they don't do so knowingly. So when things go wrong, Yarn may be unfairly blamed. Plus, making a tool that's difficult to shoot yourself in the foot with is not a bad design philosophy.

**However**, I can see several reasons to compromise:

* There seems to be a definite need here. Just look at the many use-cases listed in comments above, and the 'thumbs up' / 'thumbs down' ratios. The maintainers' apparent stubbornness in the face of such a one-sided response doesn't make Yarn look too good.

* There are solutions to be found that may work for everyone. For example, introduce a new file `yarn.local.lock`. Developers would put it in their `.gitignore`, and it would keep a record of all packages installed with the `--no-save` flag and their dependencies.

  In order to keep `yarn.lock` isolated from this, deduplication and flattening of the 'local' dependency tree is restricted. The local lock file may adapt to match a version in the main lock file (and dedupe in that case) but not the other way around. As a result, many transitive local dependencies might not be flattened into `node_modules`.

  With this solution, Yarn can continue to keep track of all packages, developers are able to install stuff without polluting their repo, and we preserve reproducible builds. (There is also room for a `package.local.json` with a `devDependencies` section, but I'm not sure it would be required.)

* People are already using workarounds to get what they want anyway, at least three of them described in comments above. But they are inconvenient to use, don't offer the same guarantees and require that developers fight against Yarn to figure them out. It's the worst of both worlds.

I might have missed something, but this seems like a conversation worth having.

**Comment by hpurmann** [comment]
I probably should have answered some time ago, right after @viveleroi explained his quite valid use case (which a lot of you seem to have). Back then I did thumbs up his response, which is obviously not enough to get noted.

I changed my mind. Usually, people want a lot of things and if the maintainers are accepting every feature, the software becomes bloated. I don't have this use case but I see many people wanting it.

I can't decide anything though. I'm not a maintainer of this project.

@Vheissu What is the issue with `yarn add --peer <dep>`?

**Comment by scottdickerson** [comment]
for me yarn add --peer <dev> works UNTIL you add another package, at which point the existing peer deps are removed from the local install and you have to manually readd them.

**Comment by jhford** [comment]
I would like this feature because today because I am writing an example implementation of my library using express, but none of my code depends directly on express.  I don't want anything to install or depend on Express, but I do want to install it into my current directory.

**Comment by unional** [comment]
Just like @brendan-hurley @suyanhanx, I have dependencies that I want to install in CI and not locally.
I want to keep my local dependencies at a minimum so that we don't have to bloat up `node_modules` and cost us time and space for every developer working on the project.

Packages that are needed in CI but not locally:

- CI specific tools: semantic-release, green-keeper-lockfile
- Coverage reporting tools: codacy-coverage, coverall
- Test reporting tool for CI: jest-junit, etc.

**Comment by otoinsa** [comment]
Here is why we need this feature:

Using `yarn link` wont link the dependencies of the package over, so you need to install them in
the linked destination - having these external dependencies added to `package.json` just makes it so much inconvenient.

Either yarn link has to add dependencies or provide a way of excluding the in destination `package.json`

**Comment by NickHeiner** [comment]
I have a pretty esoteric use case, but this would be helpful for me. I fully understand why it's important for `yarn.lock` and `package.json` to be the source of truth, and that if I used a `--no-save` command, my changes would be wiped out on subsequent `yarn` commands.

That said, I wish that `yarn` would trust me to know what I'm doing and allow me to pass the `--no-save` flag. If I run into any of the problem cases, I'll know exactly what went wrong, and that I only have myself to blame. :smile:

**Comment by Coly010** [comment]
My use case?
I run a 64-bit win machine. 
Prod machine is 32-bit.

Node-sass dependency we have only supports 32-bit unless we update the package.

Not changing the dependency in the package.json or yarn.lock to support a dev machine.
So would like to locally install the latest node-sass to support 64-bit, but not affect the package.json and yarn.lock

**Comment by tats-u** [comment]
I'd like to install `@types/*` packages to non-TypeScript projects without tainting `package.json` / `yarn.lock` for better completion in VSCode.

**Comment by TotooriaHyperion** [comment]
I use lerna with yarn workspace.
Antd's type definition breaks due to @types/react@16.8.12 update.
Antd will fix this at weekend.
But now I need to force the yarn to install a fixed version of @types/react@16.8.11 into workspaceRoot manually without affect the current package.json(since it will install the latest version automatically).

Keeping the default behavior of saving to package.json is right, but there are real cases that developer must install the module without affect the package.json. Especially when there are some unexpected breaking change in some packages.

**Comment by ghengeveld** [comment]
Here's another use case. I maintain a React library. Before publishing a new version, I want to run my tests against several versions of `react` and `react-dom`, to verify that my changes are backwards and forwards (`@next`) compatible. I was doing this using the setup below, but now I want to use Yarn's workspaces so I need to migrate to Yarn.

```json
"test:backwards": "npm i react@16.3.1 react-dom@16.3.1 --no-save && npm test",
"test:forwards": "npm i react@next react-dom@next --no-save && npm test",
"test:latest": "npm i react@latest react-dom@latest --no-save && npm test",
"test:compat": "npm run test:backwards && npm run test:forwards && npm run test:latest"
```

I can't have this script change my `package.json` as that would make my publish command (`pack publish`) fail due to unstaged changes.

**Comment by frederik-b** [comment]
I want to add additional packages in my CI pipeline for testing purposes without touching the package.json file (might be a readonly file mount).
These are not part of the dev components.
During development and testing on the dev machines, they shall not be installed and during build and prod they shall not be installed, they are only ever necessary and acceptable on the CI server during tests.

This works by just using npm, but yarn should be able to remove the depency upon npm.
This very well might bring us back to using npm only instead of yarn only.

Also it just breaks the promise of yarn being able to completely replace npm, because it just can't do what npm can.

Also yes absolutely hide this feature behind some flag because this shouldn't be a normal use case but an edge use case.

**Comment by spanasik** [comment]
are you kidding ? 3 years to add a simple switch ?

**Comment by Smona** [comment]
Another use case: We use a npm package (`git-hoooks`) for pre-commit checks. Not everyone on the team has node installed, so including it in package.json would break commits for some people. So I'm trying to create npm scripts to transiently enable/disable hooks by installing/removing git-hooks. Very disappointed to find out this seemingly simple & easy task is virtually impossible to accomplish with yarn.

If the worry is that yarn.lock will no longer be a source of truth for the contents of node_modules, well, what's so bad about that? Couldn't existing functions simply ignore the existence of the untracked dependencies? Yarn is a great tool and the maintainers have done a great service to the JS community, but they need to reconsider this decision.

**Comment by Ryuurock** [comment]
are you kidding ? 3 years to add a simple switch ?

**Comment by NickHeiner** [comment]
@spanasik and @Ryuurock: please be polite when discussing high-quality software that's provided to you for free.

This hasn't taken "3 years" because the switch is too complicated to implement – it's because the maintainers remain unconvinced that it'll be a net benefit for users. If you disagree with this, make an argument for the feature.

**Comment by alexindigo** [comment]
@NickHeiner here are 10 screens of arguments. And the main thing that drives frustration, is not that maintainers unconvinced, but that they're ignoring it, don't reply to arguments, when people "disagree with this, make an argument for the feature". And when people frustrated, of course they leave unpleasant comments. Please don't blame the whole thing on users.

**Comment by NickHeiner** [comment]
I agree that it would be better if the maintainers would address the discussion here. There's clearly interest from a broad set of people across several years. So perhaps my suggestion that @spanasik and @Ryuurock should just "make an argument" is unreasonable, because it would likely be ignored like everything else here.

> And when people frustrated, of course they leave unpleasant comments. Please don't blame the whole thing on users.

I disagree. This rudeness is still not a useful step forward, nor acceptable behavior among adults. Being impolite is a great way to justify the maintainers ignoring this further: "the thread is just trolls". 

Constructive ways to move forward:
1. Draw maintainer's attention to this thread on other channels (maybe they've ignored it) and ask them to at least acknowledge the arguments here, even if they don't agree.
1. Fork / replace yarn and govern the project in a way people are happier with.

**Comment by perezLamed** [comment]
> Handy trick is `yarn add --dev pkg && yarn remove pkg`. It does the same thing. THe lockfile stays as it was before that, so untouched.

Tested - does not work.

**Comment by perezLamed** [comment]
**My use case is the following:**
Some packages have optional addins that is loaded with 'require'. I do not want to add these add-ins to the devDependencies section so I do a 'yarn add my-add-in' and remove it manually out of the package.json file. On my cloud CI pipeline I use 'npm i' add them (for testing). On my local pipeline I do not want to use npm because it create an extra lock file. My best option now is to use npm and then delete their lock file (to remove the appearing second version of the truth).  

So after reading everything my question to the maintainers are this: 
- Why are you so inconsistent?
- Why not implement this philosophy right through every feature?
  - That is: Decide how things should be done for all of us and remove all other options from all features. Stay the course! Stay true to yourself! 

The undeniable fact is that all good software have config settings because **good software will allow the user to choose what is best for his situation**. And to always touch the 'package.json' file is good practice - but there exist edge cases where 'yarn' is just not up to the task because of this philosophy.

**I really like yarn because its simple and fast**.  It is really unfortunate that the maintainers are fighting a battle they are sure to loose - because the community is forced to revert back to slow reliable npm in order to make things work.

**Comment by foxbunny** [comment]
I feel disgusted that yarn makes me work in a certain way. I like to decide things on my own, and I don't like it when my tools tell me how I should work, insult to my intelligence being the least of the problems, and not being able to get things done being by far the biggest.

To believe in perfect rules and that there would never be an occasion to break them is naive. There's a difference between "best practices" and "do-or-die". As Oliver Wendell Holmes Sr. puts it:

> The young man knows the rules, but the old man knows the exceptions.

**Comment by NickHeiner** [comment]
Let’s turn down the temperature a bit. No one need feel disgusted by a
piece of software they’re allowed to use for free.

**Comment by foxbunny** [comment]
@NickHeiner Nobody can tell you how you need or need not feel.

**Comment by leonaves** [comment]
Make your own package manager, no-one's making you do anything.

**Comment by foxbunny** [comment]
> Make your own package manager, no-one's making you do anything.

So you are angry that I have openly expressed my feeling of disgust for what I think is not so great in yarn? If that is the case, I don't understand the logic.

**Comment by leonaves** [comment]
Not angry at all, just pointing out the error in your logic:

> yarn makes me work in a certain way.

Yarn isn't making you do anything, they've made a tool (for free) and it works in a certain way. If you don't like it use something else.

**Comment by NickHeiner** [comment]
@foxbunny I appreciate you clarifying your disgust. :) 

Even if you believe that it’s reasonable and just to feel disgusted in this case, I don’t think that language is a polite way to talk to the people who have built this freely-available tool for you. You can give constructive feedback while still being respectful.

**Comment by foxbunny** [comment]
@NickHeiner I believe you are confusing my description of my feelings with an insult. I didn't say Yarn developers are disgusting people, or that their work is disgusting. I said that I *feel* disgusted because of something yarn does. I see no way you could be reasonably offended by or dispute that.  

Also, I believe I am free to state my feelings and opinions clearly regardless if whether the tool is free or whether I use it (which I no longer do). If you find my comments too offensive to read still, please let me know and I will remove them myself.

**Comment by leonaves** [comment]
I feel like you're an asshole.

**Comment by khalid-elabbadi** [comment]
@whitecolor the team has got a point. That option --save is stupid. Yarn guaranties equilibre between node_modules, package.json and the lock file  and that's great. That's safer .... the npm --save is dangerous. It let me down many times

Please STOP IT

**Comment by leonaves** [comment]
Or how about everyone just use the tool that works the way they think is better and calm down.

**Comment by pie6k** [comment]
My use case is

I want to update sub-dependency of our app
I link this dependency with `yarn link`
I then use linked one in our app
I add some dependency in our library
Added lib dependency is not installed in the main app after `yarn install` (wtf no.1)
Then I think, ok, let's just add it quickly without saving to the app so I can just check if stuff works before I publish update to our lib
But - nope.

Thanks

**Comment by frontendbuddy** [comment]
Sorry to see the community ignored by the authors.

**Comment by NickHeiner** [comment]
As an open source volunteer, one needs to have a coherent philosophy or the
project will degrade into a ball of mud. This means sometimes telling
people “no”. If you disagree, you’re welcome to make your own package
manager, just like yarn replaced npm.

**Comment by brendan-hurley** [comment]
> I'm using Lerna, and I really just want to install _only_ Lerna in one of my CI steps, for the publish stage, as the project is already built in a previous step and artefacts carried over. Is that a valid scenario?

^ my original comment - I honestly don't know why I'd ever need this, and I didn't know this thread would blow up so horribly - but it's amusing to see emails about it years on.

I'm inclined to agree with the maintainers here:

1. I'm unconvinced by my own argument. I guess the maintainers were being polite by not calling it out for being a stupid argument.
2. Even if someone _does_ raise a PR, it would mean that ongoing maintenance of the feature would be the further burden the maintainers, blocking them from maintaining the core product.
3. This kind of feature would be misused by unassuming newbies and/or otherwise relatively unskilled consumers of yarn, further perpetuating point 2.

In any case there's probably a better, more architecturally sound way to mitigate against the need for this feature.

**Comment by darionco** [comment]
I created [`yarn-add-no-save`](https://github.com/darionco/yarn-add-no-save) to achieve this functionality. It can be installed local to your project or globally, once installed you can simply run:
```
$ yarn add-no-save <packages>
```
My use case is to test modules that declare `peerDependencies` so the tool has some options to automatically install them, to see all the options run:
```
$yarn add-no-save --help
```

NOTE: I am aware that saving a package to install packages without saving them is ironic and basically defeats the purpose, but this is the best I could come up with and it fits my needs.

**Comment by alexindigo** [comment]
This is very helpful, especially peerDeps support. Thank you.

**Comment by danielo515** [comment]
There are several good arguments for this feature. It's not like doing it the default, people is asking for it to be behind a clear flag that only people in need for it will use it. Currently, like some other, I need to do some testing during CI with other library versions that **I don't want to save**. I can't understand what is so hard to understand here.

**Comment by FrankFang** [comment]
I have to `yarn install xxx` then `yarn remove xxx`.

**Comment by callramesh** [comment]
Not sure if this usecase was ever discussed . Let me try to explain my situation - I have bunch of packages interdependent on one another in one repo. They all  use the same external dependencies with  a common package at root servicing sub projects underneath, each local package needs to be built in the order for the next to consume. To start I don’t have any local packages defined in my root package.json. After one full cycle of building all components, I end up having a fully updated root package.json with those local dependencies . Now when this updated one gets built on CI- all those local packages added are going to fail due to non availability. We have to remove those newly added entries to make it work in CI.

**Comment by Youzhigang** [comment]
> I have to `yarn install xxx` then `yarn remove xxx`.

the same

**Comment by slifty** [comment]
Here's a use case for wanting to be able to do this:

We're building a tool with a modular ecosystem for "appliances" within the tool, and the plan is for a local instance to be set up with those appliances, and have them activated dynamically via configuration.  The appliances are published to npm (and could be invoked outside of our framework if someone wanted).

Our project does NOT *depend* on these packages, so saving to `package.json` would be inappropriate.  A specific instance's configuration might call for one of the packages to be installed locally.

Lacking this feature is a tragically limiting decision for our project.  Thank goodness npm exists!

**Comment by seelts** [comment]
Before I read "maintainers" reply here, I thought I was the most stubborn person ever.

Almost 3 years... 🤦

**Comment by NickHeiner** [comment]
"Stubbornness" is not the same as "having a design vision and not implementing everything anyone asks for".

**Comment by alexindigo** [comment]
> "Stubbornness" is not the same as "having a design vision and not implementing everything anyone asks for".

Design vision describes happy path, and escape hatches as the one requested here, add to the usefulness for the wider community.

**Comment by Gustavo6046** [comment]
Why not just add a section to the lock file that keeps track of "freeform" installs, and incremental snapshots of the status quo (in `node_modules`), to make those safely reversible? Or maybe put dependencies in a folder separate from node_modules, and use node_modules just to keep links exposed to its package, so Yarn can actually manage stuff on its own and not worry about invisible installs overwriting and breaking stuff.

I feel like everybody's pushing against each other up a narrow hill when we could just go around it.

**Comment by cefn** [comment]
The below entries in my package.json have been a short-term workaround for my case - developing a React library.

It means the `yarn test` command can be provided with temporary copies of test dependencies for the duration of the test script.

```
    "pretest": "yarn add --dev react",
    "posttest": "yarn remove react; yarn add --peer react",
    "test": "jest"
```

Performing local tests is the only circumstances a package is (temporarily) needed. In all other cases it should be provided by the (singleton) version of react within the user's own repo. Basically the `react` package is required as a peerDependency to flag to users, but must not be either a dependency or a devDependency as this breaks React in production at runtime. This of course means you can't run any tests within your package which have a react dependency!

See https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react for the runtime error which react apps hit when react is either a dependency or devDependency of any imported library. That webpage hopefully explains how the opinonated feature-omissions from `yarn add` impact react library developers specifically. Perhaps a few contributors to this thread are developers of React libraries?

**Comment by cefn** [comment]
Actually after a bit more experimentation, while this leaves the package.json in a good state to be committed, it still messes with the local node_modules in a way which interferes with bundling, causing the tested package to have its own copy of react after running tests and therefore bundling it incorrectly and creating the React error described. 

That's because as far as I can see there's no way to use the yarn cli to add back a peer dependency without actually installing it. So finally my package.json has these as a workaround instead...

```
    "pretest": "npm install react --no-save",
    "posttest": "npm uninstall react; rm package-lock.json",
    "test": "jest",
```
