### ISSUE TITLE
Cannot globally install 0.17 on Ubuntu due to spawn-sync issue

### ISSUE THREAD

**Issue by joefiorini** [yarnpkg/yarn#1821]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?** 

post-install exception trying to install yarn on ubuntu server due to ForbesLindesay/spawn-sync#42. I know the issue is with spawn-sync, but with yarn being such a core dependency, it should not depend on something that requires special workarounds to install on a build server.

**If the current behavior is a bug, please provide the steps to reproduce.**

`npm install -g yarn` on an Ubuntu server (not sure if it happens on all configurations)

**What is the expected behavior?**

yarn installs on Ubuntu CI servers without errors

**Please mention your node.js, yarn and operating system version.**

**Comment by joefiorini** [comment]
Also worth mentoining, the `spawn-sync` dep exists because of the addition of `inquirer` as a dependency in 0.17.

**Comment by Daniel15** [comment]
Please try installing Yarn through the Ubuntu package repo rather than npm. The Debian/Ubuntu package has some tweaks to make it perform better and install quicker on Ubuntu compared to installing via npm.

**Comment by joefiorini** [comment]
Unfortunately, the way our images are built we don't have access to a system package manager like `apt-get`. That method will not work for us.

**Comment by bestander** [comment]
I think yarn can't protect from a subdependency that has a problem being installed on ubuntu because Debian has this weird nodejs/node name clash.
There are ways around this: 
- send a PR to inquirer or spawn-sync to fix this.
- use another method to install yarn (debian packagers, single file build)
- install nodejs-legacy on ubuntu as suggested on the linked issue

I'll close this issue for now but welcome discussion and other alternatives.
PRs are welcome

**Comment by arnoldgr** [comment]
Any news on this? I am getting it and using the latest versions ..
