### ISSUE TITLE
Log information about what was installed 

### ISSUE THREAD

**Issue by martynchamberlin** [yarnpkg/yarn#1929]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Let's say I have a super simple `package.json` file: 
```
{
  "name": "test-yarn",
  "version": "1.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
    "dependencies": {
    "admin-lte": "2.3.3"
    }
}
```

Yarn is not outputting what new dependencies were installed when running `yarn install`:
```
$ yarn install
yarn install v0.17.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 1.28s.
```

In contrast, `npm install` provides helpful information: 
```
$ npm install
test-yarn@1.0.1 /Users/martynchamberlin/Desktop/test-yarn
└── admin-lte@2.3.3

npm WARN test-yarn@1.0.1 No description
npm WARN test-yarn@1.0.1 No repository field.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
n/a

**What is the expected behavior?**
We would like to have this information logged during `yarn install` (if you don't want this default like NPM has it, it might make sense to make this a flag, so it's optional). The reason we want this is because when we do a deploy, we need to be able to confirm a dependency version, and looking at the deploy log is a lot faster for the Ops team than hunting down a `package.json` and `yarn.lock` file. 

**Please mention your node.js, yarn and operating system version.**
- Node: v6.4.0
- Yarn: 0.17.2
- OS: macOS Sierra

**Comment by markstos** [comment]
This feature seems like it would just be repeating what's in the `yarn.lock` file.

I'm not sure why the yarn.lock should be hard to hunt down if it's always in the same place, but adding `cat yarn.lock` to your deploy script would add the output of what `yarn` is installing there.

The difference with `npm` is that `npm` is potentially instalilng different versions because it doesn't use shrinkwrap by default, so it's particularly valuable to know how NPM is resolving the dependencies. With `yarn`, the answer is always consistent in what's in `yarn.lock`, so it seems noisy to repeat the contents of the file each time.

**Comment by martynchamberlin** [comment]
Thanks for weighing in @markstos. I've talked it over with the team and we've decided this feature isn't super important. Closing this.
