### ISSUE TITLE
Feature: Allow soft-linking of yarn shell script

### ISSUE THREAD

**Issue by jambonrose** [yarnpkg/yarn#1941]
I am running macOS 10.11.6, Node 6.9, and yarn 1.17.3.

[I've just created a Portfile for yarn to be installed in Macports.](https://github.com/macports/macports-ports/pull/48)

In doing so, I changed the code in `bin/yarn` from the line of code in 1 into the code in item 2.

1. `basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")`
2. `basedir=$(dirname "$(readlink "$0" || echo "$(echo "$0" | sed -e 's,\\,/,g')")")`

The addition of the `readlink` command allows for the `bin/yarn` script to be soft linked to `/opt/local/bin/yarn` for installation, allowing for yarn to be easily uninstalled by the user if desired. 

I believe the code on line 2 allows the currently script to continue working in its original context, and that the new context should work in other shells on other systems, but I would like some feedback before I open a PR with this change.

Are people interested in this change?

**Comment by Kineolyan** [comment]
Agreeing with @jambonrose. This also happens if you install yarn in /opt - as suggested by [doc for manual installation](https://yarnpkg.com/en/docs/install#alternatives-tab), but instead of add the /opt folder to `$PATH`, you add a symlink in one of the existing bin folders - /usr/bin, /usr/local/bin, ...

Cheers
