### ISSUE TITLE
yarn install for latest version dependency need to be updated in yarn.lock file

### ISSUE THREAD

**Issue by ajithr** [yarnpkg/yarn#1978]
If any dependencies in package.json have latest version reference, then it needs to be updated in the yarn.lock file while yarn install.

Example:
```
dependency: {
      @angular/core: '*',
      typescript: '*',
      tslint: '^4.0'
}
```
Other than '*' version packages don't need to be get updated in yarn.lock file. For example tslint from above package dependency.
       
**Do you want to request a *feature* or report a *bug*?**

Yes

**What is the current behavior?**
Latest version packages not updated in yarn.lock file, so it always installed older version packages from lock file.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Set '*' version to a dependency package in package.json
2. Run yarn install.
3. Now the yarn.lock file have latest version package.
4. publish the '*' versioned package with another version.
5. Delete node_modules folder and run yarn install.
3. After install, yarn.lock file have older version of '*' packages.

**What is the expected behavior?**
yarn.lock file need to be update the latest version for '*' versioned dependencies. 

**Please mention your node.js, yarn and operating system version.**
node.js: 6.9.1
yarn: 0.17.8
OS: windows 10

**Comment by hpurmann** [comment]
Thank you for filing this issue, @ajithr. The behaviour you describe is intended in yarn.

The `yarn.lock` locks down the dependencies (and sub-dependencies) of your project to the _latest version the range allows_ at the time of first install. This is done to ensure a stable build with unchanged dependencies regardless of time of execution. It's a really important feature when developing an application (as opposed to developing a library) because you don't want your build to break as a result of updated upstream dependencies.

I think what you are searching for is [yarn upgrade](https://yarnpkg.com/en/docs/cli/upgrade).
