### ISSUE TITLE
Basic yarn install

### ISSUE THREAD

**Issue by iamnathanwindsor** [yarnpkg/yarn#2093]
I'm working to install yarn in my $PATH on my mac OS X 10.11.5, but perhaps I didn't do it right?

I did this:
$ touch ~/.bash_profile; open ~/.bash_profile

set my variables here to:
# Setting PATH for Yarn
export PATH="$PATH:`yarn global bin`"

$ source ~/.bash_profile

Here's my error message:

$ yarn version
yarn version v0.17.9
error Couldn't find a package.json file in "/Users/nathan"
info Visit https://yarnpkg.com/en/docs/cli/version for documentation about this command.

**Comment by davewasmer** [comment]
@iamnathanwindsor looks like it worked actually:

```
$ yarn version
yarn version v0.17.9
...
```

Means that yarn was found. The issue here is that `yarn version` is different than `yarn --version`. The former is a command used to bump the version of the package you are currently in (a la `npm version`), and the latter prints the version of yarn you are using.

So you are seeing the error there because yarn thinks you are trying to bump the version of a package stored in `/Users/nathan`, but there's no `package.json` file in that directory.

**Comment by iamnathanwindsor** [comment]
Thank you @davewasmer! I look forward to using yarn. Please let me know if I can ever help y'all out.

**Comment by Daniel15** [comment]
I'm going to close this issue, since it looks like you figured things out. As @davewasmer mentioned, `yarn version` is actually a Yarn command to change the version number of a package. You can use it when releasing a new version of a package. On the other hand, `yarn --version` is a command to output the version number of Yarn that is installed.

Thank you for trying Yarn! 😃
