### ISSUE TITLE
Fails if optional dep not found, even with --ignore-optional

### ISSUE THREAD

**Issue by mmmdreg** [yarnpkg/yarn#2149]
**Do you want to request a *feature* or report a *bug*?** 
bug 

**What is the current behavior?**
When specifying --ignore-optional, yarn still tries to look at them, failing if not found in the repo. Npm does not fail. 

For added context, I work in a corporate with internal proxies for public repositories implemented using artifactory, which doesn't support typescript typings. Since these are optional and not critical deps, I would want yarn install to succeed (like npm, perhaps with warnings), otherwise it is unusable. 

**If the current behavior is a bug, please provide the steps to reproduce.**

yarn add apollo-client --ignore-optional
Error Couldn't find package "@types/..."

**What is the expected behavior?**
It should actually ignore the optional deps and install successfully. 

**Please mention your node.js, yarn and operating system version.**
Yarn 0.18.0
Node 7.1.0
OS windows 7 (same behavior on Linux)

**Comment by cnadeau** [comment]
Same behavior on Mac OSX El Captain

file: ../shared/my-module

but __../shared__ will only be available once the app is loaded, so I need to ignore the optional the first time _yarn_ is called

**Comment by cnadeau** [comment]
I did a bit of investigation, and the problem comes from the fact the request's optional parameter is ignored in the file-resolver

https://github.com/yarnpkg/yarn/blob/master/src/resolvers/exotics/file-resolver.js#L32

and from my investigation, looks like we can't just ignore it and return null because a manifest is expected even for optional depedencies.
