### ISSUE TITLE
wish: `yarn run` should include the commands that project commands would run

### ISSUE THREAD

**Issue by markstos** [yarnpkg/yarn#2194]
**Do you want to request a *feature* or report a *bug*?**

feature.

**What is the current behavior?**

```
$ yarn run
yarn run v0.17.8
[...]
info Project commands
   - start
   - test
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Desired behavior is show the commands that the project commands would run. `npm run` does this and it's helpful:

```
$ yarn run
yarn run v0.17.8
error No command specified.
[...]
info Project commands
   - start
        node server.js 
   - test
       gulp test-backend --no-bail
```

**Please mention your node.js, yarn and operating system version.**

N/A.

**Comment by vvscode** [comment]
I'll check it

**Comment by sotojuan** [comment]
@torifat I'm working on this. I got the commands and scripts in the `pkgCommands` array in `src/cli/commands/run.js` but having trouble printing them in a format like above because it's using `reporters.list` and I'm not sure how that works or how to change it.

For reference, this is what the `pkgCommands` object looks like for a project I test it on:

```javascript
[ { start: 'node server.js' },
  { build: 'webpack --config webpack/prod.js --progress --colors -p' },
  { test: 'standard | snazzy --verbose && NODE_ENV=test ava --verbose' },
  { deploy: 'npm run build && surge -p build -d saga-login-flow.surge.sh' } ]
```

/cc @Daniel15

**Comment by torifat** [comment]
@sotojuan I don't think it has to be exactly like the example, as long as we can keep it clean & readable.

**Comment by sotojuan** [comment]
Yeah, added and removed my comment, sorry ^^
