### ISSUE TITLE
Fails to install flat (npm package)

### ISSUE THREAD

**Issue by palmerj3** [yarnpkg/yarn#2277]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

If you attempt to install the NPM package [flat](https://www.npmjs.com/package/flat) then it fails with the error:

```
$ yarn add flat
yarn add v0.18.0
error Missing list of packages to add to your project.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a new project
2. yarn init (follow steps)
3. yarn add flat

**What is the expected behavior?**

To install the [flat](https://www.npmjs.com/package/flat) package.

**Please mention your node.js, yarn and operating system version.**

Node: 6.9.1
Yarn: 0.18.0
OS X: 10.12.1

**Comment by polizz** [comment]
The issue is in the commander lib. Any defined option, in this case, the **--flat** option, is partially identified and processed when there are no flag dashes, **--**, accompanying the flag. **--json** and the other flags behave the same way.

There is still a month-old open issue on this: (https://github.com/tj/commander.js/issues/471)

**Comment by wyze** [comment]
Duplicate #2112.
