### ISSUE TITLE
Automate release of Chocolatey package

### ISSUE THREAD

**Issue by pascalberger** [yarnpkg/yarn#2288]
0.18.1 is marked as latest release but not available on [Chocolatey](https://chocolatey.org/packages/yarn). It would be nice to have the Chocolatey releases in sync with the GitHub releases (push Chocolatey packages as part of the build script).

**Comment by Daniel15** [comment]
Thanks for the reminder, I forgot to build the Chocolatey package. I'll do that now.

>  It would be nice to have the Chocolatey releases in sync with the GitHub releases (push Chocolatey packages as part of the build script).

Yes! I've been meaning to do this. Originally I was thinking that #2045 needs to be fixed first, but instead of doing that we could probably run a PowerShell script to build + publish the Chocolatey package as part of the deployment process. This is the script used to push releases to GitHub: https://github.com/yarnpkg/releases/blob/gh-pages/nightly/api/release_appveyor.php

I tried building the Chocolatey package on Linux and it currently fails due to bugs in Chocolatey, so we'd definitely need to do that on a Windows machine. Perhaps we could build the package on AppVeyor, it'd need to be build *after* the installer is signed though, so it gets the right SHA256 hash.

**Comment by Daniel15** [comment]
Pushed 0.18.1 to Chocolatey. However, I think the other half of this task (automating the Chocolatey package build) is useful so I'll keep the task around.

**Comment by Daniel15** [comment]
I've correctly configured this to be automated. Similar to how we handle the Debian/Ubuntu releases, I have a Jenkins build job that watches `https://yarnpkg.com/latest-version` and updates the package once the version number changes. Hopefully it works - I can't exactly test it right now as the current version is already up-to-date. I'll find out if it actually works once we release a new stable version 😛
