### ISSUE TITLE
$npm_execpath value is incorrect in the .js bundle release

### ISSUE THREAD

**Issue by Kovensky** [yarnpkg/yarn#2345]
**Do you want to request a *feature* or report a *bug*?**

Bug report

**What is the current behavior?**

The `$npm_execpath` environment variable provided to scripts points to `/bin/yarn.js`.

**If the current behavior is a bug, please provide the steps to reproduce.**

With a `package.json` like:

```json
{
  "scripts": {
    "test": "echo $npm_execpath"
  }
}
```

Run `node ./yarn-0.18.1.js test`.

**What is the expected behavior?**

It should point to the bundle's own path.

The solution is to add `node: { __filename: false }` to the webpack config, to prevent it from mocking the `__filename`. Note that this will make any `__filename` anywhere return the same path, which is why it is mocked by default even on `target: node`.

Alternatively`node: false`, to disable emulation of all node features.

**Comment by kouhin** [comment]
Yes, some problem.

Since docker node is using legacy bundled version, `yarn.js` is moved to `/usr/local/bin/yarn`. 
And yarn creates `npm_execpath` by the following code: 

https://github.com/yarnpkg/yarn/blob/51b4d0dcf289ed89b4e774b1c3efad1f04d688e6/src/util/execute-lifecycle-script.js#L33

```
env.npm_execpath = path.join(__dirname, '..', '..', 'bin', 'yarn.js');
```
This code breaks bundled version.

When `yarn` is under `/usr/local/bin`, `npm_execpath` will be `/bin/yarn.js` which does not exist.
