### ISSUE TITLE
`yarn add dep@tag` incorrectly records version in package.json

### ISSUE THREAD

**Issue by billyjanitsch** [yarnpkg/yarn#2582]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

`yarn add dep@tag` adds the version string "tag" to package.json instead of recording the actually installed version as `npm install` does.

For example, `yarn add webpack@beta` adds `"webpack": "beta"` to the package.json dependencies.

This was brought up in #1306 and partially fixed in #2471, but only for the "latest" tag. Now there's an awkward inconsistency between `yarn add webpack@latest` and `yarn add webpack@beta`.

**What is the expected behavior?**

Parity with `npm install`. For example, `npm install -S webpack@beta` adds `"webpack": "^2.2.0"` to the package.json dependencies.

**Please mention your node.js, yarn and operating system version.**

Node 7.4.0, yarn 0.19.1, macOS 10.12.2.

**Comment by bestander** [comment]
Good point, send a PR 👍

**Comment by kwelch** [comment]
I am also seeing, this error. I will see if I can take some time to put in PR.

**Comment by DavidFluck** [comment]
Are version ranges supposed to be left intact in `package.json` or should the version number be replaced with the installed version? That is to say, if I were to run something like `yarn add 'webpack@>1.5.0 <2.0.0 --save'`, should the corresponding entry in `package.json` read `"webpack": ">1.5.0 <2.0.0"` or something like `"webpack": "^1.7.0"`? I ask because `npm` seems to replace a given range with the installed version, whereas  `yarn` does not. Not only would this be required for total parity, but I think it would make the code easier to write as well: instead of looking for strings specifically like `latest` or `beta`, you just replace the saved version with the package version. What do people think?

**Comment by bestander** [comment]
duplicate https://github.com/yarnpkg/yarn/issues/2466
