### ISSUE TITLE
Consider using `lodash`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [yarnpkg/yarn#2588]
**Do you want to request a *feature* or report a *bug*?**
I don't think it counts as either.  Reworking internals?

**What is the current behavior?**
`lodash` is not used.  It's in the dependency tree, so it's already there, it's just not being used.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
`lodash` is used over specific libraries (`camelcase`, `defaults`, `object-path`).
**Please mention your node.js, yarn and operating system version.**

**Comment by xtuc** [comment]
Wouldn't you rather remove it from the dependencies?

**Comment by wtgtybhertgeghgtwtg** [comment]
Sorry, I don't think I said that very well.
`yarn` depends on `inquirer`, which depends on `lodash`.  So `lodash` is in the dependency tree, even though `yarn` does not have it as a dependency.
I propose adding `lodash` as a dependency of `yarn`, since it's already there, and using it instead of specific libraries `yarn` uses (`camelcase`, `defaults`, `object-path`).

**Comment by bestander** [comment]
We had lodash as direct dependency in the beginning but ended up replacing it with those few smaller libs.
I don't think we want to bring lodash as a dependency, considering its size, just because some sub dependencies use it.
After all inquierer may decide to depend on a subset of lodash then Yarn would have to replace it again.

**Comment by wtgtybhertgeghgtwtg** [comment]
Admittedly, it's not the best argument to use `lodash`.
