### ISSUE TITLE
Used npm to install yarn globally. when I run yarn in my project directory, i get error

### ISSUE THREAD

**Issue by francisngo** [yarnpkg/yarn#2612]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When running yarn in project directory I get unexpected error: 
`EACCES: permission denied, mkdir '/Users/$USER/Library/Caches/Yarn/npm-babel-preset-es2015-6.22.0-af5a98ecb35eb8af764ad8a5a05eb36dc4386835`

and then this error right under: 
```
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/Users/SICNARF/Library/Caches/Yarn/.roadrunner.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.writeFileSync (fs.js:1223:33)
    at /usr/local/lib/node_modules/yarn/node_modules/roadrunner/index.js:25:6
    at /usr/local/lib/node_modules/yarn/node_modules/roadrunner/index.js:12:12
    at process.sigint (/usr/local/lib/node_modules/yarn/node_modules/roadrunner/index.js:46:5)
    at emitNone (events.js:91:20)
    at process.emit (events.js:185:7)
    at processEmit [as emit] (/usr/local/lib/node_modules/yarn/node_modules/signal-exit/index.js:155:32)
    at Signal.wrap.onsignal (internal/process.js:200:44)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
$sudo npm install -g yarn
$sudo yarn --version
>0.19.1
```
...cd into directory
`$yarn`
...get unexpected error and EACCES permission error listed above

**What is the expected behavior?**
Must run 'sudo yarn --version' to get version 'yarn --version' does not work. 

**Please mention your node.js, yarn and operating system version.**

yarn v0.19.1
node v7.4.0
OSX Sierra v10.12.3

**Comment by Nikki1993** [comment]
You should **not** use sudo when installing NPM & NPM packages. EACCES is, as the description says, a denied action due to permissions. I'd highly advised to nuke entire global node_modules (since it has sudo permissions instead of regular user) & install a package without using sudo. More about it here https://docs.npmjs.com/getting-started/fixing-npm-permissions 

Also, it is recommended to install yarn via brew package manager instead of npm dependency. I highly recommend check out the docs https://yarnpkg.com/docs/install

P.S. **Seriously, do NOT use sudo with NPM!**

**Comment by francisngo** [comment]
Thanks, I nuked node and npm from my computer and reinstalled them. I also changed the owner for usr/local and now can `npm install` without `sudo`.

**Comment by Daniel15** [comment]
I'm going to close this issue since you fixed it, but please feel free to reopen it if you encounter the same problem again 😃
