### ISSUE TITLE
command line flags are parsed incorrectly, leading to confusing error/hint

### ISSUE THREAD

**Issue by FlorianDold** [yarnpkg/yarn#2643]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
```
$ yarn --verbose add foo
error install has been replaced with add to add new dependencies. Run "yarn add add foo" instead.
```
**If the current behavior is a bug, please provide the steps to reproduce.**

Invoke yarn with `--verbose` (or in fact any other flag) before `add <pkg>`. 

**What is the expected behavior?**

The --verbose should be parsed as a flag.  Instead the parser gets confused, and the hint that shown is wrong and confusing.

**Please mention your node.js, yarn and operating system version.**

node: v7.4.0
yarn: 19.1
os: arch linux

**Comment by markstos** [comment]
@FlorianDold The command line flags appear parsed correctly according to documentation. 

Running `yarn --help`, the "Usage" is clearly `yarn [command] [flags]`.

Further, the [docs for yarn add](https://yarnpkg.com/docs/cli/add) do not provide any examples of putting the flags before the sub-command. 

Also, the [CLI introduction](https://yarnpkg.com/docs/cli) does not mention global flags (except for `--mutex), but it *does* document that "install" is the default command if no other sub-command is provided. 

So the behavior you see is consistent with the documentation.  Since no sub-command followed `yarn`, the implied command you ran is: `yarn install --verbose add foo`.

I recommend this bug report be closed.

**Comment by FlorianDold** [comment]
@markstos I agree that the current behavior is consistent with the docs, but it is not consistent with user expectations.

Tools like git or npm would, in this case, either throw an error or pass the flag through to the command.

With NPM, `npm --verbose install <pkg>` works as expected (running install with verbose output), and `npm --help` also only specifies `npm <command>`.

Passing flags through to the command would still be consistent with the current documentation, since it only specifies "Running yarn with no command will run yarn install".  But in the example above, yarn is in fact invoked with a command ("add"), so the fallback to "install" should not apply.

**Comment by markstos** [comment]
@FlorianDold If `yarn` is working as documented but you would rather it works more like `npm` in this regard, then this is a *feature request*, not a *bug*.

**Comment by FlorianDold** [comment]
@markstos It's debatable in this case, since the behavior is under-specified in the documentation.  In `yarn --verbose add <pkg>`, there _is_ a command given.  But by some undocumented feature, a flag in front of it prevents it from being recognized as the command.

When `yarn --help` specifies `yarn [command] [flags]`, then the above invocation should either be an error or "add" should be recognized as the command.

Thus I'm not sure anymore if the current behavior is actually properly explained by the docs.

**Comment by markstos** [comment]
> When yarn --help specifies yarn [command] [flags], then the above invocation should either be an error or "add" should be recognized as the command.

I agree that's reasonable and would be a better user experience.

**Comment by paul-soporan** [comment]
Closing as fixed in the v2, arguments can now be specified before the command.

https://yarnpkg.com/getting-started/migration
