### ISSUE TITLE
Add compressing feature for offline git dependencies.

### ISSUE THREAD

**Issue by yunxing** [yarnpkg/yarn#2671]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Git dependencies, when asked to be stored offline, are only stored as a uncompressed tar file. This creates unnecessary disk usage. 

**What is the expected behavior?**
Ideally we should add an option to allow compressing it to reduce disk usage.

cc @bestander

**Comment by bestander** [comment]
I think it should be the default behavior

**Comment by yunxing** [comment]
@bestander ok, that should also work.

**Comment by Daniel15** [comment]
For what it's worth, uncompressed tar files have some advantages:
 - If you're storing the dependencies in a Git or Mercurial repo, uncompressed tar files work better as it can actually diff the files between two versions rather than storing undiffable compressed blobs. Compressed files and Git don't get along very well
 - Faster installation time as it does not need to be decompressed

For example, see:
https://github.com/JamieMason/shrinkpack/issues/40
https://github.com/JamieMason/shrinkpack/commit/7b2f341408be4f0415714ec57534debfdaaa3fbf#comments

**Comment by bestander** [comment]
1. We don't diff files in offline mirror because file name contains version

2. In this case we want to prioritise size over extraction speed so that we
can store them in source control.

**Comment by szarouski** [comment]
Here is how I understand what Daniel says:
We have babel as a dependency which is setup as a monorepo with fixed mode for versions update - so every time babel need to release a change in one of its dependencies, all babel packages will get their version bumped. When yarn.lock is regenerated & yarn will update offline cache - all babel packages will be tracked as new by Git because they can't be diffed. Similar situation will happen when package authors will release a new minor version of package which fixes typo in package.json description or something similar. If offline packages would be in .tar format, Git would detect that package is the same and track it as moved.

If that is correct, I would like to have an option to us .tar file for offline cache instead of .tar.tgz so that repo takes less space.

Maybe shrinkpack can be used together with yarn to make that happen?

**Comment by szarouski** [comment]
Sorry, just noticed there is an open discussion already: https://github.com/yarnpkg/yarn/issues/541

**Comment by bestander** [comment]
PR to implement this feature is very much welcome.
Should be a few lines actually

**Comment by JamieMason** [comment]
Incase it is useful to anyone, how this is done in shrinkpack is [src/lib/copy-file.js:24-30](https://github.com/JamieMason/shrinkpack/blob/master/src/lib/copy-file.js#L24-L30).

**Comment by merceyz** [comment]
Closing as fixed in v2 where all dependencies stored in the cache are compressed zip files

https://yarnpkg.com/getting-started/migration
