### ISSUE TITLE
Bad release

### ISSUE THREAD

**Issue by suchitagarwal** [yarnpkg/yarn#2771]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

``npm install -g yarn``

 installs 0.18.2

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by emkrcko** [comment]
This broke our CI as we install yarn via npm

**Comment by Daniel15** [comment]
Looks like this only affects the npm package. All other installation methods look fine, as does our endpoint for getting the latest version number (https://yarnpkg.com/latest-version)

**Comment by SamVerschueren** [comment]
I came across this issue because I wanted to upgrade `yarn` to the latest version so I ran `npm install -g yarn` but it kept showing version `0.18.2`.

![screen shot 2017-02-24 at 09 38 03](https://cloud.githubusercontent.com/assets/1913805/23296380/facc2c82-fa74-11e6-858a-33d58efb22ef.png)

So apparently only 15 hours ago a new release was cut. Why is it still stuck on `0.18.2`? Might be missing something obvious here...

**Comment by Daniel15** [comment]
@bestander is going to fix this.

**Comment by bestander** [comment]
fixed

**Comment by SamVerschueren** [comment]
Nice, thanks @bestander!
