### ISSUE TITLE
git archive capability works?

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#2831]
**Do you want to request a *feature* or report a *bug*?**

*bug*?

**What is the current behavior?**

Git archive capability checks that URL matches `USER@HOSTNAME:PATHNAME`
https://github.com/yarnpkg/yarn/blob/master/src/util/git.js#L57

Is it something like `ssh://git@bitbucket.org/bestander/test-repo.git:/`?
The problem is that `:PATHNAME` does not work with git-archive feature. 
Even if the regex matches it will fail git-archive command check and the git.js will fallback to cloning.

Removing :PATHNAME from the regex could be a solution but I am not sure doing only this fixes the issue because `supportsArchiveCache` stores archive capability per hostname but archive capability also depends on access rights and protocol.

This feature needs a fix + tests.

**Please mention your node.js, yarn and operating system version.**

Yarn 0.22.0

**Comment by BYK** [comment]
@bestander I think this is now fixed via this method: https://github.com/yarnpkg/yarn/blob/ba8d0dbd9887bf50c976a47c40e04bf74c478c2a/src/util/git.js#L128-L146

Closing the issue but LMK if you think this still needs more work or attention.

**Comment by Et7f3** [comment]
[cross post of a comment on a commit (might not have visibility and is code from 9 years ago)](https://github.com/yarnpkg/yarn/commit/68a39e94acc268a88ac504754859a56630afb4b0#r136356923)
Sorry for necro-mancing but can't find info on google/git manual. If I understand this functionality avoid repacking each time ? but how it know which tarball to give back because it use `Date.now()`. I would have expected a hash or something more stable like tag/branch.
https://github.com/yarnpkg/yarn/blob/158d96dce95313d9a00218302631cd263877d164/src/util/git.js#L152
Do you know a service that support it ?

also gitlab.com ? out private gitlab instance (which might have same default than gitlab.com) doesn't support it.
I haven't tried gitolite but does it support this feature ?
