### ISSUE TITLE
passphrase is not working with ssh

### ISSUE THREAD

**Issue by SunnyTam** [yarnpkg/yarn#2882]
**What is the current behavior?**
I have try to install dependency with and without ssh passphrase. I sounds like yarn cannot prompt to let me input passphrase. For my workaround is to make an ssh key that without passphrase. 

**If the current behavior is a bug, please provide the steps to reproduce.**
use ssh key with passphrase

**What is the expected behavior?**
ask for enter passphrase instead of being stun.

**Please mention your node.js, yarn and operating system version.**
yarn verison: 0.23.0-20170308.0112
node version: v6.9.4

**Comment by dimified** [comment]
I am also experiencing issues with my passphrase. When adding yarn packages I am asked for the passphrase. But the correct passphrase is not working as a result fetching packages is not possible. The only difference is that I am asked for the pass. 

**Please mention your node.js, yarn and operating system version.**
yarn verison: 0.22.0
node version: v6.9.4

**Comment by MichaelIT** [comment]
+1

**Comment by BYK** [comment]
We have made Yarn invoke Git, SSH and Plink in batch mode to avoid these issues. Since Yarn works concurrently, it is not easily possible to pause certain operations and ask for user input. Also, one if the design goals is to make it work without user interaction as much as possible for operations like install. 

For the reasons above, we are not going to work on this feature, thus closing the ticket. Still, feel free to continue the discussion if you think this is very important or if you can find better ways to address this issue.

**Comment by JP-GNL** [comment]
This may help: https://github.com/yarnpkg/yarn/issues/2702#issuecomment-304100127

**Comment by danlugo92** [comment]
This is important for safety.
