### ISSUE TITLE
apt-get update freezing forever

### ISSUE THREAD

**Issue by xanview** [yarnpkg/yarn#3052]
apt-get update is sometimes freezing forever when I have 'deb https://dl.yarnpkg.com/debian/ stable main' in my sources.list :( - any solution?

**Comment by Daniel15** [comment]
Hmm... Can you please try `wget https://dl.yarnpkg.com/debian/dists/stable/main/binary-amd64/Packages` on the same machine and see if it works? Perhaps there's some sort of connectivity issue. Also, test it with `http://` rather than `https://` and see if that helps.

Which Linux distribution are you using?

**Comment by xanview** [comment]
It happens on 4 different machines in different places and happens intermittently. All the machines are running Ubuntu 16.04 - I will try to use http instead of https and revert back, thank you.

**Comment by xanview** [comment]
So far no issues when using http instead of https, strange! - Thank you for the tip.
