### ISSUE TITLE
yarn upgrade should not install non-listed packages

### ISSUE THREAD

**Issue by dmitriid** [yarnpkg/yarn#3176]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I have `jest` included in my `package.json` devDependencies. I tried to upgrade it, but mistyped it: `yarn upgrade hest`. Sure enough, yarn installed a package called `hest` and added it to `dependencies`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `yarn upgrade <a name that doesn't exist in your package.json dependencies>`

**What is the expected behavior?**

Yarn should upgrade the packages it can upgrade and then display a warning saying "Could not upgrade the following packages becuase they are not listed as project dependencies: <list of packages>"

**Please mention your node.js, yarn and operating system version.**

```
> node -v
v6.9.1

> yarn --version
0.21.3

> system_profiler SPSoftwareDataType
macOS 10.12.4 (16E195)
```

**Comment by ianstormtaylor** [comment]
+1

It's really easy to accidentally misspell package names and have random other packages installed in their place. If you're using `upgrade` it shouldn't ever be as a surrogate for `install`.

**Comment by rally25rs** [comment]
In the code `upgrade` chains to `add` which in turn chains to `install` so it'll take your new package names and "add" them. I do think that's probably an unintended side-effect of the way the code is reused.

**Comment by atorenherrinton** [comment]
<img width="569" alt="Screen Shot 2021-08-17 at 11 01 08 AM" src="https://user-images.githubusercontent.com/25964143/129777316-136e92b4-7d91-4c89-a2bd-41be3380113d.png">

When I tried to reproduce the bug using [yarn version 1.22.11] it goes the install process but does not add it to [node_modules] or [package.json]

I would like to make an attempt at fixing this, so that it says "Could not upgrade the <package> because it is not listed as a project dependency".

**Comment by dmitriid** [comment]
@rally25rs It looks like this bug was fixed at one point. I can't reproduce it on `1.22` Thank you for trying to reproduce and fix it! 🙏 

I'll close the bug report so that it doesn't take up space and confuse people.
