### ISSUE TITLE
yarn upgrade-interactive should show a difference between major, minor and patch versions

### ISSUE THREAD

**Issue by Haroenv** [yarnpkg/yarn#3192]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

```sh
$ yarn upgrade-interactive
yarn upgrade-interactive v0.21.3
? Choose which packages to update. (Press <space> to select, <a> to toggle all, <i> to inverse selection)
 devDependencies
❯◯ babel-preset-env  1.3.3  ❯  1.4.0  https://babeljs.io/
```

**What is the expected behavior?**

To clearly show if a version is major, minor or patch. I've before accidentally updated webpack 1 to 2 for example, which was more to deal with than I had time for at the time

**Comment by torifat** [comment]
It already color codes the difference. And, IMO saying `major, minor or patch` is misleading because not everything is using semver.

<img width="444" alt="screen shot 2017-04-20 at 12 58 04 am" src="https://cloud.githubusercontent.com/assets/208544/25186763/78e4a972-2564-11e7-8a70-47e6f1a6bd72.png">

**Comment by Haroenv** [comment]
That is a good point, my terminal must have been set up a bit bad, because I couldn't tell the difference between white and green immediately. 

I understand that not everyone uses the same versioning way, so making it more prominent is a bit impossible. Thanks
