### ISSUE TITLE
APRIL 28 ISSUES TRIAGE SESSION

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#3258]
We'll use this task to coordinate triage session this Friday (28.04.2017).

15:30 BST - 17:30 BST
07:30 PT - 09:30 PT
10:30 EDT - 12:30 EDT

We need to add some order to the issues and are going to do our first group triage session.

Goals:
- Reduce the number of duplicated issues by grouping them by category first
- Close non actionable issues
- Prioritize important issues over the rest

What we are planning to do:
- categorize by issue type (bug, discussion)
- categorize bugs by phase (configuration, resolution, fetching, linking, scripts)
- label high priority issues
- label issues good for beginners
- close issues with no steps to reproduce them. Too many issues, too little time developers can spend on each, with no repro steps the issue will hang there for a long time

Below I'll post a few templates that we can use to keep the tone positive.

We can use this issue for coordination, I'll be moderating it to remove outdated comments.
Also we can coordinate in the chat https://discordapp.com/invite/yarnpkg (does not require registration)

**Comment by arcanis** [comment]
I was wondering something: a lot of the issue on this repo have no exact repro steps. It makes it very hard to debug the issue, and even harder to know if the issue is still there after a new release - of course in a wonderful world we would fix bugs reported on the bug tracker and close the related issues, but it's easy to miss a duplicate, to forget to close the issue, to wait for a confirmation from the affected users, etc.

Maybe it would be interesting to spend some time to make a small bot that would monitor github issues, extract tagged scripts, execute them in a [sandbox](https://linux.die.net/man/8/sandbox), then report the result and the exit code. This would have two extra benefits:

  - If a bot can reproduce the issue, so can we.
  - The bot could run each open issue at each release to close the old ones.
  - Triaging would be vastly facilitated (only features requests would have to be dealt with manually)

It would be similar to Travis CI, but not competing with it - I doubt we can/should ask users to write a testcase for each issue, but writing a repro script seems like the minimum.

**Comment by bestander** [comment]
That is a nice idea, @arcanis.
I think eventually we could get there but we'll need to put an effort into educating people to submit reproducible steps, also quite often issues are specific to a user's environment or private projects.

I would start with that - close all bug reports that don't have steps to reproduce it unless they are categorized as discussion.

**Comment by Daniel15** [comment]
> Maybe it would be interesting to spend some time to make a small bot that would monitor github issues, extract tagged scripts, execute them in a sandbox, then report the result and the exit code. 

That should be doable using Docker, it would require a bit of work to set up though. There's often environment-specific issues which probably can't be automatically replicated.

**Comment by rally25rs** [comment]
I don't have permission to close/edit issues, but where I have some input I'll try to leave a comment for a member to act accordingly.

See #3261 for example; I left a comment with a duplicate issue. 👍

**Comment by bestander** [comment]
I'll try to sort out permissions for participants.
for now just ping me, I'll react quickly

**Comment by bestander** [comment]
Ok, GitHub is not really great at permissions granularity and so this is what we can do this time.

Mention me in a comment and I'll do the trick, e.g.

@bestander label bug, bug-resolution
@bestander duplicate #xxxx

**Comment by bestander** [comment]
Good example how to use me-as-a-service https://github.com/yarnpkg/yarn/issues/3249#issuecomment-298015831

**Comment by bestander** [comment]
I claim issues #153 - #499

**Comment by arcanis** [comment]
I take #781 - #510

**Comment by bestander** [comment]
claiming #958 - #1060

**Comment by torifat** [comment]
claiming  #1073 - #1291

**Comment by bestander** [comment]
claiming #2987 - #3044

**Comment by arcanis** [comment]
#2986-#2804

**Comment by bestander** [comment]
I'll close the task as the triage session is finished.
But if anyone wants to continue, just keep tagging me to close or tag the issues.

Results:

1. Closed 88 issues
Open Issues before:
<img width="243" alt="screen shot 2017-04-28 at 3 53 48 pm" src="https://cloud.githubusercontent.com/assets/2121048/25544346/f47b1582-2c51-11e7-9786-a7dd1131d432.png">
Open Issues after:
<img width="238" alt="screen shot 2017-04-28 at 8 33 20 pm" src="https://cloud.githubusercontent.com/assets/2121048/25544349/f6123bc8-2c51-11e7-8f55-fa42e46393d6.png">

2. Triaged at least 112 open issues
<img width="1051" alt="screen shot 2017-04-28 at 8 34 45 pm" src="https://cloud.githubusercontent.com/assets/2121048/25544390/300a3c7c-2c52-11e7-8843-db7f34a951b0.png">

Great job everyone!
