### ISSUE TITLE
Workspaces issue progress

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#3294]
This issue will link all related discussions and RFC.

# Prior art (wrappers on top of yarn and npm):
- https://github.com/lerna/lerna
- https://github.com/whitecolor/yall and https://github.com/whitecolor/yalc
- https://github.com/sindresorhus/np (nice publish experience)

# RFC:
- [x] RFC for `link:` https://github.com/yarnpkg/rfcs/pull/34, will help when workspaces reference each other
- [x] RFC for workspaces install https://github.com/yarnpkg/rfcs/pull/60
- [x] RFC for workspaces add/remove/upgrade/* https://github.com/yarnpkg/rfcs/pull/61
- [x] RFC for workspaces linking https://github.com/yarnpkg/rfcs/pull/66
- [x] RFC for publishConfig https://github.com/yarnpkg/rfcs/pull/40
- [x] RFC for `knit` command https://github.com/yarnpkg/rfcs/pull/41 - simulates publishing a dep instead of just symlinking to a folder. That may be useful for Phase 3 described in https://github.com/yarnpkg/rfcs/pull/60
- [x] RFC for `project:` that is similar to `knit` idea https://github.com/yarnpkg/rfcs/pull/59
- [x] Full workspaces RFC aggregated https://github.com/yarnpkg/rfcs/pull/62
- [ ] RFC for publish and workspaces (phase 5) (looking for a champion)

# Pull requests:
- [x] `project:` proof of concept https://github.com/yarnpkg/yarn/pull/3281
- [x] workspaces install phase 1 https://github.com/yarnpkg/yarn/pull/3229
- [x] workspaces add/remove commands phase 2 https://github.com/yarnpkg/yarn/pull/3365
- [x] workspaces linking each other phase 3 & 4 https://github.com/yarnpkg/yarn/pull/3516
- [x] `link:` PR https://github.com/yarnpkg/yarn/pull/3359

# Issues/discussions:
- [ ] https://github.com/yarnpkg/yarn/issues/2989 - npm config base equivalent (needs clarification)
- [ ] https://github.com/yarnpkg/yarn/issues/2919, https://github.com/yarnpkg/yarn/issues/711, https://github.com/yarnpkg/yarn/issues/2863 - common node_modules, should be fixed with Phase 1

# Implementation phase:

- [x] (0.25) 1. Installing dependencies of all workspaces in the root node_modules
- [x] (0.26) 2. Commands to manage (add/remove/upgrade) dependencies in workspaces from the parent directory
- [x] (0.27) 3. Ability for workspaces to refer each other, e.g. jest-diff → jest-matcher-utils inside jest monorepo
- [x] (0.27) 4. package-hoister for workspaces, e.g. when dependencies conflict and can't be installed on root level
- [x] 5. Remove the experimental flag and turn on by default
- [ ] 6. Command to publish all workspaces in one go (looking for a champion)

**Comment by whitecolor** [comment]
I used scripts before, now I made simple wrapper for running yarn in monorepo https://github.com/whitecolor/yall, so far so good

**Comment by bestander** [comment]
Thanks for sharing, @whitecolor

**Comment by arcanis** [comment]
@bestander @cpojer I was thinking about the `workspaces` field. In the RFC we merged, we decided to use a globing to find all the package data (`packages/**/*`). I like the syntax, but won't this be an issue from a perf standpoint? It means that any cross-workspace command that we execute must stat a lot of sub-directories, then read all the package.json files in order to extract the names. That's unless we implement some kind of cache, of course.

**Comment by bestander** [comment]
It could add up to the start time as Yarn would need to find and read multiple package.json files.
But for most cases I don't think it will be a problem, if glob find becomes slow people could be motivated to use less aggressive glob rule.
Or we could come up with a cache.

**Comment by cpojer** [comment]
I think this should be fine from a perf-perspective for now. I expect the number of shared projects to be a small number (<100) in most cases. As @bestander said, large projects can also directly embed all the paths.

**Comment by richburdon** [comment]
> yarn help workspace

Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.

Returns 404

**Comment by bestander** [comment]
Workspaces is not going to be a CLI command but rather a configuration.
I am planning to post about it here https://yarnpkg.com/blog/ and have a [section](https://github.com/yarnpkg/website/issues/573) on different ways to link local projects here https://yarnpkg.com/en/docs/.

**Comment by richburdon** [comment]
Thanks very much @bestander 

Any idea of the timeline (for the docs, and the features to land?)

Very much looking forward to it.

**Comment by bestander** [comment]
I intend to finish the post by the end of the week.

**Comment by donaldpipowitch** [comment]
Should this issue track all workspace related bugs? If yes, I created an issue for a (small) bug: https://github.com/yarnpkg/yarn/issues/3972

**Comment by bestander** [comment]
Thanks, @donaldpipowitch.
I think this issue can be closed soon.
All workspaces-related bugs we tag with https://github.com/yarnpkg/yarn/labels/feature-workspaces.

BTW, thanks a lot for submitting issues with great repro steps, very much appreciated.

**Comment by donaldpipowitch** [comment]
Thank you for your work ❤

**Comment by elderfo** [comment]
Are workspaces still under the experimental flag in the RC?

**Comment by bestander** [comment]
Yes, still under experimental

**Comment by richburdon** [comment]
@bestander any update on your blog or instructions for using workspaces?

**Comment by bestander** [comment]
Sorry, I am waiting my colleagues to give feedback on the blogpost, a draft is here https://github.com/yarnpkg/website/pull/580

**Comment by richburdon** [comment]
O frabjous day! Fantastic.

Comments on blog:
1). might want to emphasize (and document) "private": true is required (I missed that on first try).
2). For neophytes like myself you might mention that you then call `yarn install` as normal (i.e., no need for a different command -- and that all other commands -- e.g., `yarn upgrade` should just work as expected).

And:
3). any support for `--nohoist` (grunt plugins don't work if they're hoisted -- grunt specifically only checks the local node_modules).

Thanks again. Awesome work, really appreciated.

**Comment by svenefftinge** [comment]
The decision in both lerna and yarn workspaces seem to be to hoist node packages to a common top level `node_modules` folder. While it works nicely, due to the default module resolution of traversing up parent folders, it also puts all modules into scope and leads to accidentally referencing code that you don't have a dependency on. 
One could instead change the name of the top level hoisted modules folder, so that it is not considered and have explicit symbolic links to it for all dependencies (and transitive ones).

**Comment by evocateur** [comment]
Why not just use pnpm, then?

More seriously, this is the sort of thing eslint-plugin-import is capable of validating. It only complicates lerna/yarn hoisting for a vanishingly small gain.

**Comment by akosyakov** [comment]
The correctness and tooling are bad, e.g. VS code proposes bogus imports which should not be accessible. You are right, it can be identified and fixed with eslint-plugin-import for pure js projects (e.g. if you use typescript you are out of luck) and fixed afterward. But such errors could be eliminated at all without additional tooling if node_modules are not hoisted to the root.

Having the nice support of hoisting in all kind of tools does not sound as a vanishingly small gain. The current hoisting strategy makes use of node module resolution without respecting it by putting not only shared dependencies in the root but all. If it does respect then all tools around will play nicely automatically.

**Comment by arcanis** [comment]
> VS code proposes bogus imports which should not be accessible

Seems like an issue with VS Code then? They probably should use the package.json as source of truth rather than the filesystem (or at least use it to validate things).

> But such errors could be eliminated at all without additional tooling if node_modules are not hoisted to the root.

Symlinks have their own set of issues, so that's unfortunately not really a solution here.

> The current hoisting strategy makes use of node module resolution without respecting it by putting not only shared dependencies in the root but all.

I'm not sure I understand, would you mind detailing what you mean by that?

**Comment by akosyakov** [comment]
> Seems like an issue with VS Code then? They probably should use the package.json as source of truth rather than the filesystem (or at least use it to validate things).

VS Code follows node module resolution that allows having parent packages to define shared dependencies, looking in package.json is not enough.

> Symlinks have their own set of issues, so that's unfortunately not really a solution here.

The suggestion of @svenefftinge does solve the issue using linking of dependencies, including transitive, from node_modules folder that does not belong to the root.

> I'm not sure I understand, would you mind detailing what you mean by that?

There are 2 packages: `Foo` and `Bar`. `Foo` depends on `X`, `Bar` depends on `X`, `Y`. Without hoisting one can introduce a parent package and declare `X` to avoid duplicating dependencies but keeping `Y` in `Bar`. With the current hoisting everything go to the root, making `Y` accessible to `Foo` and breaking developer tools. 

To fix it one should invent additional tools. An alternative is to fix hoisting by not putting non-shared dependencies in the root.

**Comment by arcanis** [comment]
I don't know. The use cases you're talking about looks to me things that should be handled by those tools rather than by the package managers. Don't forget that each rule we add to specify how we install dependencies also decreases our ability to improve it and try out new things in later releases.

We follow a semantic based on package.json, which I believe is common enough for it to be natively supported by most tools. If yours doesn't, then maybe it might be worth considering implementing it. Just my personal thoughts 😉

**Comment by akosyakov** [comment]
> I don't know. The use cases you're talking about looks to me things that should be handled by those tools rather than by the package managers. Don't forget that each rule we add to specify how we install dependencies also decreases our ability to improve it and try out new things in later releases. That's why how the hoister works is not specified: it gives us leverage to improve it without breaking contracts.

VS code and other tools follow node module resolution as [defined here](https://nodejs.org/api/modules.html#modules_all_together), looking at `package.json` is just one of steps. I don't see why they should be fixed.

> We follow a semantic based on package.json, which I believe is common enough for it to be natively supported by most tools. If yours doesn't, then maybe it might be worth considering implementing it. Just my personal thoughts 😉

Most of the tools follow [this semantic](https://nodejs.org/api/modules.html#modules_all_together) that does not allow to access dependencies of siblings packages. What is allowed by hoisting and why it does not play nicely.

**Comment by arcanis** [comment]
> Most of the tools follow this semantic that does not allow to access dependencies of siblings packages. What is allowed by hoisting and why it does not play nicely.

The Node resolution algorithm has no knowledge whatsoever of the `dependencies` field of the `package.json`. How it is interpreted is left to the package manager implementation, and the common interpretation is "I promise that if you specify a dependency, you will be able to access it". Once again, we make no guarantee that you *can't require a module that is not listed*, and this is by design.

Hence why I say: if you want your tools to have the same behavior as your package manager, then you have to read the `dependencies` field and interpret it the same way, you can't just rely on the `node_modules` directory being in a particular state. Otherwise, you will end up losing information (such as that package relationships).

**Comment by svenefftinge** [comment]
The `package.json` is a means for yarn or npm to produce the `node_modules` folder(s). All downstream tools, transpilers and loaders should rely on the same scoping rules, that is the [node_module resolution strategy](https://nodejs.org/api/modules.html#modules_all_together). In my projects I have typescript, vscode, webpack, node. They all use the same module resolution strategy and they all 'see' stuff that they should not, because the hoisting puts too much on their scope.

**Comment by Hypnosphi** [comment]
@svenefftinge How do you think, is it OK to import a second-level dependency directly in your code? Say you have a dependency to `react` in your `package.json`, and `react` depends on `fbjs`. So should your tools warn you if you do this?
```
import emptyFunction from 'fbjs/lib/emptyFunction';
```

**Comment by svenefftinge** [comment]
Re-exported transitive dependencies are what yarn and npm do by default, so I wouldn't argue that they should not be added. That said, with the design I proposed it would be possible to optionally only link the explicit dependencies.

**Comment by BYK** [comment]
>That said, with the design I proposed it would be possible to optionally only link the explicit dependencies.

Which adds another feature/option that we need to support with increased complexity, that's the point @arcanis is trying to make. It is the toolmakers' responsibility to protect against this one.

**Comment by donaldpipowitch** [comment]
Thank you every on for this great feature. I there an issue where I can track discussion/progress for "nested workspaces"? We used this previously with Lerna and it was a really nice experience. It looked similar to this:

```
packages/
  - buttons/
    - examples/
      - simple/
      - group/
  - forms/
    - examples/
      - simple/
      - complex/
      - validation/
...
```

So basically: publishable packages on the first layer and examples for every package at the second layer.

**Comment by rarkins** [comment]
If anyone is interested, I've added yarn workspaces support to [Renovate](https://github.com/singapore/renovate). It's an open source tool for keeping dependencies and lock files up-to-date which you can run self-hosted (installable via npm/yarn) or via the [GitHub App](https://github.com/apps/renovate) I run, if your repository is on GitHub.

**Comment by donaldpipowitch** [comment]
💡 This seems to work:

```json
{
    "private": true,
    "workspaces": [
        "packages/*",
        "packages/*/examples/*"
    ]
}
```

I guess "nested" workspace means multiple `package.json` files containing the `workspaces` property than? And _not_ having nested packages inside a workspace?

**Comment by bsvipas** [comment]
Hi guys, I have problem with Ember: https://github.com/yarnpkg/yarn/issues/4503 (same as https://github.com/yarnpkg/yarn/issues/4081)

**Comment by gustaff-weldon** [comment]
@bsvipas I think this is `ember-cli` and at least `ember-dependency-checker`-related. I suggest you bring the issue to ember-cli team attention.

**Comment by bestander** [comment]
Thanks everyone, I'll mark this issue as closed.
Please go ahead and raise issues for particular cases.
