### ISSUE TITLE
yarn upgrade should have a force flag

### ISSUE THREAD

**Issue by OmgImAlexis** [yarnpkg/yarn#3384]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
`yarn upgrade -f` ignores the `-f` flag

**What is the expected behavior?**
`yarn upgrade -f` should update the packages to the latest version ignoring the version range specified in the `package.json`.

**Comment by rally25rs** [comment]
As a workaround, you could use `yarn upgrade-interactive` which already ignores the version ranges.

**Comment by rally25rs** [comment]
I'm thinking about adding a `--latest` flag instead of `-f` to be clearer in it's meaning.
It would ignore the package.json defined semver range when a package name with no explicit version is passed.

Examples:

Given a package.json

```
"left-pad": "<=1.1.1"
```

And the `left-pad` package has these versions defined in the registry:

```
0.0.9
1.0.0
1.1.0
1.1.1
1.1.2
1.1.3
2.0.0
```

# Existing Behavior:

> yarn upgrade

Upgrades to 1.1.1 because it matches the package.json semver range (<=1.1.1)

> yarn upgrade left-pad

Upgrades to 2.0.0 because a package was passed with no explicit version

> yarn upgrade left-pad@~1.1.2

Upgrades to 1.1.3 because it is the latest match for the passed in semver range (~1.1.2)

# New Behavior:

> yarn upgrade --latest

Upgrades to 2.0.0 because it would ignore the package.json semver range and use the latest as defined in the registry

>yarn upgrade left-pad --latest

Upgrades to 2.0.0 because that is the latest. This is what the command already does, so it is equivalent to ignoring the flag.

> yarn upgrade left-pad@~1.1.2 --latest

Upgrades to 1.1.3 because it is the latest match for the passed in semver range (~1.1.2).  This is what the command already does, so it is equivalent to ignoring the flag. (i.e. explicit version range as a parameter takes precedence over the --latest flag)

-----

In addition, I'd like to add the opposite as well, some way to specify

> yarn upgrade left-pad --SOMETHING

and have it respect the package.json defined semver.

I do this all the time where I have dozens of deps but just want to upgrade to the latest on 1 or 2 libraries in a certain range. For example, for a while my project was stuck on PhantomJS v1, but could not use any v2 release. I'd liked to have done a `upgrade phantomjs` and have it get the latest v1 release as defined in package.json, without having to specify it on the command line `upgrade phantomjs@^1.0.0`

❓ The questions for discussion;

is this useful for others? and if so, what do we call `--SOMETHING`?

Perhaps something like `yarn upgrade left-pad --specified` or `--use-range` or `--not-latest` ... I dunno. Naming things is hard. 😖

**Comment by lopopolo** [comment]
bundler uses `--strict` for `--SOMETHING`

**Comment by OmgImAlexis** [comment]
Closed in https://github.com/yarnpkg/yarn/commit/b9fe983307ed426ee02624f219519c52b828d110

**Comment by OmgImAlexis** [comment]
@cpojer I don't know if it's a one off or if it's an actual bug but if you have a look at these commits you'll notice that I ended up with a weird `yarn.lock` because of `yarn upgrade --latest`.

I bumped the deps using `yarn upgrade --latest` in the template directory(https://github.com/ladjs/lad/commit/9ae4973453228637b9dba52d2f2c04b5b567dee7). I ran my tests and they all broke so I deleted `yarn.lock` and redid the yarn install and my tests now work again.

After this I noticed the `yarn.lock` (https://github.com/ladjs/lad/commit/3e88d77ac1fa4ff8c6598adb7cd00f5499efb7a0) changed quite a bit even though they should have been the same because of all the updates.
