### ISSUE TITLE
'yarn run' does not forward SIGTERM to process

### ISSUE THREAD

**Issue by frank-weindel** [yarnpkg/yarn#3424]
When running an application via 'yarn run' and a SIGTERM is signaled on it, yarn does not forward the SIGTERM to its child process(es). Hence an application's graceful shutdown code cannot run.

**Comment by bestander** [comment]
Send a PR :)

**Comment by GAumala** [comment]
Does yarn even handle SIGTERM? if so, where? It would have to keep a reference to every child process and call `child.kill()` on every one of them when SIGTERM is received.

**Comment by bestander** [comment]
@GAumala, would you send a PR?
The code is here https://github.com/yarnpkg/yarn/blob/master/src/util/execute-lifecycle-script.js

**Comment by GAumala** [comment]
I'd love to give it a shot, but I have some questions.

So `execCommand` is in `execute-lifecycle-script.js`, and then that function eventually calls `spawn()` in [`child.js`](https://github.com/yarnpkg/yarn/blob/master/src/util/child.js), which uses [Node's API for spawning child processes](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options). A reference to the child process is needed to call `kill()`, but `spawn()` only returns the process STDOUT. So there are two options:

- Make `spawn()` return a reference to the child process instead of STDOUT. The child process object is then passed to whatever signal handler yarn has.
- Make `spawn()` attach a SIGTERM listener to the global `process` object in which `child.kill()` is executed. If yarn already handles SIGTERM somewhere else, that behavior will be overriden.

Does yarn already have a SIGTERM handler? Which choice should I use?

**Comment by OmgImAlexis** [comment]
@frank-weindel can you update the OP as this is an issue with `yarn x` as well as `yarn run x`.

**Comment by bestander** [comment]
@GAumala, sorry for a delay.

I don't think yarn has a SIGTERM handler except for onDeath() callback when Yarn is executed in mutex mode https://github.com/yarnpkg/yarn/blob/master/src/cli/index.js#L232.

I think returning reference should be a cleaner solution rather than attaching to global process.
