### ISSUE TITLE
External dependencies will not install

### ISSUE THREAD

**Issue by donni106** [yarnpkg/yarn#3471]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I  installed yarn for the first time per brew on mac. When trying to yarn install a project (https://github.com/diegomura/react-pdf) it seems to freeze on installing external dependencies. Nothing is happening for a long time:
![bildschirmfoto 2017-05-22 um 14 21 26](https://cloud.githubusercontent.com/assets/1942953/26308591/2b2e0606-3efa-11e7-873c-380de32bbcee.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
1 clone https://github.com/diegomura/react-pdf
2 yarn

**What is the expected behavior?**
Finishing the installation.

**Please mention your node.js, yarn and operating system version.**
node.js 7.10.0
yarn 0.24.5
macOS Sierra 10.12.4

**Comment by rally25rs** [comment]
This is happening while running `react-pdf`'s `postinstall` script:

```
    "postinstall": "lerna bootstrap",
```

It looks like [Lerna](https://www.npmjs.com/package/lerna) sets some things up then uses `npm` to do additional installs.

> $ lerna bootstrap
>
> Bootstrap the packages in the current Lerna repo. Installs all of their dependencies and links any cross-dependencies.
>
> When run, this command will:
>
> 1. npm install all external dependencies of each package.
> 2. Symlink together all Lerna packages that are dependencies of each other.
> 3. npm prepublish all bootstrapped packages.

-----

You could try manually running `lerna bootstrap` in that directory and see if it has the same result. If so, then this is not related to Yarn.

Otherwise, there might be some compatibility issue here with Yarn running Lerna running NPM.

**Comment by donni106** [comment]
Thank you. I referenced this in the react-pdf repository issue for further action.
