### ISSUE TITLE
Missing package version glob@4.4.1 using yarn import

### ISSUE THREAD

**Issue by solocommand** [yarnpkg/yarn#3552]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When attempting to do a `yarn import` to generate a lockfile I'm unable to proceed because a package version throws a 404 when attempting to install it.

**If the current behavior is a bug, please provide the steps to reproduce.**

Included output from `yarn import` [yarn-error.log](https://github.com/yarnpkg/yarn/files/1042868/yarn-error.log.txt) and `npm ls` [npmls.txt](https://github.com/yarnpkg/yarn/files/1042882/npmls.txt)

**What is the expected behavior?**
Not sure why the file is throwing a 404, the [current version (7.1.2)](https://registry.yarnpkg.com/glob/-/glob-7.1.2.tgz) follows the same url structure as the [requested version (4.4.1)](https://registry.yarnpkg.com/glob/-/glob-4.4.1.tgz), and the [registry page](https://yarnpkg.com/en/package/glob) lists that version as being available.

It's a child dependency I don't have control over, so unfortunately I'm not sure what else I can do at this point.

**Please mention your node.js, yarn and operating system version.**
node `v6.3.1` yarn `v0.23.4` osx `10.12.2`

**Comment by solocommand** [comment]
@yarnpkg Any update on this?

**Comment by arcanis** [comment]
I don't think the problem comes from us. Look at this json object: https://registry.npmjs.org/glob. Despite the `4.4.1` release being available in the `time` field, it is not listed into the `versions` object. Actually, if you try to run `npm install glob@4.4.1`, npm will also tell you that this version cannot be found.

My best guess is that this version has been unpublished when it was still possible. That's not something we can fix, but you can probably just manually update the package.json file from this package in order to make Yarn think that it's another version.

Closing this issue since there's nothing actionnable on our side :)
