### ISSUE TITLE
Yarn installs wrong version

### ISSUE THREAD

**Issue by smelukov** [yarnpkg/yarn#3560]
**Do you want to request a *feature* or report a *bug*?**

Report a *bug*

**What is the current behavior?**

- put `"dependencies": { "css-tree": "^1.0.0-alpha17" }` in package.json
- exec `yarn`

`yarn.lock` is
```
css-tree@^1.0.0-alpha17:
  version "1.0.0-alpha9"
  resolved "https://registry.yarnpkg.com/css-tree/-/css-tree-1.0.0-alpha9.tgz#6ee3e397b569eef32419286c86e3e8b65fcaf3e3"
  dependencies:
    source-map "^0.5.3"
```

With NPM it's ok (NPM installs `1.0.0-alpha17`)

**What is the expected behavior?**

Resolve and install `1.0.0-alpha17` instead of `1.0.0-alpha9`

**Please mention your node.js, yarn and operating system version.**
MacOS 10.12.4
Node: v8.0.0
NPM: 5.0.1
But this case reproduces and on earlier version of node and NPM

**Comment by smelukov** [comment]
https://github.com/yarnpkg/yarn/blob/master/src/util/misc.js#L9
`sortAlpha('1.0.0-alpha7', '1.0.0-alpha9') // -2`
`sortAlpha('1.0.0-alpha17', '1.0.0-alpha9') // -8 (but +8 is expected)`

**Comment by kaylieEB** [comment]
I started looking into this, and it's that the `semver.maxSatisfying` doesn't return the expected max version. 
```
semver.maxSatisfying(['1.0.0-alpha', '1.0.0-alpha9', '1.0.0-alpha17'], '^1.0.0-alpha17')
'1.0.0-alpha9'
```
Technically css-tree has the incorrect semver, since pre-release tags should be dot-separated (http://semver.org/#spec-item-9)  such as `1.0.0-alpha.17`. Should we still try to patch this on our end?

fyi, this works
```
sem.maxSatisfying(['1.0.0-alpha', '1.0.0-alpha.9', '1.0.0-alpha.17'], '^1.0.0-alpha.17')
'1.0.0-alpha.17'
```

**Comment by rally25rs** [comment]
The `semver` that Yarn is calling here is just using https://github.com/npm/node-semver right?

If so, then I think it should be filed as an issue there... from a quick search I saw this: https://github.com/npm/node-semver/issues/30 where the 3rd-to-last comment points out this same issue.

**Comment by kaylieEB** [comment]
thanks! From that issue's last comment, it looks like `node-semver` won't be supporting invalid prerelease versions. I'll look into a patch for yarn. I guess another alternative is to file an issue with css-tree to fix their semver.

**Comment by smelukov** [comment]
Thanks. We'll try to fix csstree version

**Comment by smelukov** [comment]
```js
// for old installs:
semver.maxSatisfying(['1.0.0-alpha9', '1.0.0-alpha19', '1.0.0-alpha.20'], '^1.0.0-alpha19') // 1.0.0-alpha9
// for new installs
semver.maxSatisfying(['1.0.0-alpha9', '1.0.0-alpha19', '1.0.0-alpha.20'], '^1.0.0-alpha.20') // 1.0.0-alpha9

// if unpublish "wrong" versions
// for old installs:
semver.maxSatisfying(['1.0.0-alpha.20'], '^1.0.0-alpha19') // 1.0.0-alpha9
// for new installs:
semver.maxSatisfying(['1.0.0-alpha.20'], '^1.0.0-alpha.20') // 1.0.0-alpha.20 is OK
```

Any ideas? :)

**Comment by kaylieEB** [comment]
@rally25rs It used to be that npm [also used maxSatisying](https://github.com/npm/npm/blob/d46015256941ddfff1463338e3e2f8f77624a1ff/lib/utils/pick-manifest-from-registry-metadata.js#L18) but it seems like that file is no longer being referenced and they moved onto using their new library [pacote](https://www.npmjs.com/package/pacote), which gets the correctly requested package in the scenario above. We should probably update yarn to be able to handle cases like @smelukov's since it'd be a pain to republish all versions to correct semver and users would run into backwards compatibility issues.

**Comment by arcanis** [comment]
Good job tracing the issue! :) I'm not fond of the idea of adding a hack to the codebase to fix this, tho ... the alternative would be to fork `semver` to implement this behavior, but I'm not convinced either.

I would suggest `csstree` to fix the versioning - unless I'm mistaken, the worst side effect is that people currently tracking your alpha channel will stop getting update until they switch to the right pattern, which seems acceptable. If you wish to be more proactive, you can try publishing a release called `1.0.0-alphaX` that would contain `{"scripts" :"echo some message && exit 1"}`, where your message would be something inviting your users to fix their package.json files.

WDYT?

**Comment by rally25rs** [comment]
I thought the move to `pacote` was parts of the NPM5 work. @smelukov could you try your install with an NPM version over than 5? If they were using `maxSatisfying` in NPM <=4 then I would expect it to fail in the same way Yarn does.

**Comment by kaylieEB** [comment]
I've only tested it with npm5 since that was the original version in the issue, but I think they do other fixes and normalization to support dist-tags and things that yarn doesn't. @arcanis yeah i'm not 100% happy with the solution either since adding that normalization will slow things down for every package and main reason why I like using yarn is due to speed. On the other hand, semver can be forked to support limited in cases like

```
semver.maxSatisfying(['1.0.1-alpha.12'], '^1.0.0-alpha.10') // returns null
```
This is an existing limitation from [semver](https://github.com/npm/node-semver#prerelease-tags)

> For example, the range >1.2.3-alpha.3 would be allowed to match the version 1.2.3-alpha.7, but it would not be satisfied by 3.4.5-alpha.9, even though 3.4.5-alpha.9 is technically "greater than" 1.2.3-alpha.3 according to the SemVer sort rules. 

Maybe yarn just needs to be clear in docs that it only supports valid semver and latest tags as stated [here](https://github.com/yarnpkg/yarn/blob/dfb6a2b636860c516c02b1272e4c2629f87025d3/src/package-constraint-resolver.js#L8-L10)

**Comment by smelukov** [comment]
@rally25rs NPM4 installs `alpha19` instead of `alpha9` and it's ok

**Comment by bestander** [comment]
FYI we have special code for alpha versions here https://github.com/yarnpkg/yarn/blob/master/src/util/semver.js

**Comment by BYK** [comment]
I do not think this is something `yarn` should do. Ignoring these kinds of package errors would cause people to keep using them or not even become aware so closing the issue.

If anyone disagrees, I'm open for discussion.

**Comment by rally25rs** [comment]
I'm going to reopen this for a moment for more discussion...

I did some digging in NPM's source (what a mess) and found that what they do is, before falling-back to `semver.maxSatisfying` is to check the `latest` tag and see if it satisfies the requested tag.

In other words:

* if you have a repo that has versions: `[1.3.0, 1.2.0, 1.1.0]`
* And the registry has `dist-tags: { latest: '1.2.0'}`
* And your `package.json` requests `^1.0.0`.

Then Yarn will resolve this to 1.3.0 (the max satisfying version). NPM will first check if `latest (1.2.0)` satisfies `^1.0.0`, which it does, so it just uses that.

That seems to be what is happening with css-tree. Their `latest` tag is the newest `-alpha` release
```
"dist-tags":{"latest":"1.0.0-alpha25"}
```

So NPM just says `semver.satisfies('1.0.0-alpha25', '^1.0.0-alpha17')` which returns `true`, so it uses `latest/1.0.0-alpha25`

-----

@yarnpkg/core what do you guys think about adding this initial check for `latest` to satisfy the range to Yarn? That should fix a heap of this "installs wrong version" errors with pre-release versions.

**Comment by Daniel15** [comment]
Hmm, that's interesting behaviour. I wonder if that's documented anywhere, or if it's just an internal undocumented implementation detail of npm.

> I did some digging in NPM's source (what a mess)

This is one of the reasons Yarn was created. 😛
