### ISSUE TITLE
Error message could be better

### ISSUE THREAD

**Issue by sarupbanskota** [yarnpkg/yarn#3617]
**Do you want to request a *feature* or report a *bug*?**

bug / minor enhancement

**What is the current behavior?**

```
--- gig/babel ‹enforce_plugin_names* ?› » yarn --global add babel-register                       1 ↵
yarn install v0.24.5
error `install` has been replaced with `add` to add new dependencies. 
Run "yarn global add add babel-register" instead.
```

_Notice the double add_

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

would be nicer to have had something like:

```
Error: "--global" isn't supported. Run "yarn global add babel-register"
```

**Please mention your node.js, yarn and operating system version.**
node 8, yarn v0.24.5

**Comment by aij** [comment]
There are similarly confusing error messages when other flags are specified before the command as well. Rather than recognizing the command that is after the flags, yarn will infer the command as `install`, and then complain about the `install` being used inappropriately. This is particularly surprising on GNU/Linux where the position of flags tends to be quite flexible. (Some of) the BSDs tend to be more strict.

For example, `yarn test --pure-lockfile --frozen-lockfile` will run tests, whereas changing the argument order results in this misleading error:

```
$ yarn --pure-lockfile --frozen-lockfile test
yarn install v0.24.6
info No lockfile found.
error `install` has been replaced with `add` to add new dependencies. Run "yarn add test" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Would it be reasonable to allow options (or at least global options) to appear before the command? (I'm not familiar enough with older version of yarn to know whether that might produce surprising new interpretations of previously supported invocations or not.)
