### ISSUE TITLE
yarn install not prompting passphrase required

### ISSUE THREAD

**Issue by p-fernandez** [yarnpkg/yarn#3699]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Running `yarn install` gets stuck without prompting passphrase required when trying to install package in external repository, having the RSA key with passphrase.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. package.json with external private repository dependency:
```
{
  ...
  "dependencies": {
     ...     
     "externalPackage": "git+ssh://git@projecthost.com/whatever/externalPackage.git",
     ...
  },
  ...
}
```
2.RSA key with passphrase.
3. Execute `yarn install`.
4. Installation gets stuck waiting for user to insert passphrase to be able to access to private repository but passphrase required message is not prompted.

**What is the expected behavior?**
Passphrase required message should be prompted. Or showing any kind of error message.

**Please mention your node.js, yarn and operating system version.**
yarn --version: **0.24.6**
node -v: **8.1.2**
O.S. version: **OS X 10.12.5**

**Comment by arcanis** [comment]
The message *is* prompted, but overwritten by the progress bar.

Since install from Yarn should work without interaction with the using (think CI, etc), we decided to completely disable prompting for password with git and ssh. Because of this, starting at the next 0.27 release, the install will fail instead of hanging eternally. If you wish to avoid this, we recommend you to use an ssh agent.

**Comment by p-fernandez** [comment]
I agree with the 0.27 release approach. Thank you.
