### ISSUE TITLE
Bug? Symlinks to all workspaces are created in root node_modules

### ISSUE THREAD

**Issue by jardakotesovec** [yarnpkg/yarn#3740]
If I understand the [rfc](https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-workspaces-link-phase-3.md) correctly, it seems to me that the symlinks should be created only if there are some cross references between workspaces in package.json's, which is also behavior I would expect.

But I don't have any such cross references and it still creates symlinks in node_modules for all workspaces:

```
<root>/node_modules/admin-api -> ../admin
<root>/node_modules/toolbox-api -> ../toolbox
<root>/node_modules/user-api -> ../user
```

Root package.json:
```
{
  "private": true,
  "name": "pl-server",
  "dependencies": {
  },
  "devDependencies": {
  },
  "workspaces": [
    "user",
    "admin",
    "toolbox"
  ]
}
```

yarn 0.27.1, node v6.11.0, OS X Sierra 10.12.5

**Comment by bestander** [comment]
This is an implementation detail.
All dependencies are automatically hoisted to the workspace root's node_modules unless there is a dependency name conflict at the root.

From Node.js resolution logic this works fine because it automatically searches for a `require` resolution in the parent folder and it would find it at the root.

I think we could make the links unhoistable but I could not come up with a scenario when it is needed.

**Comment by bestander** [comment]
I'll close the issue for now because it is not actionable but happy to answer more questions and solutions

**Comment by jardakotesovec** [comment]
@bestander My point is why it should create these symlinks there at all, since I don't have explicit dependencies between the workspaces. 

I thought from the rfc that it creates symlinks only if there are actual dependencies between workspaces (defined in individual workspace package.json's).

**Comment by bestander** [comment]
The reason is because it was a lot easier to implement it like this :)
So I have allowed myself to not follow that part of the RFC and do a shortcut.

So far it proves to be working fine like that and Node.js applications work fine by resolving requires to sibling workspaces via the parent's node_modules.
In the end we could update the RFC or fix this aspect in the implementation depending on people's feedback.
