### ISSUE TITLE
Yarn check fails when version is prefixed with a 'v'

### ISSUE THREAD

**Issue by jeffrey-xiao** [yarnpkg/yarn#3776]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`yarn check` fails when version is prefixed with a 'v'.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/jeffrey-xiao/yarn-check-error-repro
```
yarn
yarn check
```

**What is the expected behavior?**
Should not error.

**Please mention your node.js, yarn and operating system version.**
yarn@0.27.1
node@5.11.0
ubuntu@10.04

This doesn't seem to be an issue with yarn@0.24.6 though.

**Comment by bestander** [comment]
There is a package that sanitizes version.
Feel free to send a PR to use it in the check.js command.

**Comment by Intrepidd** [comment]
We investigated a bit with @Timpetricola and found the following: 

- it's broken since b223d51f
- The offending check is https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/check.js#L291, before b223d51f the `pkg.version` would contain a "v" but not after apparently

I'm not familiar at all witht he codebase but maybe using `semver.satisfies`  instead of `!==` would fix it ?

cheers

**Comment by bestander** [comment]
Thanks, @Intrepidd and @TimPetricola.
I see the strict check `pkg.version !== packageJson.version` was there before but maybe something else moved.

I would suggest calling `semver.clean` on the version from package.json.
Would you guys send a PR please?
