### ISSUE TITLE
Unable to install dependencies, 503 from registry backend

### ISSUE THREAD

**Issue by jacek213** [yarnpkg/yarn#3804]
$ curl -I https://registry.yarnpkg.com/
    HTTP/1.1 503 No healthy backends
    Date: Mon, 03 Jul 2017 09:41:20 GMT
    Content-Type: text/html; charset=utf-8
    Connection: keep-alive
    Set-Cookie: __cfduid=d1286fdfaf8c35d860c79024cf2ce60711499074880; expires=Tue, 03-Jul-18 09:41:20 GMT; path=/; domain=.yarnpkg.com; HttpOnly
    Retry-After: 0
    Accept-Ranges: bytes
    Via: 1.1 varnish
    X-Served-By: cache-hhn1543-HHN
    X-Cache: MISS
    X-Cache-Hits: 0
    X-Timer: S1499074880.497217,VS0,VE0
    Server: cloudflare-nginx
    CF-RAY: 3788e372ff646b37-WAW

**Comment by Daniel15** [comment]
This seems like a failure on npm's end... We might need to loop in someone from npm.

**Comment by jacek213** [comment]
It was resolved after about  half hour, however - not sure how that could be npm's fault - yarn's registry backend was the one that responded with 503.

**Comment by Daniel15** [comment]
@jacek213 - Yarn's backend is simply a reverse proxy over the top of npm's one. It's powered by CloudFlare. The error is coming from a Varnish server (see `Via: 1.1 varnish`) which CloudFlare do not use, but npm do (via Fastly). This means the error is coming from the upstream npm servers rather than anything controlled by Yarn 😃

**Comment by jacek213** [comment]
@Daniel15 ok thanks for clarifying - I thought it was yarn's varnish cache :)
