### ISSUE TITLE
yarn upgrade can't update the package.json file?

### ISSUE THREAD

**Issue by NicholasNC** [yarnpkg/yarn#3835]
I didn't understand why use `yarn upgrade` not update the  `package.json` file in the meantime？

**Comment by rally25rs** [comment]
From the docs:

> This command updates all dependencies to their latest version based on the version range specified in the package.json file.

Since the version already specified in `package.json` is used to determine the latest version to upgrade to, the file doesn't need to be changed.

If my package.json contained `foo@^1.0.0` and I currently had version `1.1.0` installed, upgrade might move to a newer version, perhaps `1.2.0`. The package.json entry is still accurate in that I only want versions that match `^1.0.0` (any 1.x version).

**Comment by webmobiles** [comment]
my package.js have:
```

    "redux": "",
    "redux-form": "",
```

I did yarn, and yarn upgrade, but the file keeps empty; there is an option to get filled with the version with ^ ?

**Comment by rally25rs** [comment]
@webmobiles I don't think "empty string" is a valid entry. `yarn upgrade --latest` might replace it with the current version, otherwise just delete those and re-add them.

**Comment by webmobiles** [comment]
thanks, I moved from an old project the package.json so I wanted use the lastest version, so I wrote empty string the long list of packages so i don't write yarn add for every package, with "$ yarn"  yarn.lock is updated well but not package.json ,  yarn upgrade --latest , is equivalente in this case , i think the only solution is to copy again the old package.json and to do a yarn upgrade --latest, but really yarn care about package.json ? when yarn.lock is already created?

**Comment by homerjam** [comment]
This helped me: https://www.npmjs.com/package/syncyarnlock

```
$ yarn upgrade-interactive && syncyarnlock
```
