### ISSUE TITLE
Add default "test" script for running test

### ISSUE THREAD

**Issue by g-plane** [yarnpkg/yarn#3915]
**Do you want to request a *feature* or report a *bug*?**
Feature request.

**What is the expected behavior?**
For a package or a project, if `test` script field isn't in `package.json`, when running `yarn run test` or `yarn test`, Yarn can find bin commands of unit test framework like Jest, Mocha and etc.

For example:
`package.json` may like (Note that `test` field is not existed):
```json
{
  "devDependencies": {
    "jest": "^20.0.4"
  }
}
```
In the project directory, suppose Jest has been installed.
```sh
$ find ./node_modules/.bin/jest
./node_modules/.bin/jest
```
When I am going to run `yarn test` or `yarn run test`:
```sh
$ yarn test                                
yarn test v0.28.0                                        
warning package.json: No license field                   
$ H:\Programming\Node.js\yarn-test\node_modules\.bin\jest
 PASS  __tests__\example-test.js
  √ 1 + 1 should be 2

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.98s
Ran all test suites.
Done in 2.29s.
```

**Comment by rally25rs** [comment]
Sounds a little "magical" to me... Yarn would have to know what installed dependencies could be executed as a test runner. What if `jest` and `mocha` are both installed?

**Comment by g-plane** [comment]
If someone installed both Jest and Mocha, IMHO, `test` script field in `package.json` should be specified manually.

**Comment by BYK** [comment]
I agree with @rally25rs this being too magical. Also, there's this package that would collide: https://yarnpkg.com/en/package/test

I was hoping the `test` package to do the magic for us though 😀

**Comment by g-plane** [comment]
I have read readme of `test` package, and it seems we should specify `test` script in `package.json`. But what I have said is, if `test` script isn't existed, Yarn would choose a test runner. In other word, once `test` script is specified, Yarn would run the specified command.
If there's something I misunderstood, discussion is welcomed.

**Comment by BYK** [comment]
@g-plane sorry for not being more specific. I was trying to say I'd wish a package named `test` do this since you can just run `yarn test` which would invoke that binary automatically.

Although I find the idea interesting, since it is not very feasible to keep track of all test frameworks, I don't think this should be in yarn.

That said you can submit PR's to your favorite test frameworks for them to add a `test` binary automatically or write this as a separate package which provides the so-called binary and does the magic internally.
