### ISSUE TITLE
Use existing yarn directory during upgrade

### ISSUE THREAD

**Issue by markwoon** [yarnpkg/yarn#3944]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

When reinstalling/upgrading yarn on windows using the MSI, it should detect that yarn has already been installed and install into the existing directory.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Install old version of yarn into non-standard directory (e.g. `C:\yarn`).
2. Install newer version of yarn
3. Install does not detect that yarn was previously installed in `C:\yarn`.

**What is the expected behavior?**

MSI should detect that yarn has already been installed, and install the upgrade into the same directory.

**Please mention your node.js, yarn and operating system version.**

node 8.1.4
yarn 0.27.5
Windows 10

**Comment by BYK** [comment]
Thanks for filing an issue for this @markwoon! No promises yet but we'll try to get to this some time.

In the meantime, feel free to try doing it yourself :)

**Comment by BYK** [comment]
@Daniel15, may be you can guide @markwoon about Windows MSI installer packaging?

**Comment by Daniel15** [comment]
I think I know what we're doing wrong, I'll take a look.

**Comment by Daniel15** [comment]
@markwoon - If you don't mind, could you please try this one and see if it works for you: https://ci.appveyor.com/api/buildjobs/8q0wl7dlfep73210/artifacts/artifacts%2Fyarn-0.28.0-20170719.0508-unsigned.msi. It should use the existing directory by default. Since this is an unsigned dev build, you'll need to bypass SmartScreen by clicking "more info" than "Run anyway"

**Comment by markwoon** [comment]
@Daniel15 That did the trick!
