### ISSUE TITLE
Download-Server classified as security threat on latest Chrome

### ISSUE THREAD

**Issue by kwasmich** [yarnpkg/yarn#4019]
When trying to download any of the releases, Google Chrome warns of untrusty servers.
Obviously the download link gets redirected to `https://github-production-release-asset-2e65be.s3.amazonaws.com` but the certificate is not trusted.

**Comment by edmulraney** [comment]
Appears to affect all github repos

**Comment by cggaldes** [comment]
Yes, I've found it on the FreeCAD site as well as the Ethereum site.

**Comment by BYK** [comment]
Why do you think this is a Yarn-related problem?

**Comment by kwasmich** [comment]
I wanted to get yarn and so I noticed it there. Haven't tried to download anything else from GitHub. But the problem seems to have existed only temporary and therby is solved.

**Comment by tatsujb** [comment]
This is a continuing issue for yarn. if you are behind company firewall and must access the net via proxy regular downloads of yarn via web browser will work curl will work on and off but downloading it automatically as part of a maven build (for jenkins deployment for example) will fail. npm and node will work for example because they allow http download. but yarn redirects those to https which causes the download to fail with a `407`

**Comment by BYK** [comment]
I think this issue should be closed since this is a problem with your corporate proxy, not Yarn. Yarn does the right and sane thing by redirecting to HTTPS. It is the proxy who behaves incorrectly by blocking secure traffic.

**Comment by tatsujb** [comment]
I'm a bigger fan of yarn than probably yourself, but the bottom line is : I can get npm on a proxied jenkins setup, the same can't be said for yarn. and I'm doubtful I'm the only one who notices this.
