### ISSUE TITLE
Version is not saved to yarn.lock for GitHub URLs

### ISSUE THREAD

**Issue by hongaar** [yarnpkg/yarn#4052]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When installing a [dependency from a GitHub URL](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) the initial `yarn install` behaves as expected, but saves an empty version string in the `yarn.lock` file:

    "@orbit/orbit@hongaar/orbit":
      version ""
      resolved "https://codeload.github.com/hongaar/orbit/tar.gz/e288d9625af233593c2d9d276ab709f13a6dfcd2"

A second pass of `yarn install` will now yield:

    yarn install v0.27.5
    [1/4] Resolving packages...
    error Package "{package}@" doesn't have a "version".
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**If the current behavior is a bug, please provide the steps to reproduce.**

Given this `package.json`:

    {
        "dependencies": {
            "@orbit/orbit": "hongaar/orbit"
        }
    }

running `yarn install` two times will reproduce this error.

Specifying a semver or using alternative notations (i.e. `github:...`) give the same results.

**What is the expected behavior?**

Some version (master (?) or semver) should be saved to `yarn.lock` and subsequent calls to `yarn install` should not return an error.

**Please mention your node.js, yarn and operating system version.**

node v6.4.0
yarn version v0.27.5
windows 10.1703

**Comment by aij** [comment]
I am also using yarn v0.27.5, but for me it *is* saving the version for Github dependencies.

The problem may be that yarn is resolving to a bad package, and then confusing itself rather than rejecting it.

If you look at
https://github.com/hongaar/orbit/blob/e288d9625af233593c2d9d276ab709f13a6dfcd2/package.json
it is missing a `version` field, which is required [according to the NPM documentation](https://docs.npmjs.com/files/package.json#version).

**Comment by hongaar** [comment]
@aij, thanks, that solved my issue.

Would be nice indeed if `yarn` could complain about this error, but the error was still mine 😳
