### ISSUE TITLE
Yarn local mirror creates invalid file name when Git repository is at server root

### ISSUE THREAD

**Issue by itsananderson** [yarnpkg/yarn#4076]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

My project's local `.yarnrc` is configured with this setting:

```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


yarn-offline-mirror "./virtual_env/yarn_packages"
```

In my `package.json` I have a reference to the following internal package:

```
"private_package": "git+ssh://git@git.corp.net:private_package.git",
```

Notice that Git repository is at the root of the server, rather than being a subfolder as with Github repositories: `git@github.com:itsananderson/some-repo.git`

Unfortunately, with the way Yarn parses the Git URL to generate the cache name, it generates this:

```
:private_repo.git-198dac0ae3f10765058a69d02c4f987527cd9b51
```
I believe that's due to this code: https://github.com/yarnpkg/yarn/blob/5e1eee74f18b7f229e8accb49e7ba9ac9c4655bf/src/fetchers/git-fetcher.js#L40

When a URL like `git+ssh://git@git.corp.net:private_package.git` is parsed, the `pathname` property is set to `:private_package.git`. One potential fix for this would be to simply trim the colon from the beginning.

**If the current behavior is a bug, please provide the steps to reproduce.**

I tried to create a GitHub demo of this issue, but since the issue only appears for repositories where the Git repo name is at the root of the server, the issue can't be reproduced with GitHub repositories.

Here are the steps I used to create a minimal repro by creating a local `--bare` Git clone and adding it as `git+ssh//$USER@localhost:node-extend.git`. I used `node-extend` because it's a simple module with no dependencies that can be installed from its Git repository.

```
# Create local bare git repo
git clone --bare git@github.com:justmoon/node-extend.git

# Clone local repo to make sure host signature is accepted etc.
git clone $USER@localhost:node-extend.git

# Create test project
mkdir git-cache-repro
cd git-cache-repro
yarn init -y
echo 'yarn-offline-mirror "./yarn-packages"' >> .yarnrc
yarn add git+ssh://$USER@localhost:node-extend.git
ls yarn-packages
# Note that the listed package is prefixed by a colon
```

Note that you may need to authorize your own SSH key to log into your machine. This should work for a typical setup:

```
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
```

Hopefully that's enough detail to make the repro easy, but let me know if you need more.

**What is the expected behavior?**

The cache file should be created without a colon in the name. This is an important bug, because colons aren't valid characters in Windows file names.

**Please mention your node.js, yarn and operating system version.**

macOS 10.12.6
Node v6.11.1
Yarn 0.27.5

**Comment by itsananderson** [comment]
As a secondary note, is it intentional that those Git caches don't have `.tgz` appended to their name?

**Comment by BYK** [comment]
Hi @itsananderson, sorry for the late response. It indeed looks like a bug and thanks a lot for taking the time to put the detailed repro instructions.

We are a bit busy busting some other bugs that are higher priority. Although I think this is important, this only constitutes a problem when you have root-level git-repos, use them from yarn and on Windows so less likely to affect many people.

I'd appreciate if you have the time to help us resolve this with a PR. Otherwise we'll get to it but probably later than you'd like us to do :)

**Comment by jespino** [comment]
I think I fixed the problem, I applied the suggested solution by @itsananderson, looks a bit quick and dirty, but I think is the correct, because the getTarballMirrorPath is responsible of converting reference to packageFilename so, I think, it's the correct place to manage this exceptional behavior derived from how url.parse and path.basename works.
