### ISSUE TITLE
Implementation of search by categories

### ISSUE THREAD

**Issue by MAPESO** [yarnpkg/yarn#4182]
I came up with the idea of making a website where all modules in npm are categorized by categories.

**So the newest users, you can search for modules related to fronted or backend** etc. I find it annoying to use the search when you have not the slightest idea that modules can exist for the fronted or backend.

I would like to work on this idea but I need all the modules from npm so that I can classify each module.

**Comment by BYK** [comment]
Hey @MAPESO  - can you explain how this is relevant to yarn?

**Comment by MAPESO** [comment]
@BYK It's an idea that seems good to me and that the thread needs to be better.
I could do the website and then you integrate it with your main site.

**Comment by MAPESO** [comment]
@BYK  This functionality will help users a lot. To discover new packages of npm related to the category that they raised.

I hope you can support my idea please.

**Comment by Haroenv** [comment]
Problem is that it’s quite complex to know if a module is compatible in a certain location. All info we have is in the “keywords” tag of package.json. You can refine based on this information in the Yarn website (see https://twitter.com/haroenv/status/895339855978401792)


![ezgif-1-612f7fffe0](https://user-images.githubusercontent.com/6270048/29486605-7c93fdd0-84ea-11e7-9022-e2545ab8ff81.gif)


Closing this issue here, but feel free to reopen and give more information on https://github.com/yarnpkg/website
