### ISSUE TITLE
yarn install --production is checking for presence of devDependencies

### ISSUE THREAD

**Issue by gpltaylor** [yarnpkg/yarn#4190]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Currently running yarn install --production is not checking for only dependencies. It's also checking devDependencies.

**Why**
In development I am using Lerna with multiple packages, however, I use Webpack to build the bundle. There is a Server (Express) that uses some packages that need to be included into node_modules. I perform a second "npm install --production" to get these packages, before zipping up the build and deploying. I updated to use "yarn install --production" and this failed. This is because this is running in a target/deploy folder and Lerna has not bootstrapped the dependencies. So, Learn looks for packages that are private and normally resolved using Lerna within the Webpack build. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Install only production dependences and not review/look at devDependencies.

**Please mention your node.js, yarn and operating system version.**
node: 6.1.0
lerna: 2.0.0-beta.38
Windows 10

**Comment by rally25rs** [comment]
This is as designed. The dev dependencies must be known in order to have a deterministic lock file and deterministic hoisting of packages in `node_modules/`

If this ends up being a deal-breaker to using Yarn, I know that NPM5 does not check dev or optional dependencies (which leads to them not being in the lock file, and the lock file changing between install types and different OS's, which is also a problem)

I'm pretty sure there was a discussion about this in a closed issue but all I can seem to find at the moment is this comment: https://github.com/yarnpkg/yarn/issues/3577#issuecomment-306449988

Also since NPM5 does not resolve packages that aren't about to be installed (which is the behavior you expect) it results in this bug that I opened against NPM a few days ago: https://github.com/npm/npm/issues/18135

So neither system is perfect at the moment. A possible solution might be to start storing the entire hoisting directory structure in the `yarn.lock` file so that the package metadata doesn't need to be queried.

**Comment by gpltaylor** [comment]
Not a bug but a feature 😄 
Solved this by hoisting these dependencies into the root of Lerna and pushing to the CI as a separate process.

**Comment by eobrien-fsp** [comment]
This is a bug. When running a command like the following...

yarn install --prod --no-lockfile

It should not be looking at devDependencies at all.

**Comment by eobrien-fsp** [comment]
> The dev dependencies must be known in order to have a deterministic lock file and deterministic hoisting of packages in `node_modules/`

Why do the dev dependencies need to be known? They are not relevant in a production system. This surely is what the --prod is for.

If this is going to be the default functionality, there should at least be a parameter to override it. At the moment I'm having to use an alternate package.json just for production, which doesn't contain a devDependencies section.

yarn should do what it's being asked to do and nothing more.
