### ISSUE TITLE
Yarn doesn't notice missing dependency if manually deleted from node_modules

### ISSUE THREAD

**Issue by rally25rs** [yarnpkg/yarn#4197]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

If you manually delete a dependency from `node_modules` and re-run `yarn install` it things it is already up to date.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
$ yarn
yarn install v0.27.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.66s.

$ rm -rf node_modules/grunt/

$ yarn
yarn install v0.27.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.61s.
```

**What is the expected behavior?**

Yarn should detect the missing `grunt` package and install it.

**Please mention your node.js, yarn and operating system version.**

yarn 0.27.5
node 8.3.0

**Comment by rally25rs** [comment]
Just noticed that using `yarn install --check-files` does properly find and reinstall the missing packages.

Is this by-design that `check-files` needs to be manually passed to actually find missing dependencies?

**Comment by arcanis** [comment]
Yes. The default behavior simply checks if the node_modules is already there or not (it also checks if the flag used are the same, but this is irrelevant here). In order to track the directories themselves, you also need to use the `--check-files` option, which embed the directory listing inside the `node_modules/.yarn-integrity` file.

**Comment by rally25rs** [comment]
thanks for the info! I'll go ahead and close this...
