### ISSUE TITLE
yarn-lockfile package doesn't work independently

### ISSUE THREAD

**Issue by palmerj3** [yarnpkg/yarn#4213]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

yarn-lockfile is not able to parse yarn.lock files outside of the yarn project.

**If the current behavior is a bug, please provide the steps to reproduce.**
Simple public repository showing the issue:
https://github.com/palmerj3/yarn-lockfile-test

This is due to the fact that yarn-lockfile has a dependency on yarn itself. Yet when used in a new project, the yarn dependency only contains a concated file in libs (yarn-cli.js) and so these require statements in yarn-lockfile/index.js fail:

```
module.exports = {
  parse: require('yarn/lib/lockfile/parse.js').default,
  stringify: require('yarn/lib/lockfile/stringify.js').default
}

```
**What is the expected behavior?**

Sample public repository should be able to parse the sample lockfile.

**Please mention your node.js, yarn and operating system version.**

Node: 6.10.3
OS: OS X 10.12.6
Yarn: 0.27.5

**Comment by palmerj3** [comment]
From the thread in https://github.com/yarnpkg/yarn/pull/4114 this may be a known issue?

Either way I'm super excited to use this package!

**Comment by palmerj3** [comment]
After further digging it looks like the new yarn-lockfile isn't published yet?

@wmhilton's original package is still referenced in NPM under that name.

**Comment by Daniel15** [comment]
Yes, the new package is not published yet. Likely it'll be available as `@yarnpkg/lockfile`.

**Comment by Daniel15** [comment]
Published the new one: https://yarn.pm/@yarnpkg/lockfile

**Comment by wmhilton** [comment]
@palmerj3 I have updated the `yarn-lockfile` package to provide a migration path for users. Version 1.1.0 depends on `@yarnpkg/lockfile` rather than on `yarn`, and version 1.1.1 is the exact same code as 1.1.0 but shows a deprecation message in the README and on npm install informing users that yarn now publishes an official lockfile package.

But if developers never update their code they should be fine too because `yarn-lockfile` specifies "*" for the version so it will always install the latest version of `@yarnpkg/lockfile` (unless you've got another version of @yarnpkg/lockfile already installed somewhere in which case it might use that I guess).
