### ISSUE TITLE
Support npm config "script-shell"

### ISSUE THREAD

**Issue by aikar** [yarnpkg/yarn#4248]
NPM 5.1 added a much longed feature to set the "script-shell" to be used for npm run commands.

This allowed our team to resolve the issue where scripts ran by npm run did not execute in git bash on windows, even though the command was being executed by git bash.

running `npm config set script-shell bash` resolves the issue under NPM, but does not work for yarn.

Please add support for this config so that when yarn has to invoke a command, it respects the config for what shell to use instead of cmd.exe.

**Comment by aikar** [comment]
Any update on this?

**Comment by arcanis** [comment]
Our attention is focused on other issues atm, but please feel free to open a PR and we'll gladly review it :)

**Comment by aikar** [comment]
closed via a2a054438fe91f9860dd06cc4ee7b8004ad7efa0

**Comment by carsonpowers** [comment]
Need this :<

**Comment by kaleidawave** [comment]
Is this present in yarn 2?

`shell-scripts` doesn't seem to exist under the configuration section

**Comment by arcanis** [comment]
No. Yarn 2 implements its own bash-like shell, which is portable across systems and thus doesn't require to set a custom interpreter (using a custom one would make your code non-portable, hence why we don't provide a setting to change it).

**Comment by kaleidawave** [comment]
Ah okay. Having a problems on windows with `yarn 2.4.2`. Running a script via `yarn workspace .. run` with a `cp` command in the script fails saying it is not present...?

**Comment by arcanis** [comment]
`cp` isn't a shell, it's a command. Regardless of the shells, you need to have the underlying binaries present (except for a few binaries implemented as builtins, like `echo`).

**Comment by kaleidawave** [comment]
Yep I know `cp` isn't a shell 😂 I have had a problem in the past with npm and a script with `cp` in. Then I switched npms `shell-scripts` to use powershell (which has cp command as a alias) instead of command prompt and the script worked fine.

I believe this is the same issue. I think my yarn installation is correct so it should have the *underlying binaries* present? Currently the script is works fine when in git-bash so using that as workaround for the moment :)
