### ISSUE TITLE
yarn add .git repo postinstall issue

### ISSUE THREAD

**Issue by willin** [yarnpkg/yarn#4309]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

```bash
yarn add --dev https://github.com/AirDwing/babel-plugin-transform-pipeline.git#master
```

```
[!] (babel plugin) ReferenceError: Unknown plugin "transform-pipeline" specified in "/Users/willin/Documents/w2fs/esnext-pipeline-biolerplate/.babelrc" at 0, attempted to resolve relative to "/Users/willin/Documents/w2fs/esnext-pipeline-biolerplate"
src/index.js
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```bash
yarn add --dev https://github.com/AirDwing/babel-plugin-transform-pipeline.git#master
# must build manually
cd node_modules/babel-plugin-transform-pipeline && yarn && yarn build
```

**What is the expected behavior?**

```bash
yarn add https://xxx.git  # automatically build
```

**Please mention your node.js, yarn and operating system version.**

node 8.4.0

os x 10.12.6

**Comment by BYK** [comment]
Thanks for the report! That said this looks like a problem with the package or your setup since if the package required building after install, it would have (or should) defined a `postinstall` script. Right now it doesn't have this.

Packages usually ship the built version of the files but since you are using it from master, this isn't the case. I think you should open an issue in that repo and discuss possible options with the maintainers.
