### ISSUE TITLE
Yarn 1.X - Can't install Github Pull Requests anymore

### ISSUE THREAD

**Issue by mtraynham** [yarnpkg/yarn#4369]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Yarn 0.X allowed you to install PR commits by referencing the PR number.  I've seen a few ways to do this, but it's always worked for me as:
`yarn add angular-ui/ui-layout#228/head`

Using 1.X, you now get:
```
yarn add v1.0.1
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find match for "228/head" in "_c" for "https://github.com/angular-ui/ui-layout.git".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn init; yarn add angular-ui/ui-layout#228/head`

**What is the expected behavior?**
It installs the head commit of the Pull Request.

**Please mention your node.js, yarn and operating system version.**
Node 8.4
Yarn 1.0.1
Linux Mint 18.3

**Comment by KristofMorva** [comment]
I can confirm. I'd also like add, it's not working for getting PR commit IDs either (like `flatlogic/awesome-bootstrap-checkbox#49f4bd03155c6ce6c006d0957c22e65888d657a9`).

**Comment by BYK** [comment]
@mtraynham @KristofMorva please see @arcanis' comment on the PR: https://github.com/yarnpkg/yarn/pull/4411#issuecomment-328827415

Looks like it was intentional removing the PR support and I now remember having a similar discussion now. The reason was the `/pr/` pattern looks like the code is from this repo but it can be from another repo which may be a security issue. Instead of using PR's directly, it is still possible to use the different repo + commit combination. What do you think about this?

**Comment by mtraynham** [comment]
I don't disagree, but I think you guys are missing a valuable feature of PRs when used this way; at least from my interpretation it seems like it's implemented this way.

When a forked repo branches and creates a PR, referencing a forked branch is circumstance to being deleted and the git commit reference or branch alias could disappear.  When referencing a PR "branch" in the upstream repo, the user could delete the forked branch, but the commits within the PR persist and they cannot be deleted.

**Comment by KristofMorva** [comment]
@BYK yes, it's true we can. For us, it's just more obvious that "we are waiting for this PR to be merged" instead of referencing a forked repo, and it's also easier to check if we can get back to the original repository because on the PR you see it's status, the fork is really uninformative. But it's only our case, we can adapt if this change was intentional :)

**Comment by BYK** [comment]
Thank you both for the very informative answers!

>When a forked repo branches and creates a PR, referencing a forked branch is circumstance to being deleted and the git commit reference or branch alias could disappear (e.g. yarn add mtraynham/ui-layout#my_branch). When referencing a PR "branch" in the upstream repo, the user could delete the forked branch, but the commits within the PR persist and they cannot be deleted (e.g. yarn add angular-ui/ui-layout#228/head).

I think this is a good-enough reason to keep it, what do you think @arcanis?

**Comment by vizath** [comment]
Note to future Google searches: I had permission issues on my ssh key which also gave this error.
