### ISSUE TITLE
Extraneous dots in "yarn outdated" output

### ISSUE THREAD

**Issue by mjomble** [yarnpkg/yarn#4395]
**Do you want to request a *feature* or report a *bug*?**
To report a bug

**What is the current behavior?**

Yarn uses different coloring for the matching and different parts of the current and wanted versions.
However, if the current and wanted versions are the same, there is an extraneous dot at the end of the wanted version:

![](https://i.imgur.com/KXvahiu.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
Install a version of a package that is not the latest.
Make sure the version range in package.json matches the version you installed.
Run `yarn outdated`

**What is the expected behavior?**

There should be no extraneous dots.
For example, on the above image, the wanted version of `expect` should be `1.20.2` instead of `1.20.2.`

**Please mention your node.js, yarn and operating system version.**
node.js 6.11.3
yarn 1.0.1
Windows 7

**Comment by solkaz** [comment]
Also noticing this on my project: 

![screen shot 2017-09-11 at 9 52 33 am](https://user-images.githubusercontent.com/10211603/30281119-314bffc2-96d7-11e7-8445-fad19d40ec1e.png)


Node.js: 8.4.0
Yarn: 1.0.0
OSX El Capitan 10.11.6

**Comment by solkaz** [comment]
I think the issue is in the [colorize-diff](https://github.com/yarnpkg/yarn/blob/master/src/util/colorize-diff.js) function. 

1. When `from` and `to` are identical, `splitIndex` will be equal to `parts.length`
2. In the next statement, we take the slice of `parts`, but since the `begin` argument to `slice` is the `parts.length`, it will return an empty array, which will return an empty string when `join` is invoked on it, so `colorized = ''`
3. The function will then return the entire `parts` array _concatenated with the empty string_ that is then `join`'d. If `parts === ['1', '0', '0']`, for example, then it would return `parts.concat('').join('.')`, which evaluates to `1.0.0.`

I'm not sure of how to fix this; should it just return `parts.join('.')` if `from` and `to` are equal?

**Comment by Daniel15** [comment]
> I would be willing to make a PR for it.

That would be great, thanks! Ideally with a unit test too :)
