### ISSUE TITLE
Not all top level packages are downloaded

### ISSUE THREAD

**Issue by musaffa** [yarnpkg/yarn#4420]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Yarn doesn't download all top level packages as written in `yarn.lock`.

**If the current behavior is a bug, please provide the steps to reproduce.**

For this package.json:
```json
{
  "name": "test-yarn",
  "dependencies": {
    "ember-apollo-client": "^0.4.2"
  }
}
```
A yarn.lock is generated which contains `ember-apollo-client`'s dependency `graphql-tools` as a top level package. But in the `node_modules` directory `graphql-tools` is not downloaded as a top level package.

**What is the expected behavior?**

All the top level packages written in `yarn.lock` should be found in the `node_modules` directory as top level packages. With yarn `v1.01`, `graphql-tools` package is missing. But this was not a problem with yarn `v0.28.4`. 

**Please mention your node.js, yarn and operating system version.**

node.js: 8.2.1
yarn: 1.01
OS: Ubuntu 16.04 LTS 64 bit

The problem can be solved by downgrading yarn to `v0.28.4`.

**Comment by arcanis** [comment]
It's weird it hasn't been hoisted, however this is not a bug per spec. This is *not* the guarantee:

> All the top level packages written in yarn.lock should be found in the node_modules directory as top level packages.

The correct guarantee is:

> All the packages listed in the `package.json` dependencies should be found in the node_modules directory as top level packages.

**Comment by musaffa** [comment]
Why should I? With npm and yarn `0.28.4` this is not a problem.

**Comment by arcanis** [comment]
Investigated a bit, and the behavior is completely correct:

- `ember-apollo-client` is depending on `apollo-client@^1.0.4`, `graphql-tools@^0.10.0`, and `graphql@^0.9.1`

- `apollo-client@1.0.4` is depending on `graphql@^0.10.0`

- note that `0.10.0` doesn't match `^0.9.1` in semver terms (because they are under the `0.x.y` umbrella), neither does `0.9.1` match `^0.10.0`

- `graphql@0.10.0` gets hoisted to the root, but because the versions conflict, `graphql@0.9.1` cannot and must stay under `ember-apollo-client`

- `graphql-tools@0.10.0` has a peer dependency on `graphql`. It means that it *must* use the version its parent provides, otherwise it would be non-conforming.

- Because the version its parent provides (ie `graphql@0.9.1`) cannot be hoisted, it means that `graphql-tools` cannot either.

Of course, none of this changes anything to the fact that the contract we have is that we will provide you all the dependencies you requested in your `package.json` listing, recursively (ie. each dependency will be able to access its own dependencies, but has no guarantee on being able to require any other). The rest is an implementation detail, an optimization we do to be more efficient and less space-consuming.

**Comment by arcanis** [comment]
For what it worth, it worked in 0.28.4 because the 0.28.4 was buggy and was hoisting the packages without considering the peer dependencies. Fixing this bug simply revealed the undefined behavior you were relying upon.

**Comment by arcanis** [comment]
And as for why it works on npm, it looks like npm is actually suffering from the bug we previously had: its `graphql-tools` package gets hoisted even tho its peer dependencies aren't, which means it will use a different `graphql` version than `apollo-client`.

**Comment by musaffa** [comment]
Thanks for clearing the issue.
