### ISSUE TITLE
Handle upgrade-interactive fail state

### ISSUE THREAD

**Issue by olingern** [yarnpkg/yarn#4436]
Continuation from #4434

Things that should be resolved:

  1. When do rejections happen? i.e. failed upgrade
  2. What is the right recourse? i.e. ask for a retry, etc.
  3. Tests to verify upgrade-interactive responds as expected in all fail states ( lost connection, failed upgrade, etc.)

**Comment by olingern** [comment]
@torifat @arcanis @BYK If you all have any info on the right recourse for a failed state (exit, retry, etc.) that'd be super helpful!

**Comment by BYK** [comment]
I'm not familiar with this part of the code but I'm hoping @torifat is.

**Comment by torifat** [comment]
1. Are you asking about the Inquirer reject or the `try-catch` reject inside `run`?
2. IMO most of the time it doesn't make sense to retry. Because we already re-try for network failure. I would expect some useful feedback so that I can decide about my next action. But, others maybe have some better idea @yarnpkg/core
3. Test for `lost connection`, `failed upgrade` and <kbd>Ctrl + C</kbd> seems like a good start.

**Comment by olingern** [comment]
@torifat 
1. Yes 👍 
2. Hmm ... if upgrade failed (i.e. insufficient permissions or out of disk space ) -- we should exit here and let user determine the right recourse from the error output?
3. 👍
