### ISSUE TITLE
Yarn 1.1.0 reports itself as 1.0.2

### ISSUE THREAD

**Issue by DenisVuyka** [yarnpkg/yarn#4548]
**Do you want to request a *feature* or report a *bug*?**

Bug report

**What is the current behavior?**
`yarn --version` reports 1.0.2 for 1.1.0

**If the current behavior is a bug, please provide the steps to reproduce.**

For macOS:

- install yarn 1.1.0 via brew
- run `yarn --version`
- the output is `1.0.2`

Note: the lib itself installed to `/usr/local/Cellar/yarn/1.1.0/` folder.

**What is the expected behavior?**

the output should be `1.1.0`.

**Please mention your node.js, yarn and operating system version.**

OS: macOS 10.12.6 
node: 8.5.0
yarn: 1.1.0

**Comment by devoto13** [comment]
Can you post output of?

    $ ls -al `which yarn`

**Comment by DenisVuyka** [comment]
```
-rwxr-xr-x  1 username  staff  878 13 Sep 12:41 /Users/username/.yarn/bin/yarn
```

Replaced real user name with `username`

**Comment by devoto13** [comment]
You're using Yarn not installed from Homebrew, but installed using some other method. That's why you get the wrong version.

You should probably remove this installation or remove `/Users/username/.yarn/bin` from `PATH` to make it use installation from Homebrew. If everything done right you should get something like:

    $ ls -al `which yarn`
    lrwxr-xr-x  1 devoto13  admin  29 Sep 26 12:47 /usr/local/bin/yarn -> ../Cellar/yarn/1.1.0/bin/yarn

**Comment by DenisVuyka** [comment]
That helped thanks.
