### ISSUE TITLE
Yarn hangs when running as child process of node 5.x et 6.x on Windows

### ISSUE THREAD

**Issue by sandorfr** [yarnpkg/yarn#4694]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
When running on node 5.x ou 6.x, yarn version 1.0, 1.1 and 1.2 will hang if it is running as child process of another node processus on Windows.

The bug the not happen with node 8.x.

**If the current behavior is a bug, please provide the steps to reproduce.**
For example when running `yarn test` of [this project](https://github.com/jrr/vsts-yarn-issue-repro) on [VSTS  using the task extension](https://marketplace.visualstudio.com/items?itemName=geeklearningio.gl-vsts-tasks-yarn), yarn will hang in 80% of the cases.

You can find additional background here : https://github.com/geeklearningio/gl-vsts-tasks-yarn/issues/17

**What is the expected behavior?**
It should fail or succeed but not hang.

**Please mention your node.js, yarn and operating system version.**
Windows Server 2016, Windows Server 2012
Node 5.x, 6.x
Yarn 1.0, 1.1, 1.2

**Comment by paul-soporan** [comment]
Closing as there have been many Yarn versions and Node versions released since this was posted. If it still happens with the v1, please check if it's still the case in the v2 where many things have improved (https://yarnpkg.com/getting-started/migration).

If it still happens with the v2, please open an issue in https://github.com/yarnpkg/berry.
