### ISSUE TITLE
Install without package.json

### ISSUE THREAD

**Issue by ronag** [yarnpkg/yarn#4813]
For docker builds it would be nice to be able to run `yarn` with only the lock file, i.e. without the `package.json` file. Currently, whenever we run `npm version patch` we have to re-install all dependencies even though nothing has changed... :/

**Comment by BYK** [comment]
Yarn needs both `package.json` and `yarn.lock` files by design and I don't think that will change anytime soon if ever.

I think instead of copying all files in the directory, you can find a way to leverage Docker's layered file system with selectively copying files over.

**Comment by ronag** [comment]
@BYK I don't see anyway to resolve this otherwise? Since the package.json is changed during versioning and it has to be included before you run `yarn` you always have to re-install all dependencies even if they haven't changed...

**Comment by tianjianchn** [comment]
May be using another file to save the version, like VERSION. use `semver -i patch <version>` to generate the new version and use `fs.writeFileSync` to save it to VERSION file

**Comment by Downchuck** [comment]
This is an awful experience when using offline workspaces with Docker as the primary yarn.lock does contain information for unpacking files.

**Comment by sebmellen** [comment]
@BYK and @ronag and @Downchuck have any of you found a way to resolve this yet? 

I'm into doing the same thing as I'm using yarn workspaces, and otherwise I have to pull in and concatenate dependencies from the `package.json` files in each submodule I've added to my project. If I could just install from `yarn.lock` which is in the top-level directory and lists _all_ the hoisted packages of _all_ the submodules, I could just copy that over to the base Docker layer and save myself the trouble...

Kinda stumped looking for ways around this.

**Comment by rohit-gohri** [comment]
I created a small helper for yarn berry (v2+) inspired by pnpm's fetch that recreates the workspace just from the lockfile so yarn can do a successful install - https://github.com/rohit-gohri/yarn-lock-to-package-json

```
COPY .yarn ./.yarn
COPY yarn.lock .yarnrc.yml ./

RUN yarn dlx yarn-lock-to-package-json

RUN yarn install --immutable
```

This means docker layer cache is not invalidated due to random changes in package.jsons

**Comment by sod** [comment]
Thats a clever sollution @rohit-gohri, and also kinda proves that requiring the package.jsons for `yarn install --immutable` is arbitrary if you are able to generate what yarn wants from the lockfile.

I wonder if doing this as a plugin instead would be possible.

**Comment by rohit-gohri** [comment]
> I wonder if doing this as a plugin instead would be possible.

I tried doing it but could not figure out yarn internals 😅 , this way ended up being easier.  There is a issue in yarn v2+ where the author tried implementing a plugin - https://github.com/yarnpkg/berry/issues/4529
