### ISSUE TITLE
yarn scripts file matches in process.argv doesn't match result in shell

### ISSUE THREAD

**Issue by sixinli** [yarnpkg/yarn#4951]
**report a *bug***

**What is the current behavior?**
yarn scripts with file regex doesn't match folders properly
**If the current behavior is a bug, please provide the steps to reproduce.**

repro at: https://github.com/sixinli/testYarn

```
➜  testYarn git:(master) ✗ yarn test
yarn run v1.3.2
$ ./node_modules/test-log/bin/test-log folder1/src/**/*.txt
2 [ 'folder1/src/inner-src/inner-src1.txt',
  'folder1/src/inner-src/inner-src2.txt' ]
✨  Done in 0.18s.

➜  testYarn git:(master) ✗ ./node_modules/test-log/bin/test-log folder1/src/**/*.txt
4 [ 'folder1/src/inner-src/inner-src1.txt',
  'folder1/src/inner-src/inner-src2.txt',
  'folder1/src/src1.txt',
  'folder1/src/src2.txt' ]
```

`test-log` is basically doing `console.log(process.argv.slice(2).length, process.argv.slice(2));`

**What is the expected behavior?**
expected the list of files that matches to be the same

**Please mention your node.js, yarn and operating system version.**
node: v8.9.1
yarn: 1.3.2
MacOS: 10.12.6

**Comment by rally25rs** [comment]
I get the same 2 files any way I run it:

```
~/Projects/testYarn : yarn run test
yarn run v1.3.2
$ ./node_modules/test-log/bin/test-log folder1/src/**/*.txt
2 [ 'folder1/src/inner-src/inner-src1.txt',
  'folder1/src/inner-src/inner-src2.txt' ]
✨  Done in 0.14s.

~/Projects/testYarn : test_packages/test-log/bin/test-log folder1/src/**/*.txt
2 [ 'folder1/src/inner-src/inner-src1.txt',
  'folder1/src/inner-src/inner-src2.txt' ]

~/Projects/testYarn : ./node_modules/test-log/bin/test-log folder1/src/**/*.txt
2 [ 'folder1/src/inner-src/inner-src1.txt',
  'folder1/src/inner-src/inner-src2.txt' ]
~/Projects/testYarn (sli/yarn_file_regex_test) :
```

The 2 files are also what OSX (Sierra 10.12.4)'s `ls` command sees for that glob pattern:

```
~/Projects/testYarn : ls folder1/src/**/*.txt
folder1/src/inner-src/inner-src1.txt folder1/src/inner-src/inner-src2.txt
```

At a base level, Yarn calls Node.js's [child_process.spawn()](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) with the command `./node_modules/test-log/bin/test-log folder1/src/**/*.txt` so after that it is in Node's hands. Yarn does not "resolve" these on its own.

-----

It seems like `'folder1/src/src1.txt'` and `'folder1/src/src2.txt'` should not match that glob pattern anyway, so I'm not sure why they would be in your output. That seems incorrect. Perhaps whatever shell you are using is globbing differently? My output above was from `/bin/bash` shell, but I think resolving glob patterns is shell-implementation-dependent.

Going to close this for now since those 2 files seem correct for the pattern, and it's not interpreted by Yarn anyway. If you find out any additional info on why the difference, please post it here and we could reopen this.

**Comment by sixinli** [comment]
sorry @rally25rs i dont think we have the same result with ls
```
➜  testYarn git:(sli/yarn_file_regex_test) ls folder1/src/**/*.txt
folder1/src/inner-src/inner-src1.txt folder1/src/inner-src/inner-src2.txt folder1/src/src1.txt                 folder1/src/src2.txt
```

also `**` matches non or any?

**Comment by sixinli** [comment]
to illustrate it more, i updated the repro with one extra layer:
```
➜  testYarn git:(sli/yarn_file_regex_test) ✗ yarn test
yarn run v1.3.2
$ ./node_modules/test-log/bin/test-log folder1/src/**/*.txt
2 [ 'folder1/src/inner-src/inner-src1.txt',
  'folder1/src/inner-src/inner-src2.txt' ]
✨  Done in 0.25s.
➜  testYarn git:(sli/yarn_file_regex_test) ✗  ./node_modules/test-log/bin/test-log folder1/src/**/*.txt
6 [ 'folder1/src/inner-src/inner-inner-src/inner-inner-src1.txt',
  'folder1/src/inner-src/inner-inner-src/inner-inner-src2.txt',
  'folder1/src/inner-src/inner-src1.txt',
  'folder1/src/inner-src/inner-src2.txt',
  'folder1/src/src1.txt',
  'folder1/src/src2.txt' ]
```

**Comment by sixinli** [comment]
my bad - zshell and bash are showing different behavior... will echo back if i figure out whats going on in the circle box vs local vs different shell thing

**Comment by rally25rs** [comment]
Yeah I suspected you might be in a different shell. This is a zsh vs bash difference in how they resolve the patterns.

Another look at the Node.js docs and I noticed:

> runs command inside of a shell. Uses '/bin/sh' on UNIX

Which would explain it. The glob pattern is likely being resolved by `sh` instead of `zsh`.

It does look like you can pass a shell string to `.spawn()` in it's options ('/bin/zsh' for example). Would it be helpful to make this issue a "feature request" to have a .yarncfg option to override the shell?

**Comment by rally25rs** [comment]
One final thought:

First, I tried this in `npm run test` from `bash` and `zsh` and only get 2 files, so NPM exhibits the same behavior as Yarn.

Second, I don't think we should offer overriding the shell as a config feature either, because people's npm scripts have likely all been written for and tested on the default `/bin/sh` and if any of those scripts have something like `cp foo/**/*.js` or `rm foo/**/*.js` then it would result in potentially incorrect or behavior when run on different shells.

So IMO this issue should stay closed and not reopen as a feature request as I was initially inclined to do.
