### ISSUE TITLE
"Unmet peer dependency" with peer dependency already installed as transitive dep

### ISSUE THREAD

**Issue by Hypnosphi** [yarnpkg/yarn#4962]
To reproduce, just follow the instructions from here: https://github.com/yarnpkg/yarn/issues/2688#issue-207140699

```shell
yarn init -y
yarn add storyboard@3.0.0-rc.1
yarn add storyboard-listener-console@3.0.0-rc.1
```

Then you get a warning about missing `storyboard-core`:
```
warning " > storyboard-listener-console@3.0.0-rc.1" has unmet peer dependency "storyboard-core@^3.0.0-rc.0".
```

But it's actually present (as a **transitive** dependency):
```
$ yarn list storyboard-core
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ storyboard-core@3.1.3
```

**Comment by BYK** [comment]
@Hypnosphi would you mind explaining why this is not the same issue as #4850?

**Comment by Hypnosphi** [comment]
#4850's author says:
> I've seen multiple issues with the same subject but not the same reason, here React is not a transitive dependency

**Comment by Hypnosphi** [comment]
The steps are exactly the same, honestly I don't understand what's unclear:

```
$ yarn init -y
$ yarn add storyboard@3.0.0-rc.1
$ yarn add storyboard-listener-console@3.0.0-rc.1
```

**Comment by BYK** [comment]
Okay, I've investigated this and the warning is correct. Transitive dependencies are accepted only if they are on the same tree. Here, `storyboard-core` comes from `storyboard` which is installed side-by-side with `storyboard-listener-console` which is the package that needs `storyboard-core` as a peer dependency.

There's no guarantee that `storbyboard-core` would be available to `storyvoard-listener-console` with this setup since it belongs to a tree under `storyboard` which doesn't have any intersections with the `storyvoard-listener-console` tree.

**Comment by EECOLOR** [comment]
> There's no guarantee that `storyboard-core` would be available to `storyboard-listener-console` with this setup since it belongs to a tree under `storyboard` which doesn't have any intersections with the `storyboard-listener-console` tree.

@BYK Could you please explain this a bit more?

I might be totally wrong as my knowledge of yarn and node modules is very limited, but to my knowledge `storyboard-core` would be installed at the top level `node_modules` unless it was already installed there with a different version. If that was the case the matching algorithm should check that one.

My statement probably shows my lack of knowledge which is why I asked the original question: could you elaborate what you mean?

Thanks

**Comment by Hypnosphi** [comment]
> `storyboard-core` would be installed at the top level `node_modules`

It's just an optimization, there's no guarantee that they will keep doing this
