### ISSUE TITLE
Add option to skip re-building packages with platform dependencies

### ISSUE THREAD

**Issue by langri-sha** [yarnpkg/yarn#4987]
Imagine you're on a slow internet connection and you have `node-sass` in your dependencies which goes through an expensive, time-consuming download of binaries from the internet.

Is there no way to be able to skip this and simply reuse what has been previously built?

Yarn 1.3.2
Node.js v8.8.1

**Comment by bestander** [comment]
node-sass and similar packages download the binaries in their install scripts which could be any bash script outside of Yarn's influence.
Quite possible you could pass a no-download option via environment variables to that install script.

But otherwise Yarn is not in control what every package is doing so it is up to the package authors to decide on offline modes.

I'll close the issue as we currently can't act on this issue.
Please feel free to continue discussion.

**Comment by langri-sha** [comment]
Thanks! Is there any way we can tell Yarn to use what package it might have built previously? I haven't dug in, but I can see my Yarn cache growing over time, so they must be retained somewhere.

I've tried passing flags that might help me circumvent these packages getting rebuilt to no avail. I understand this might be important first because whatever their scripts do might get invalidated between two build attempts and secondly because something might have changed on the user's platform as well, but this really leaves me 💔 💥 🔨 because the motivation to move to Yarn was to avoid unnecessary I/O in order to save time.

**Comment by langri-sha** [comment]
I guess for the time being someone might want to run a HTTP proxy that caches responses to circumvent this problem.

**Comment by bestander** [comment]
I suppose Yarn could have an option to skip build steps for a particular package.
Similar to what we do in https://github.com/yarnpkg/rfcs/pull/86.
Hack around in package-linker.js and send a PR :)
