### ISSUE TITLE
add local repository with branch

### ISSUE THREAD

**Issue by alpha-and-omega** [yarnpkg/yarn#5017]
Requesting a feature.

Please make it possible to add local repository providing a branch:
yarn add file:../repo/sitory#branch
fails
yarn add file:../repo/sitory@version
fails

**Comment by rally25rs** [comment]
#5026 pushes this a step closer. It will allow a local git repo of the form `file:../my-project.git` (the tailing `.git` is the key to having Yarn process it as a Git repo instead of a plain filesystem structure).

From there is should be a simple change to have it check for local un-pushed branches.

**Comment by alpha-and-omega** [comment]
Why file-git-fix is not a part of a master since 15 december 2017 ?

**Comment by arcanis** [comment]
Because I just merged it 🙂 Will be part of the next release.
