### ISSUE TITLE
How to use bower artifactory (private repository) with Yarn?

### ISSUE THREAD

**Issue by nishantkagrawal** [yarnpkg/yarn#5053]
**Do you want to request a *feature* or report a *bug*?**
Not sure. I am looking for a specific feature and not sure whether it is available or not.

I am trying to migrate from bower to yarn.

I am currently using the following properties in .bowerrc file. We are using a JFrog artifactory to host our private bower components

```
registry": {
        "search": [
            "http://domain-api.mycompany.com/artifactory/api/bower/default.bower.global",
            "http://bower.int.thomsonreuters.com",
            "https://bower.herokuapp.com"
        ]
    },
    "resolvers": [
        "bower-art-resolver"
    ],
```

When I ran bower-away it produced something like this
```
"@bower_components/my-package": "art://my-package/my-package#1.0.0",
```

My .npmrc file has
```
registry = "http://domain-api.mycompany.com/artifactory/api/npm/default.npm.global"
```

When I run ```yarn```, I get
```
error An unexpected error occurred: "http://domain-api.mycompany.com/artifactory/api/npm/default.npm.global/@bower_components%2my-package: not_found".
```
How to deal with this? Does yarn support installing bower components from private repository?

**Comment by bestander** [comment]
@nishantkagrawal, try searching in existing issues for a workaround or a solution https://github.com/yarnpkg/yarn/issues?q=is%3Aissue+artifactory+is%3Aopen.

Otherwise try our Discord channel https://discordapp.com/invite/yarnpkg, there are plenty of people happy to help with questions.

We organize github issues for bugs and not for questions otherwise we won't be able to prioritize work well.
So I'll close this one but feel free to comment and if you find a solution or workaround please post here.
