### ISSUE TITLE
How to setup remote repository to download yarn releases

### ISSUE THREAD

**Issue by MaxCCC** [yarnpkg/yarn#5058]
I try to setup a remote registry (generic) on Artifactory to download yarn releases (specified in our pom).
Most of our plugins use the format:
`vX.X.X/yarn-vX.X.X.tar.gz`

Just the same for node where it's working.

I just simply tried to import `https://github.com/yarnpkg/yarn/releases/download/` as URL and our plugins are providing `v.1.3.2/yarn-v1.3.2.tar.gz` but we recieve a 404 forbidden. (as a sort of proxy)

What is the recommended way to setup a remote registry to artifactory releases and does it has to point to github releases or are they stored somewhere else.

We need the `v.1.3.2/yarn-v1.3.2.tar.gz`  format too because we are using the frontend-maven-plugin which needs those arguments to download the right release.

**Comment by Daniel15** [comment]
You can use https://yarnpkg.com/downloads/1.3.2/yarn-v1.3.2.tar.gz as the URL, or https://yarnpkg.com/latest.tar.gz to get the latest version.

**Comment by Daniel15** [comment]
There's also https://yarnpkg.com/latest-version if you just want to know the latest version number.

**Comment by tatsujb** [comment]
thanks for the above but I'd need the `http` version of that not `https` else I can't include downloading it as part of a maven build.

**Comment by Daniel15** [comment]
yarnpkg.com forces HTTPS... Can you not use HTTPS as part of a Maven build?

**Comment by tatsujb** [comment]
no, not when I'm behind corporate-imposed firewall... 😞

**Comment by stieler-it** [comment]
@tatsujb Of course that is easy to say, but you should somehow fix this. Downloading executables without validating at least the server certificate seems to be a bad idea in terms of security.

I want to add that we have the same problem. Fetching from `http://artifactory/yarn-github/v1.5.1/yarn-v1.5.1.tar.gz`

returns

```
{
  "errors" : [ {
    "status" : 404,
    "message" : "Forbidden"
  } ]
}
```

In our case HTTPs can not be a problem because the remote repository to `https://nodejs.org/dist/` worked out of the box.

The alternative URL provided by @Daniel15 is probably just a redirect to GitHub. Also, the path structure is slightly different, so if eirslett/frontend-maven-plugin would try to fetch from

`https://yarnpkg.com/downloads/v1.3.2/yarn-v1.5.1.tar.gz`

it is redirected to

`https://github.com/yarnpkg/yarn/releases/download/vv1.3.2/yarn-v1.5.1.tar.gz`

(Notice the double v)

**Comment by lvthillo** [comment]
Same issue for us. As workaround we are using a remote repo to `https://npm.taobao.org/mirrors/yarn` which acts the same as `https://nodejs.org/dist/`. Generic remote repo's to those url's work fine but we did not manage to find a way how to handle this for yarn releases immediately.

We tried to set those url as remote repo `https://github.com/yarnpkg/yarn/releases/download/` which finally results in `https://github.com/yarnpkg/yarn/releases/download/v1.5.1/yarn-v1.5.1.tar.gz`  but also we also receive a 404 Forbidden.
