### ISSUE TITLE
Duplicate dependency when adding a pre-release package

### ISSUE THREAD

**Issue by ukabuer** [yarnpkg/yarn#5066]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
The latest release of `video.js` at npmjs.com is `6.4.0`, but I want to try a pre-release version `6.5.1`.

When I add `video.js@6.5.1` and `videojs-contrib-hls` which requires `video.js` as well, both v6.5.1 and v6.4.0 of `video.js` were installed.

The dependency tree is like this
```
app
|-- video.js@6.5.1
|-- videojs-contrib-hls
     |-- video.js@^5.19.1 || ^6.2.0
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Run
```
yarn init -y
yarn add video.js@6.5.1 videojs-contrib-hls
```
You can see `video.js@6.5.1` under `node_modules` and `video.js@6.4.0` under `node_modules/videojs-contrib-hls/node_modules`

**What is the expected behavior?**
Only version `6.5.1` be installed, just like what `npm` do.

**Please mention your node.js, yarn and operating system version.**
node v9.1.0
yarn v1.3.2
Windows 10 64 bit

**Comment by bestander** [comment]
@6.5.1 is not marked as "latest".

<img width="399" alt="screen shot 2017-12-10 at 10 31 23 am" src="https://user-images.githubusercontent.com/2121048/33808092-56a521e0-dd95-11e7-99b0-831874cbad52.png">

That is why `video.js@^5.19.1 || ^6.2.0` resolves to 6.4.0, the latest "latest".

Can be fixed by updating the tag on vide.js
