### ISSUE TITLE
Running `yarn add <package>` also updates unrelated dependencies.

### ISSUE THREAD

**Issue by dailytabs** [yarnpkg/yarn#5093]
This seems counter-intuitive. If I add a package, why is it upgrading other packages at the same time?

E.G.
    $ yarn add ng-stomp
    yarn add v0.19.1
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    [3/4] Linking dependencies...
    [4/4] Building fresh packages...
    success Saved lockfile.
    success Saved 2 new dependencies.
    ├─ angularjs-color-picker@3.2.1
    └─ ng-stomp@0.4.0
    Done in 14.53s.

Why was color picker even touched?

**Comment by rally25rs** [comment]
Can you share your `package.json`? (or just the dependencies listed in it?)
I've seen something similar reported a couple times but I can never seem to reproduce the issue...

**Comment by dailytabs** [comment]
I seem to have fixed it by re-adding the color picker with `-E`, but here is what I think it was prior to the fix:

```
  "dependencies": {
    "angular": "~1.4.12",
    "angular-animate": "~1.4.12",
    "angular-bindonce": "^0.3.1",
    "angular-cookies": "~1.4.12",
    "angular-drag-and-drop-lists": "^1.4.0",
    "angular-gridster": "^0.13.14",
    "angular-local-storage": "^0.2.7",
    "angular-prompt": "^1.2.0",
    "angular-sanitize": "~1.4.12",
    "angular-timer": "^1.3.3",
    "angular-touch": "~1.4.12",
    "angular-ui-bootstrap": "^2.1.3",
    "angular-ui-router": "^0.3.1",
    "angular-ui-validate": "^1.2.2",
    "angular-virtual-scroll-npm": "^0.6.2",
    "angularjs-color-picker": "3.2.1",
    "bootstrap": "^3.3.7",
    "detect-element-resize": "0.0.2",
    "es6-promise": "^4.0.5",
    "floatthead": "^1.4.2",
    "font-awesome": "^4.6.3",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.1",
    "gulp-concat": "^2.6.0",
    "gulp-cssnano": "^2.1.2",
    "gulp-less": "^3.3.0",
    "gulp-rename": "^1.2.2",
    "gulp-uglify": "^2.0.0",
    "gulp-uglifycss": "^1.0.6",
    "gulp-util": "^3.0.7",
    "html2canvas": "^0.5.0-beta4",
    "isteven-angular-multiselect": "^4.0.0",
    "javascript-detect-element-resize": "^0.5.3",
    "jquery": "^3.1.0",
    "jquery-masked-input": "^0.1.2",
    "jquery-ui-dist": "^1.12.0",
    "moment": "^2.14.1",
    "moment-timezone": "^0.5.5",
    "ng-infinite-scroll": "^1.3.0",
    "path": "^0.12.7",
    "restangular": "^1.5.2",
    "underscore": "^1.8.3",
    "underscore.string": "^3.3.4"
  },
  "devDependencies": {
    "gulp-angular-templatecache": "^2.0.0"
  }
```

And the yarn.lock for color picker:
```
angularjs-color-picker@^3.1.0:
  version "3.2.1"
  resolved "https://registry.yarnpkg.com/angularjs-color-picker/-/angularjs-color-picker-3.2.1.tgz#08f1ed6c57050d3260038455c19818962bf7fe0a"
  dependencies:
    angular "^1.4.0"
    tinycolor2 "^1.3.0"
```

**Comment by dailytabs** [comment]
Could someone else have upgraded/modified it, I didn't run a `yarn install` on my local, then my `yarn add` ensures it is installed? E.g. `yarn add` runs a `yarn install` alongside?

**Comment by rally25rs** [comment]
Interestingly, the package.json entry:

```
"angularjs-color-picker": "3.2.1",
```

does not match the lockfile key:

```
angularjs-color-picker@^3.1.0:
```

but that might just be there because you re-added it with `-E` _or_ someone could have edited it by hand.

I can reproduce the same output you see if I manually edit a version in package.json but not run an `install`. Then do a `yarn add` and it also installs the "missing" item that no longer matches the lockfile. So it's possible that someone had edited that file, or perhaps updated it with `npm` instead of `yarn`.

In the Yarn code, the "add" command extends "install" (in the object-oriented sense) so a lot of "install" behavior happens when adding packages too. I think this check is one of those things.

**Comment by dailytabs** [comment]
Ok, that sounds reasonable. I think I would prefer a warning that my install is out of date, rather than it just doing it. But, good enough. Will close. You can re-open if you think there is anything that can/should be done. Thanks for your time.

**Comment by qkreltms** [comment]
I think It still updates other packages when you manually modify package.json.
I was be able to fix this issues by moving to npm

**Comment by felipenmoura** [comment]
well...I see that happening now (2022)...should it be doing that?
I ran
`yarn add some-public-package`
And it is failing because it can't authenticate to my github repo to load some private dependencies.
I just added my token to a .npmrc file ant it worked, but still...why was it even trying to access that private repository when I simply added a new dependency?

I'm guessing here, that the reason is because yarn does that to look for peer or conflicting dependencies in other dependencies, but it is still very counter-intuitive, anyways.
