### ISSUE TITLE
BUG: yarn incorrectly names packages with . in the path

### ISSUE THREAD

**Issue by utdrmac** [yarnpkg/yarn#5102]
**Do you want to request a *feature* or report a *bug*?** BUG
**What is the current behavior?**
```
$ yarn add scottoffen/jquery.toaster
yarn add v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ jquery@0.0.0
✨  Done in 2.22s.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
See above. 
```
$ ls -la node_modules/jquery/
total 88
drwxr-xr-x    9 drmac  staff    306 Dec 17 19:36 .
drwxr-xr-x  190 drmac  staff   6460 Dec 17 19:36 ..
-rw-r--r--    1 drmac  staff      1 May 12  2017 .gitignore
-rw-r--r--    1 drmac  staff    582 May 12  2017 LICENSE
-rw-r--r--    1 drmac  staff  11389 May 12  2017 README.md
-rw-r--r--    1 drmac  staff    541 May 12  2017 bower.json
-rw-r--r--    1 drmac  staff   5012 May 12  2017 index.html
-rw-r--r--    1 drmac  staff   4740 May 12  2017 jquery.toaster.js
-rw-r--r--    1 drmac  staff   1147 May 12  2017 toaster.jquery.json
```

**What is the expected behavior?**
The expected behavior is that yarn ignore the '.' when naming packages. This is clearly not jquery, but a jquery plugin that is poorly named.

Even attempting shell escape `yarn add scottoffen/jquery\.toaster`, produces the same result.

**Please mention your node.js, yarn and operating system version.**
macos
$ node --version
v9.3.0
$ yarn version
yarn version v1.3.2
info Current version: 1.0.3

**Comment by iansu** [comment]
I've been able to verify this bug but it seems to be something other than (just) the . in the name. For example, the package `ipaddr.js` installs just fine. It looks like this package is coming from GitHub and also has no `package.json` file. It's definitely still a bug but there's more going on here.

**Comment by rally25rs** [comment]
I'd argue that you aren't installing a Node library, because there is no `package.json` file. This isn't a valid package so behavior is a bit ... "undefined".

I think if the `package.json` is missing, then Yarn tries to guess at a package name and version. It's probably blindly truncating the "extension" because `account/repo.git` is also a valid URI, and they can also end with `.tar` or `.tar.gz`. All of these need the stuff after the `.` trimmed.

If someone wants to tackle this, the logic is in `src/util/guess-name.js` and there are tests in `__tests__/util/guess-name.js`

**Comment by iansu** [comment]
I'll take a look at it now that I know where to look.
