### ISSUE TITLE
yarn keeps hanging while downloading node-sass cause of invalid url. Do you guys have any solution?

### ISSUE THREAD

**Issue by janiele2109** [yarnpkg/yarn#5132]
![2017-12-28_235952](https://user-images.githubusercontent.com/19186353/34417654-34d8d908-ec2c-11e7-90c7-21e2db17791d.jpg)

**Comment by rally25rs** [comment]
If I try to install `node-sass` it downloads the file after a couple seconds then finishes. That download is part of [that package's custom install script](https://github.com/sass/node-sass/blob/master/scripts/install.js), so you might want to report the issue there if it persists. There is nothing Yarn can do since that install script is not under our control.
