### ISSUE TITLE
Yarn not resolving version correctly

### ISSUE THREAD

**Issue by kyleholzinger** [yarnpkg/yarn#5324]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Yarn installs the wrong version of a dependency if another dependency depends on a later version of that library.

**If the current behavior is a bug, please provide the steps to reproduce.**

If you depend on library `A` that depends on library `B@2.0.0` and then manually add library `B` with a specific version with `yarn add B@1.0.0`, it still installs library `B` with version `2.0.0`. [Here's a repo](https://github.com/kyleholzinger/yarn-bug) where I reproduced the issue with jquery as library `B` and jquery-ujs as library `A`. The strange thing is that if you go into the yarn.lock file and remove the old version resolution manually, and _then_ run `yarn install`, it'll correctly identify that it should install library `B` with version 1.0.0. 

**What is the expected behavior?**
It installs library `B` with version 1.0.0

**Please mention your node.js, yarn and operating system version.**
Node version 6.9.5
Yarn version 1.1.0 (but I checked and it still exists on 1.3.2)
OS version macOS 10.13.3

**Comment by bestander** [comment]
The problem is that `jquery@>=1.8.0` gets resolved to "3.3.1"
```
jquery@>=1.8.0:
  version "3.3.1"
  resolved "https://registry.yarnpkg.com/jquery/-/jquery-3.3.1.tgz#958ce29e81c9790f31be7792df5d4d95fc57fbca"
```

Which looks like a correct behavior of semver https://semver.npmjs.com/.


If you switch to the same version ">=1.8.0" in your top level project then they should resolve to the same one.

I don't think Yarn can do anything here

**Comment by kyleholzinger** [comment]
@bestander Hm well there has to be a bug somewhere, cause if you remove the `yarn.lock` file and install them all at once, it resolves to the earlier version of jquery, not the "incorrect" version of 3.3.1. I feel like one way or the other is a bug? Or is that the intended behavior

**Comment by bestander** [comment]
I think the dedupe mechanism could be improved but I don't think that current behavior is a bug.

Here is my line of thinking.
1. If you already had a locked version of `jquery@>=1.8.0 -> jquery@3.x` as subdependency yarn should not downgrade to `jquery@1.12.0` if you add it at top level.

2. If you have `jquery@1.12.0` as top level dependency and and then add `jquery@>=1.8.0` Yarn should pick `jquery@1.12.0` because it is already available.

(1) is up to debate, I think it would be awesome to have a flag that would optimize dependency tree even downgrading resolutions.

If you feel strong about it send a PR, it would be welcome

**Comment by kyleholzinger** [comment]
Ahh I see, so if you have it already locked in, adding it as a top level dependency will not downgrade, interesting. Sounds good, I'll dig into adding a flag for that optimization. Thanks!
