### ISSUE TITLE
v1.5.0 release info?

### ISSUE THREAD

**Issue by dlong500** [yarnpkg/yarn#5408]
Why is there a v1.5.0 release with no information or asset section?  Is this a mistake?

**Comment by jure** [comment]
I guess something's funky with the build infrasctructure. There definitely used to be information about the release (it was not a pre-release) when it first appeared 3 days ago, which a few days later became a pre-release, Google cache shows this:
![image](https://user-images.githubusercontent.com/238667/36652435-ac4659f4-1aa6-11e8-93c7-b26b52d721e5.png), and has now, as you have noticed, disappeared almost completely.

I think something went wrong with the builds, resulting in the website not being updated (https://github.com/yarnpkg/website/pull/783), homebrew not being updated (https://github.com/Homebrew/homebrew-core/pull/24471) and npm not being updated (even though this wasn't a pre-release, npm's `latest` tag still points to 1.3.2). You can still install it with `npm install -g yarn@1.5.0` or with the shell script `curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.0`, but given the current lack of information about the release, which is surely intentional, perhaps it's best to wait it out.

**Comment by Daniel15** [comment]
The Windows build is failing (https://ci.appveyor.com/project/kittens/yarn/build/4862), so the release is incomplete. @arcanis could you please follow up on it? Let me know if you need help :)

**Comment by Daniel15** [comment]
Pushed v1.5.1, which is identical to v1.5.0 but contains a fix for the test that was failing on Windows.

**Comment by rarkins** [comment]
There still seems to be some discrepancies in the versions available.

Yarn website shows v1.3.2 as stable and v1.5.1 as RC:
![image](https://user-images.githubusercontent.com/6311784/36718481-3d104520-1ba2-11e8-95a9-16e8d3cd07b8.png)

npmjs shows v1.5.0 as latest:
![image](https://user-images.githubusercontent.com/6311784/36718497-4c4c991c-1ba2-11e8-8d13-4eebcdd70539.png)

`brew upgrade yarn` installs v1.3.2

**Comment by Daniel15** [comment]
I guess 1.5.x is supposed to be stable, and someone manually bumped it on
npm but not elsewhere. I'll fix it.
