### ISSUE TITLE
How to install Yarn with pacman without installing nodejs

### ISSUE THREAD

**Issue by msudgh** [yarnpkg/yarn#5523]
I'm using [**`n`**](https://github.com/tj/n) and I want to install **`Yarn`** without installing the Node.Js dependency.
How can I resolve this problem?

**Comment by rally25rs** [comment]
Node is required for Yarn to execute, but you should be able to install Yarn on your system even if Node isn't there by using the curl & bash combination or manually from a downloaded tarball:

```
curl -o- -L https://yarnpkg.com/install.sh | bash
```

which are listed in the ["alternative" installation](https://yarnpkg.com/en/docs/install#alternatives) options.

(closing this issue, since I think this answers your question. If it does not, then leave a comment and we can re-open this.)
