### ISSUE TITLE
outdated command doesn't always report new beta versions correctly

### ISSUE THREAD

**Issue by ngyikp** [yarnpkg/yarn#5668]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Given this package.json:

```json
{
  "dependencies": {
    "@babel/core": "7.0.0-beta.43",
    "@storybook/cli": "4.0.0-alpha.0",
    "babel-loader": "8.0.0-beta.0"
  }
}
```

Running `yarn outdated` doesn't report any new versions for `babel-loader` or `@storybook/cli`:
```
$ yarn outdated
yarn outdated v1.6.0
Package     Current       Wanted        Latest        Package Type URL                
@babel/core 7.0.0-beta.43 7.0.0-beta.43 7.0.0-beta.44 dependencies https://babeljs.io/
✨  Done in 1.53s.
```

**What is the expected behavior?**
I should see updates for `@storybook/cli` to `4.0.0-alpha.2` and `babel-loader` to `8.0.0-beta.2`.

`npm outdated` does report about the outdated versions, albeit confusing:

```
$ npm outdated
Package               Current         Wanted         Latest  Location
@babel/core     7.0.0-beta.43  7.0.0-beta.43  7.0.0-beta.44
@storybook/cli  4.0.0-alpha.0  4.0.0-alpha.0          3.4.1
babel-loader     8.0.0-beta.0   8.0.0-beta.0          7.1.4

$ npm -v
5.6.0
```

Might be somewhat related? https://github.com/yarnpkg/yarn/issues/2691

**Please mention your node.js, yarn and operating system version.**
Tested on both Yarn version 1.5.1 / 1.6.0
Node.js v8.11.1
macOS 10.13.4

**Comment by rally25rs** [comment]
Although a bit confusing, the output is actually correct. Hopefully this explanation helps clear it up...

The column `Wanted` is the newest version that matches your requested semver range according to your package.json file.

The column `Latest` is the version actually tagged as `latest` in the registry.

-----

Your package.json has _exact_ version ` "@babel/core": "7.0.0-beta.43"`
So yarn will always show `Wanted` as the same exact version that you wanted (since there is no range). For `Latest` the registry actually has `7.0.0-beta.44` tagged as latest:

```
$ yarn info @babel/core | grep latest
   { latest: '7.0.0-beta.44' },
```

Since `7.0.0-beta.44` is greater than your currently installed `7.0.0-beta.43`, it outputs that package as outdated.

-----

Now let's look at `"babel-loader": "8.0.0-beta.0"`

`Wanted` is `8.0.0-beta.0` and `latest` according to the registry is `7.1.4`. Neither of these is greater than your current version of `8.0.0-beta.0` so the package is not reported.

-----

What you might want to do is change your versions in package.json to use ranges, like `"@babel/core": "~7.0.0-beta.43"` which will then report the newest beta version in the requested range.

Hopefully that helps clear up the output you are seeing. What might be a nice addition to yarn at some point is to add a flag that would report versions newer than `latest` (include beta and RC versions that are in the future) but unfortunately that isn't available right now. We may want to clear up those column titles too, but it's hard to pick a word or 2 that perfectly describes what the column represents.
