### ISSUE TITLE
yarn 1.6.0 breaks script-shell multiple commands

### ISSUE THREAD

**Issue by aikar** [yarnpkg/yarn#5699]
yarn config set script-shell bash

package.json:

  "scripts": {
    "foo": "echo foo; echo bar";
  }

run yarn foo

expected:
>>> yarn foo
yarn run v1.6.0
$ echo foo; echo bar
foo
bar
Done in 0.06s.

received:
>>> yarn foo
yarn run v1.6.0
$ echo foo; echo bar
bash: echo foo; echo bar: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

This worked pre 1.6.0 and helps keep stuff working consistently between windows and linux and needs to be supported.

**Comment by arcanis** [comment]
Which node version are you running ?

**Comment by aikar** [comment]
8.11.1

**Comment by arcanis** [comment]
Hm that's really weird - it seems like the command being run is `"echo foo; echo bar"` instead of `"echo" "foo"; "echo" "bar"`. If it was really the case, our tests would be screaming like crazy (plus it would break even without multiple commands).

The only case I'm aware where this could happen is if you're running with an unsupported 4.X Node version (which doesn't support the `shell: true` option), but if that's not the case, then I have no clue ...

**Comment by aikar** [comment]
did you set the script shell to 'bash'?

Also worth noting, Linux Mint 18.3

**Comment by aikar** [comment]
and I had installed using the yarn installer script.

**Comment by rally25rs** [comment]
Has nothing to do with multiple commands. `"foo": "echo foo"` fails with the same error.
This looks like `script-shell` is just broken. _(insert rant on why `script-shell` is a terrible idea 😠)_

Yarn is trying to execute the command `bash "echo foo"` which causes the same error

```
~/Projects/yarn-test 🐒   bash "echo foo"
bash: echo foo: No such file or directory
```

This looks like it was caused by https://github.com/yarnpkg/yarn/pull/5484 @BYK

**Comment by BYK** [comment]
Thanks for the quick diagnosis @rally25rs!

I think we can just use the shell option. I don't know why I haven't done it that way when I was refactoring. I'll test in on Windows when I get to my computer.

**Comment by aikar** [comment]
@BYK sounds like solution is known, when will this be fixed?

**Comment by kostiako** [comment]
I can't make heads or tails out of yarn's codebase, otherwise would gladly fix this.
Since this is currently rendering my whole Windows env useless.

Anyone?

**Comment by rally25rs** [comment]
I created PR #5851 if you want to test it out.
