### ISSUE TITLE
registry setting forces https

### ISSUE THREAD

**Issue by juliangruber** [yarnpkg/yarn#5732]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

If you set the registry to `http://localhost:8000` and install package `name`, it will first

```
GET http://localhost:8000/name
```

then

```
GET https://localhost:8000/name/-/name-version.tgz
```

Note, it switched to `https` protocol on its own.

**What is the expected behavior?**

It shouldn't switch the asset url to `https` on its own.

**Please mention your node.js, yarn and operating system version.**

- node: 9.0.0
- yarn 1.6.0
- os: mac OS 10.13.4

**Comment by rally25rs** [comment]
Sorry for the delayed response. Didn't get to finish digging through code yesterday. According to this chunk:

https://github.com/yarnpkg/yarn/blob/master/src/resolvers/registries/npm-resolver.js#L216-L218
```
      info._remote = {
        resolved: `${this.cleanRegistry(dist.tarball)}#${dist.shasum}`,
        type: 'tarball',
        reference: this.cleanRegistry(dist.tarball),
        hash: dist.shasum,
        registry: NPM_REGISTRY_ID,
        packageName: info.name,
      };
```

cleanRegistry is:

```
  cleanRegistry(url: string): string {
    if (this.config.getOption('registry') === YARN_REGISTRY) {
      return url.replace(NPM_REGISTRY, YARN_REGISTRY);
    } else {
      return url;
    }
  }
```

(returns the same URL that it is passed, when a custom registry is used.)

so we basically just take `dist.tarball` from the metadata and swap npmjs.org for yarnpkg.org when no custom registry is being used, which is what I was getting at in my initial reply (we use what the registry gives us)

however, I'm pretty sure there is a difference when the package is already cached. If the package has already been downloaded and cached, then we will use whatever is in the cache instead of re-querying the registry. If the package had been installed over https once, then it could have the https url in the cache. You might want to try `yarn cache clean name` where `name` is the name of your package.

**Comment by juliangruber** [comment]
sorry, this was a bug on my end, it _did_ have the https in the tarball url. Sorry for your time, but also thank you a lot for investigating :)
