### ISSUE TITLE
(node:3184) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues.

### ISSUE THREAD

**Issue by aamorozov** [yarnpkg/yarn#5770]
**Do you want to request a *feature* or report a *bug*?**

I don't think it's a bug but might be good to resolve it in the future. 
**What is the current behavior?**
The deprecation warning is thrown when installing a package with `yarn add` and node >= 10.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
No deprecation warnings. 
**Please mention your node.js, yarn and operating system version.**

macOS High Sierra, version 10.13.4
Node v. 10
Yarn v. 1.6.0

**Comment by MrCheater** [comment]
+1

**Comment by simonkberg** [comment]
This is already being tracked in #5477

**Comment by denisinla** [comment]
So we need to revert to using npm for projects until this is complete right? I get reminded of said error via yarn but not with npm. But all packages fail to install via yarn.

**Comment by simonkberg** [comment]
@deisinla if packes fail to install you're having some unrelated issue, although you will still see this warning if you're using Node 10 which might be confusing. This is a _deprecation warning_ in Node, the old API is still present and works like before.

I suggest you open a separate issue discribing your error (and include the error log), this issue will most likely be closed since it's a dupe.

**Comment by aamorozov** [comment]
👍

**Comment by AbhimanyuAryan** [comment]
How to fix this?

**Comment by aleph1ow** [comment]
I got this problem too after trying to install `Inkscape` via brew and uninstalling it because brew fails to install some dependencies.
- Mac OS 10.13.4
- node v10.1.0
- yarn 1.6.0

**Comment by Stahlion** [comment]
+1
Mac OS 10.13.4
node 10.1.0
yarn 1.6.0

**Comment by derekbtw** [comment]
+1

Windows 10 v1803
node v10.1.0
yarn v1.6.0

`$ yarn run dev`

`(node:14480) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

**Comment by wachunei** [comment]
This is showing up a lot recently. The fix is already committed to master, just wait for a new release https://github.com/yarnpkg/yarn/issues/5477

**Comment by zwhitchcox** [comment]
Does anyone know how to install this version? with a fresh install, this is still happening fo rme

**Comment by zwhitchcox** [comment]
It looks like the nightly msi version is broken, as it installs a different version of yarn than it says it's downloading: https://yarnpkg.com/en/docs/install#windows-nightly

It says it's installing 1.10.0, but installs 1.9.0

**Comment by zwhitchcox** [comment]
Idk, maybe I'm just still having the same problem...this is my console output

$ yarn
yarn install v1.9.0-20180706.1017
warning package-lock.json found. Your project contains lock files generated by tools other than
 Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies c
aused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[-------------------------------------------------------------------------------------] 0/1449(
node:11232) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability
issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error inotify@1.4.2: The platform "win32" is incompatible with this module.

**Comment by zwhitchcox** [comment]
Ok, it worked when I `npm install yarn@latest`.

**Comment by samuelcastro** [comment]
Just `brew update yarn`

**Comment by xuyuheng** [comment]
+1

**Comment by shirshak55** [comment]
still same :( why do even such minor issue don't get fixed . Really hate those irritating warning

**Comment by axelkennedal** [comment]
I'm also getting this error with the latest version of Yarn (1.9.4)

**Comment by DarrenClyde** [comment]
+1 (1.9.4)

**Comment by akeuk** [comment]
still warning on yarn 1.9.4

**Comment by manu-st** [comment]
And in 1.10.0 too.

**Comment by Norbert1001001** [comment]
Having the same issue with node > 10 and angular-cli 6.2.0. No yarn installed or used.

**Comment by isaiahdavisx** [comment]
I am having this issue in vs code with the following specs:
Windows 10
yarn@1.13.0
npm@6.7.0

If there is anyone that could help it would be immensely appreciated. I do not have a strong development background I am trying to set up a debug environment. Thanks.
