### ISSUE TITLE
`yarn` tries to execute `node.js` script on Windows

### ISSUE THREAD

**Issue by azasypkin** [yarnpkg/yarn#5777]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If you open folder that contains `node.js` file (literally name is `node`, extension is `.js`, it's configuration file in our project) and run `yarn`, windows will try to execute/open that file with `Windows script host` app. 

**If the current behavior is a bug, please provide the steps to reproduce.**

See steps above. Just put `node.js` file in any directory and run `yarn` there. It's Windows only problem, `npm i` also works fine. We can obviously workaround this issue by renaming `node.js` to something like `node-configuration.js`, but yarn behavior on Windows still feels wrong.

**What is the expected behavior?**

`yarn` should not depend on names of the scripts located in the working directory.

**Please mention your node.js, yarn and operating system version.**

NodeJS 8.11.1, yarn 1.6.0, Windows 10 Home 1709/16299.309

**Comment by rally25rs** [comment]
This is a Windows oddity. `yarn.cmd` calls `node` which Windows then decides to run the local `node.js` because it for some reason thinks that is executable and takes priority in the path. Interestingly, just running `node` in that directory directly resolves to actual Node JS executable, but when run through a `.cmd` or `.bat` file, `node` gets mapped to `./node.js`

This is actually broken in `npm` too, with a different error message.

```
C:\Projects\yarn-test> npm
Sorry, there's a problem with nodist.
Error:  fork/exec .\node.js: %1 is not a valid Win32 application.
```

-----

You can actually reproduce this in just windows scripts:

node.js
```
console.log('cool');
```

foo.bat
```
node -v
```

```
C:\Projects\yarn-test> node -v
v5.12.0

C:\Projects\yarn-test> .\foo.bat

C:\Projects\yarn-test>node -v
{{ Windows Script Host error popup happens }}
```

then run `./foo.bat` and it will try to execute your `./node.js` not actual Node.

-----

Windows... 😿 Anyway, I don't think there is much we can do to fix this. It just seems to be some oddity about how Windows decides what to run for commands in `.bat` and `.cmd` files.

_(but if someone does find a solution, submit a PR!)_

**Comment by rally25rs** [comment]
Just noticed you said `npm` works for you. It doesn't for me. Wonder what the difference is... 😕

**Comment by azasypkin** [comment]
By the way if you install yarn as a global node module `npm install -g yarn` then everything works as expected. I see that `yarn.cmd` installed with `npm install -g yarn` and the one created when `yarn` is installed via `Chocolatey` are different, but didn't dig too much to see where the difference is. Do you know anything about that @rally25rs ?

**Comment by rally25rs** [comment]
I think in the case of `npm -g` npm makes a link to the `yarn.js` file, bypassing the .cmd file. I don't have my Win machine in front of me, but on OSX anyway, the created npm symlink is:

```
/Users/jvalore/.nvm/versions/node/v8.10.0/bin/yarn -> ../lib/node_modules/yarn/bin/yarn.js
```

In the case of Choco, I'm not sure. I don't know why it would be any different. I think it just downloads and runs the `.msi` installer https://github.com/yarnpkg/yarn/blob/master/resources/win-chocolatey/tools/chocolateyinstall.ps1.in
