### ISSUE TITLE
Hi i'm color Color blindness

### ISSUE THREAD

**Issue by Loyide** [yarnpkg/yarn#5800]
i'm color blindess so when use yarn outdated 

I can't distinguish the difference between green and yellow

```
 yarn outdated
yarn outdated v1.6.0
info Color legend :
 "<red>"    : Major Update backward-incompatible updates
 "<yellow>" : Minor Update backward-compatible features
 "<green>"  : Patch Update backward-compatible bug fixes
```

**Comment by rally25rs** [comment]
Hi @Loyide 👋 Pardon my lack of knowledge with this particular accessibility concern, but is there a better color combination that you can recommend? We use [chalk.js](https://github.com/chalk/chalk) so the other color options can be viewed there.

I also believe the "yellow" and "green"  come from the color settings of your terminal, so changing color settings there might be another more universal approach that would cover other applications that use colored output.

In this particular case the colors are just a secondary indicator of which digit in the semver (major, minor, patch) is different, and that information is also communicated by displaying the actual semver ranges themselves, so I hope this hasn't prevented you from using `upgrade-interactive`.

I'll mark this as a feature request to improve accessibility. Thanks for your feedback!

**Comment by Loyide** [comment]
For people like me, red, yellow and blue are much better combinations than
 red, yellow, and green combinations.

So I would like to recommend the blue family!

For your information
There are many kinds of color blindness. 
Some of them can not distinguish between green and yellow.
So the colors of the traffic lights can be confusing.

Thank you for your feedback!
Have a great day!

**Comment by sth** [comment]
I feel green intuitively conveys "should cause no problems when upgrading", much more so than blue. So isn't green in general the better color for this?

How the colors actually look is very much dependent on the terminal you use (light or dark background, color scheme). Usually that can be configured by the user (though I don't know if it is possible on windows). Also there are different kinds of color blindness where different pairs of color are hard to distinguish.

Wouldn't it be a much better solution for the user to configure their terminal with a color scheme that is accessible by them? That would not only fix their problems for this yarn command, but for all terminal programs.

**Comment by BYK** [comment]
>Wouldn't it be a much better solution for the user to configure their terminal with a color scheme that is accessible by them? That would not only fix their problems for this yarn command, but for all terminal programs.

As a [deutan](http://www.color-blindness.com/deuteranopia-red-green-color-blindness/) myself I can totally relate to the author. That said since there are other types of color blindness, especially ones like [tritanopia](http://www.color-blindness.com/tritanopia-blue-yellow-color-blindness/) who would actually suffer from a change like #5829, I think the best is to leave this to the end user's terminal color settings.

What do you think @Loyide and @ohbarye?

**Comment by ohbarye** [comment]
@sth @BYK 
Thanks for your opinion!

I first thought my change saves someone who feels isolated from the world due to lack of consideration of them. And yarn would be a more accessible tool for more people. But I didn't know it causes another issue and there seems no perfect solution for everyone.

I'm not color blindness, it means that I cannot totally understand how/what you feel on yarn's color selection. So if insiders, like you, say that's okay, I entirely respect your voice. 👍 

Feel free to close #5829 !

**Comment by BYK** [comment]
Since I haven't heard much from anyone else, I'll go ahead and close this issue along with the pull request. Thanks a lot for raising awareness about this and all the effort!

**Comment by milesj** [comment]
I looked into something like this for another project of mine. I ended up going with themes (through something like `--theme`) instead of specific color blindness support. https://github.com/milesj/boost/blob/master/src/themes.ts 

You can then use the hexcodes directly with chalk: https://github.com/milesj/boost/blob/master/src/Reporter.ts#L433 This feature does require true color support in the terminal however.

For all other instances where this isn't possible, it should probably be up to the users terminal settings.
