### ISSUE TITLE
yarn upgrade & yarn add didn't update sub deps

### ISSUE THREAD

**Issue by bluelovers** [yarnpkg/yarn#5822]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

i install a `dep1`

`dep1@^1.0.4`
├─ `dep2@^1.0.4`

after installed, then `dep2` has a new verison `1.0.6`

* `yarn upgrade`
* `yarn add dep1`

can't update `dep2` to new version

also try delete `yarn.lock` and run `yarn`

but `dep2` still is `1.0.4`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

update `dep2` to `1.0.6` without add to `package.json` `dependencies` or `resolutions`   
because it is sub dep of `dep1`

**Please mention your node.js, yarn and operating system version.**

yarn 1.6.0

**Comment by rally25rs** [comment]
It is working like this because:

`yarn upgrade` and `yarn upgrade-interactive` use `yarn outdated` to decide what can be upgraded, which only considers your direct dependencies. Since `dep1` doesn't have an update, it considers nothing to be outdated.

Not sure if this is really a bug, or just one of those things where everyone wants `upgrade` to work a different way. (only direct deps, or all deps. Upgrade transitive subdeps, or not). We could try to make various commands of flags to fit every possible use case, but I'm not sure we should change how it works currently since some users already rely on the way it currently works.

Although, I would have expected deleting `yarn.lock` to then pull the newer version, since it would not longer find a locked version. 🤔 Maybe try `rm -rf node_modules yarn.lock && yarn install` ? It might be finding the existing version in node_modules and deciding there is nothing to do?

**Comment by dmngu9** [comment]
+1

**Comment by bluelovers** [comment]
still wanna this, and not use `rm -rf node_modules `
