### ISSUE TITLE
Move to yargs

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/yarn#5871]
The Yarn command line is currently using Commander, which require us to basically reimplement a command-line manager on top of Commander itself to do everything we want. It would be better if we could remove this part of the codebase.

One issue we might have is with `yarn run` and `yarn node`, which automatically forward their arguments without requiring the `--` segment. It's pretty handy, so it would be interesting to preserve this behavior if possible.

**Comment by rally25rs** [comment]
see: #3408

**Comment by Aghassi** [comment]
Has the team considered any other options? I'm curious because while yargs is great, for larger projects we have been playing around with [Oclif](https://oclif.io) and have really been enjoying it. The speed and auto doc generation is definitely a plug. It also sports a plugin architecture so it allows for extensibility if you so choose. It would mean that parts of the Yarn system to be split into smaller packages and then recomposed into the CLI that people use. It's a thought, but one I figured is worth asking if there is a large move in place.

**Comment by paul-soporan** [comment]
Hello from the future, we're using https://github.com/arcanis/clipanion in Yarn 2+ and we're very satisfied with it.

https://yarnpkg.com/getting-started/migration
