### ISSUE TITLE
Yarn upgrade installs old dev version of UIkit framework

### ISSUE THREAD

**Issue by AndZyk** [yarnpkg/yarn#6319]
**What is the current behavior?**

`yarn upgrade` installs old dev version **uikit@3.0.0-rc.9-dev.bd39d353** of [UIkit](https://github.com/uikit/uikit) framework.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. `yarn add uikit`
2. `yarn upgrade`

**What is the expected behavior?**

Update to the lastest stable version of UIkit.

**Please mention your node.js, yarn and operating system version.**

- Node v10.9.0
- Yarn 1.0.0-20170817.1516
- MacOS 10.13.6

**Comment by cmawhorter** [comment]
yarn 1.0.0? the latest is 1.9.4.  try upgrading yarn?

**Comment by AndZyk** [comment]
Sorry, my mistake. I use version 1.9.4 installed via homebrew.

Cleaning the cache doesn't help.

Upgrading with `npm upgrade` works as expected.

This is off-topic, but I was wondering if it is good to add packages and then to always upgrade with `yarn upgrade` or if it is better to upgrade to specific versions of packages with `yarn add package@1.0.x`?

**Comment by cmawhorter** [comment]
i always use `yarn upgradeInteractive` myself.  

what is the version in package.json for uikit? if it's exact e.g. `"uikit": "3.0.0-rc.9"` (with no `^`), then yarn will not upgrade it by design.  Even with `yarn upgrade uikit`.

i'm having my own issues around yarn misbehaving around upgrades.  for me, the issues are largely around git deps and even child dependencies of npm deps. My workarounds have been:

1. First try: `rm -fr ./node_modules; yarn`
1. If that doesn't work: Edit package.json and remove the entry for the problem dependency. then `yarn && yarn add [problem dep]`
1. Nuclear option: `rm -fr ./node_modules; rm yarn.lock; yarn cache clean; yarn`

I've even taken to hand patching yarn.lock since 1.9.4. 😢

**Comment by AndZyk** [comment]
The version in the package.json is `"uikit": "^3.0.0-rc.12"`. So it should only upgrade if there is a newer version available. But when I run `yarn upgrade` it shows:

`[1/4] 🔍  Resolving packages...`
`warning uikit@3.0.0-rc.9-dev.bd39d353: wrong`
`[2/4] 🚚  Fetching packages...`
`[3/4] 🔗  Linking dependencies...`
`[4/4] 📃  Rebuilding all packages...`
`success Saved lockfile.`
`success Saved 1 new dependency.`
`└─ uikit@3.0.0-rc.9-dev.bd39d353`

So Yarn knows, that this upgrade is wrong, but upgrades it anyway.

On some of my machines it worked as expected. Maybe there is something cached anywhere. But `yarn cache clean` didn't helped.

But thank you for mentioning the command `yarn upgrade-interactive`. I didn't knew about that one but will use it in the future instead of `yarn upgrade` to have more control. 👍

**Comment by AndZyk** [comment]
I have finally found out my issue: Somehow I managed to install Yarn two times on my machine. One time under my user and one time with homebrew. Uninstalling both installations and installing it again with homebrew solved this issue.
