### ISSUE TITLE
PR: Enable Travis an Appveyor CI tests

### ISSUE THREAD

**Issue by amilajack** [yarnpkg/yarn#632]
Would love to make a PR for this, if it would be welcome

**Comment by kittens** [comment]
We currently have this setup, although we have a few failing tests that are intermittent due to CI troubles. Happy to accept any PRs improving this!

**Comment by amilajack** [comment]
Oh I see. From what I saw, it seems like the tests [aren't](https://ci.appveyor.com/project/yarnpkg/yarn/branch/master) [enabled](https://travis-ci.org/yarnpkg/yarn).

**Comment by BanzaiMan** [comment]
Probably due to data sync timing, the builds have not been running on https://travis-ci.org/yarnpkg/yarn.

**Comment by BanzaiMan** [comment]
Someone with the admin privilege still needs to enable Travis CI.

**Comment by amilajack** [comment]
<img width="684" alt="screen shot 2016-10-11 at 1 51 30 pm" src="https://cloud.githubusercontent.com/assets/6374832/19288201/d412be38-8fb9-11e6-905a-6dfe746908a8.png">

Seems like travis was configured but not enabled

**Comment by BanzaiMan** [comment]
@amilajack You'd notice that the link to Travis goes to https://travis-ci.com. It was configured on .com (because it was private until today), and the PR build request has gone there before data were sync'd recently (which is scheduled in the background at 24-hour intervals).

New PRs will not run on Travis CI until it is enabled on .org.

**Comment by BanzaiMan** [comment]
It's running now.
