### ISSUE TITLE
[Bug]Yarn Plug n Play not working for node-addon-api

### ISSUE THREAD

**Issue by gengjiawen** [yarnpkg/yarn#6524]
yarn install failed for node-addon-api.
repro: https://github.com/nodejs/abi-stable-node-addon-examples/blob/master/1_hello_world/node-addon-api/package.json.

node 10, yarn 1.12.0, macOS 10.14

**Comment by arcanis** [comment]
This is due to `node-bindings` using a [regexp on the error message](https://github.com/TooTallNate/node-bindings/blob/master/bindings.js#L87) (which doesn't match the error message thrown by PnP, since we embed contextual information that the Node resolution cannot have).

cc @TooTallNate? Would you accept a PR that would instead check that the `code` property from the exception is amongst a known list (regular Node exceptions throw `MODULE_NOT_FOUND`, in this case you'd be interested in `QUALIFIED_PATH_RESOLUTION_FAILED`)?

**Comment by armenr** [comment]
We're hitting this same issue.

**Comment by gengjiawen** [comment]
Fixed via https://github.com/TooTallNate/node-bindings/pull/56
