### ISSUE TITLE
Compatibility pnp mode

### ISSUE THREAD

**Issue by sunflowerdeath** [yarnpkg/yarn#6530]
**Request of feature**

Currently, many packages (like react components or webpack plugins) do not have correct peer dependencies. Because of this, pnp mode does not work. Until all these packages are fixed, it would be useful to have a mode in which you can allow them to require direct dependencies of the parent. Also, this mode can provide warnings, to help fix missing peer dependencies.

**Comment by arcanis** [comment]
As you might have noticed since you've closed this issue, we have a fallback mechanism where we first check the top-level dependencies if a require call cannot be resolved. If the require would work with a dependency provided by the top-level, then we allow it.

Doing this based on the parent cannot be done without breaking the tree (it's a bit complex to explain why in a few words, but the gist is that it would prevent every package from being deduplicated). The top-level is the only package in the tree that allows us to do this kind of thing safely.
