### ISSUE TITLE
Migrate lock file to workspace root

### ISSUE THREAD

**Issue by borekb** [yarnpkg/yarn#6563]
I've migrated our monorepo from separate packages to Yarn workspaces with a single central `yarn.lock` file. During the migration, I did this for each package:

1. Added it as a workspace in the root `package.json` file.
2. Ran `yarn`, observed that the root `yarn.lock` file updated with new dependencies.
3. Deleted package's `yarn.lock` file

It all seemed to work fine but later, I was encountering subtle issues at runtime. So I checked and the locked versions were actually different. For example, the original package-local `yarn.lock` file:

```
underscore@^1.8.3:
  version "1.8.3"
  resolved "https://registry.yarnpkg.com/underscore/-/underscore-1.8.3.tgz#4f3fb53b106e6097fcf9cb4109f2a5e9bdfa5022"
```

Central lock file:

```
underscore@^1.8.3:
  version "1.9.1"
  resolved "https://registry.yarnpkg.com/underscore/-/underscore-1.9.1.tgz#06dce34a0e68a7babc29b365b8e74b8925203961"
```

This specific change was breaking the app. Was my workflow incorrect? How should I approach this?

**Comment by Gudahtt** [comment]
I don't know of a straightforward way of "merging" lockfiles in the manner you are describing. In your example, the workspace `yarn.lock` file was not being used.

That might make for a useful feature, though I'm not exactly sure how it would work. How would it know which differences in versions were incidental, and which were meaningful? That type of information should be in the `package.json` file. In your example, if `underscore@1.9.1` breaks the app, then you should update the `package.json` file to prevent that version from being used (e.g. change the version range to `~1.8.3` instead of `^1.8.3`). That information has to exist somewhere.

That said, merging separate packages into a single workspace is a major change, and is as good a time as any to update the lockfile. Presumably you would eventually want to update your dependencies. I'd suggest taking this opportunity to see what works and what doesn't, and update your `package.json` file accordingly.

**Comment by arcanis** [comment]
This feature goes against a core principle in Yarn, so I can say right now that we can't implement what you have in mind 🙂

Yarn simply doesn't allow multiple identical ranges to have different possible resolutions. And this "one range = one resolution" rule is fundamental, since we derive various optimizations from it (such as the lockfile format itself - that's what allows it to be flat).

So while at the surface your request appears reasonable, it simply goes against Yarn's design.

**Comment by smably** [comment]
> Yarn simply doesn't allow multiple identical ranges to have different possible resolutions.

Sorry to resurrect such an old issue, but what would be really useful for me is a command similar to `yarn install --flat`, but for initializing a workspace lockfile from existing project lockfiles. Where an identical range had different resolutions among the existing lockfiles, it would prompt me to choose a resolution and then write that resolution into the workspace's lockfile. Resolutions where all the existing lockfiles agreed could be copied over into the new lockfile automatically.

**Comment by zemse** [comment]
I'm combining multiple repositories into a monorepo design using yarn workspaces. Since these packages have existed as repositories on their own before, each of them have a `yarn.lock` file.

Running `yarn install --frozen-lockfile` in monorepo root installs the packages, but ignoring the locked package versions in individual package's `yarn.lock` files. Sometimes changing the `"^0.8.1"` to `"0.8.1"` in the workspace packagejsons have helped me at least lock the direct dependencies installed by the global `yarn install`, but it's difficult to get dependencies of dependencies locked at a version with this approach.

I understand there are some technical problems if similar ranges and different lock versions are hoised. But at least allowing a way for specifying a workspace to be independent, i.e. be completely non-hoisted and utilise it's `yarn.lock` file. This has a downsides that packages repeat, but sometimes it is needed.
