### ISSUE TITLE
"yarn install --no-bin-links" is not working since yarn@1.11.x

### ISSUE THREAD

**Issue by ktanakaj** [yarnpkg/yarn#6612]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
```
[vagrant@localhost server]$ yarn install --no-bin-links
yarn install v1.11.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
error An unexpected error occurred: "EPROTO: protocol error, symlink '../bin/acorn' -> '/vagrant/server/node_modules/acorn/.bin/acorn'".
info If you think this is a bug, please open a bug report with the information provided in "/vagrant/server/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Run the following commands.
```
mkdir work
cd work
npm init -y
yarn add --no-bin-links typescript
```

**What is the expected behavior?**
```
[vagrant@localhost server]$ yarn install --no-bin-links
yarn install v1.10.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
Done in 236.49s.
```

**Please mention your node.js, yarn and operating system version.**
* node.js : v10.13.0
* yarn : v1.10.0, v1.11.1, v1.12.1
* CentOS : 7.5
* Vagrant : 2.1.1
* Virtual Box : 5.2.12

Note: I use yarn on virtual box shared folder. This folder is not supported to symlinks.

**Comment by dhampik** [comment]
We also faced the same issue just yesterday when we tried to update yarn. We have pretty similar environment:
nodejs: v8.11.1 or v10.13.0 or v11.0.0
yarn: v1.11.1, v1.12.1
CentOS: 6
Vagrant: 2.2.0
Virtualbox: 5.2.20
Host system: Windows 8.1/10

When trying to run `yarn install --no-bin-links` in a shared folder it looks like yarn is skipping bin links option and still tries to create symlinks and fails (since it's shared folder on windows which by default does not support symlinks).

We've found that it works fine with yarn 1.10.1 and does not work with 1.11.1 or 1.12.1.

It's strange that it was not reported earlier, looks like the issue exists for a couple of months already.

**Comment by ktanakaj** [comment]
I confirmed that yarn v1.12.3 is working  with "--no-bin-links" option.
A pull request for #6585 was merged 2 days ago.
I guess my issue was also fixed.

**Comment by Cvar1984** [comment]
I faced same problem on yarn 1.22.4

**Comment by hezedu** [comment]
Same problem on yarn 1.22.4 too

**Comment by fresheneesz** [comment]
Please address this. This option is needed for things like windows linux subsystem. Yarn is useless on such a system because inevitably a symlink fails to be created.
