### ISSUE TITLE
"Plug'n'Play" is confusingly similar to "PNPM"

### ISSUE THREAD

**Issue by octogonz** [yarnpkg/yarn#6637]
Yarn's [Plug'n'Play feature](https://github.com/yarnpkg/rfcs/pull/101) uses the acronym "PNP" and config files with names like **pnp.js**.

When I discuss this feature of Yarn with people, they seem to regularly confuse it with the [PNPM](https://pnpm.js.org/) package manger, which is a completely unrelated project.  PNPM predates PNP by years, and is as old as Yarn itself.

Facebook should choose a different name that respects other JavaScript community projects, and avoids unnecessary confusion.

**Comment by arcanis** [comment]
Interesting remark!

The official name is Plug'n'Play. I've discussed the project with @zkochan before even publishing it publicly, and I don't recall there ever was a problem (and that's not something he mentioned since then either). Also note that you're the first one to raise the issue even though the RFC had a quite significant exposure, and that Plug'n'Play / PnP is already known under this name - a rename would things more confuse, not less.

All that to say I'm not too worried about the confusion in the general case. There might be some, and the similarity certainly is unfortunate, but I believe time will make this moot. If pnpm managed to avoid confusions with npm, I believe we should be able to do the same 😄 

Note that the best casing is PnP (I don't care that much, but it contributes to make them visually different, at least).

> Facebook should choose a different name that respects other JavaScript community projects, and avoids unnecessary confusion.

Yarn isn't a Facebook project. Please refer to "the Yarn team" for things like this 🙂

**Comment by zkochan** [comment]
It is true that @arcanis has notified me about PnP a week before submitting the RFC (thanks for that).

I did notice the similarity but somehow thought it was not such a big issue. I probably had to notify our group and ask their opinion, so sorry about that.

At the moment, when I search for "pnpm", I don't see PnP in the results. However, if that will change or people will be confused in the future, I'd ask to note somewhere in docs that "PnP is a feature of Yarn, don't confuse it with [pnpm](https://github.com/pnpm/pnpm), which is a different, standalone JavaScript package manager".

**Comment by arcanis** [comment]
> However, if that will change or people will be confused in the future, I'd ask to note somewhere in docs that "PnP is a feature of Yarn, don't confuse it with pnpm, which is a different, standalone JavaScript package manager".

That sounds totally fair 👍
