### ISSUE TITLE
Native packages  (java, better-sqlite3) rebuilt every time I remove a package

### ISSUE THREAD

**Issue by qiulang** [yarnpkg/yarn#6656]
**I want to report a bug**
I notice https://github.com/yarnpkg/yarn/issues/932 was closed and you guys said 

> "If it happens with one specific native dependency, please also open an issue but don't forget to specify the name of the dependency in the title" 

 But my problem is it happens every time I **remove** a package , please check the log:

The rebuild log was cleared when yarn finished, but I have copied them and paste at the bottom

```
qiulangs-MacBook-Pro:inspection qiulang$ yarn remove koa-morgan
yarn remove v1.12.1
(node:16743) ExperimentalWarning: The fs.promises API is experimental
[1/2] 🗑  Removing module koa-morgan...
[2/2] 📃  Regenerating lockfile and installing missing dependencies...
success Uninstalled packages.
```

Then I remove another package and yarn rebuilt those packages again

```
qiulangs-MacBook-Pro:inspection qiulang$ yarn remove multiparty
yarn remove v1.12.1
(node:18376) ExperimentalWarning: The fs.promises API is experimental
[1/2] 🗑  Removing module multiparty...
[2/2] 📃  Regenerating lockfile and installing missing dependencies...
success Uninstalled packages.
✨  Done in 48.20s.
```

The rebuild log

```
qiulangs-MacBook-Pro:inspection qiulang$ yarn remove multiparty
yarn remove v1.12.1
(node:18376) ExperimentalWarning: The fs.promises API is experimental
[1/2] 🗑  Removing module multiparty...
[2/2] 📃  Regenerating lockfile and installing missing dependencies...
[8/8] ⠄ better-sqlite3
[-/8] ⠄ waiting...
[-/8] ⠄ waiting...
[-/8] ⠄ waiting...
[5/8] ⠄ java

```

```
qiulangs-MacBook-Pro:inspection qiulang$ node --version
v10.1.0
qiulangs-MacBook-Pro:inspection qiulang$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14
BuildVersion:	18A391
```

**Comment by vaindil** [comment]
This is also happening to me on Windows 10. I have `windows-build-tools` installed globally, which means I can't touch my global packages unless I use an admin command prompt because it's rebuilding that package every time and therefore needs admin permissions. The only two that this would apply to are `node-sass` and `windows-build-tools`; both are being rebuilt regardless of which global package I add or remove.

Yarn 1.12.3, Windows 10 Professional x64

**Comment by qiulang** [comment]
And sometime rebuild will be stuck. For example today I tried remove and yarn got stuck

```
qiulangs-MacBook-Pro:inspection qiulang$ yarn remove  koa-bodyparser
yarn remove v1.12.1
[1/2] 🗑  Removing module koa-bodyparser...
[2/2] 📃  Regenerating lockfile and installing missing dependencies...
[1/8] ⠄ integer
[-/8] ⠄ waiting...
[-/8] ⠄ waiting...
[4/8] ⠄ nodejieba
[5/8] ⡀ java
```

**Comment by zzzorgo** [comment]
I don't understand how Yarn works with native modules. Why should it rebuild them after every deps change even if the change doesn't affect any native module? May be there is some way to configure Yarn not to do so or is this really a bug?

**Comment by mitra42** [comment]
There are many other scenarios that this happens - it seems to be a yarn bug, I reported a similar problem in https://github.com/yarnpkg/yarn/issues/7484 , where two consecutive yarn upgrades do a complete rebuild of packages, even though **nothing** has changed between the two runs. 

For us its an issue, because our package is included in a larger package (that isnt javascript) and they don't want to run upgrades on our package not because of the time it takes to do a real upgrade, but because of the time it takes when there is no upgrade to do at all.

**Comment by merceyz** [comment]
Closing as fixed in v2 where the tracking of what needs to be rebuilt has been greatly improved

https://yarnpkg.com/getting-started/migration
