### ISSUE TITLE
Hosted Git commit dependencies not served from cache

### ISSUE THREAD

**Issue by gabegorelick** [yarnpkg/yarn#6828]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Yarn does not resolve a dependency like "foo": "githubuser/repo#commit", from cache. Instead, yarn has to resolve the dependency each time `yarn install` is run.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Add github commit as dependency
2. Run `yarn install`
3. Run `yarn install` again. Notice yarn has to re-resolve dependencies from internet

**What is the expected behavior?**

Yarn should serve dependencies on (non-local) specific commits from cache by default. 

The existing behavior may make sense when pointing to a branch that's expected to move, but makes less sense for dependencies that point to specific commits.

The risk is that someone can overwrite commits, but seems like that should be overcome by running `yarn install --force`.

Yarn: 1.12.3

**Comment by rally25rs** [comment]
The thing following the `#` is a "commit-ish" (a commit object, a tag object that points to a commit object, a tag object that points to a tag object that points to a commit object, etc.)

Yarn doesn't know if it is a commit or a tag or a branch. There was an existing bug where it would pull from cache instead of re-fetching branch changes, so this is probably a side-effect of a fix for that, but 

I don't think this is something that we would change. Resolving the commit-ish to see if it is a commit or something else then choosing to use cache or not is more likely to cause issues that just fetching the data from the git url.
