### ISSUE TITLE
`npm prune` equivalent behavior

### ISSUE THREAD

**Issue by bouk** [yarnpkg/yarn#696]
**Do you want to request a _feature_ or report a _bug_?**

Feature

**What is the current behavior?**

Currently yarn doesn't seem to be removing any packages that aren't needed. With npm you can run `npm prune`, but yarn doesn't have that and doesn't do the same operation in other cases.

**What is the expected behavior?**

```
yarn init
npm install react
yarn clean
yarn install # I expect one of these two commands to remove node_modules/react
```

**Please mention your node.js, yarn and operating system version.**

Node v5.7.0
Yarn v0.15.1
macOS 10.12

**Comment by kittens** [comment]
Thanks for the report! `yarn install --force` should do what you're looking for. When generating integrity hashes (what we use to check validity of the current install) we should also do an `fs.readdir` of all module folders.

**Comment by akshatjain1995** [comment]
`yarn remove <package-name>` removes the package... @kittens can we add instruction for the user as we are adding the instruction for the `yarn -i`?

**Comment by torifat** [comment]
@kittens running `yarn prune` says:

```
error The prune command isn't necessary. `yarn install` will prune extraneous packages.
```

**Comment by jljorgenson18** [comment]
@torifat Yea that looks to be working, even when you cut out devDependencies by using `--production`

**Comment by thomaswmanion** [comment]
When I run `yarn`, then `npm prune --prodution`, then have to run `yarn` again, It doesn't reinstall the dev dependencies. Force seems like overkill. How else would you get around this?

**Comment by develar** [comment]
My expectation that `yarn` will not required additional and explicit `prune` or `deduce`. And my node_modules will be always clean and small. Currently, removing dependency from package.json manually (e.g. `@types/semver`) and then `yarn`,  yarn doesn't remove files. `npm prune` is still required :(

**Comment by rarkins** [comment]
On our CI platform, we currently do this:

`npm install`
tests
`npm prune --production`
deploy

i.e. after testing, but before deploying, we remove devDependencies. They get added back again at the start of the next build/test. Is there an equivalent way with `yarn` that doesn't bypass the cache or require `npm`?

**Comment by davglass** [comment]
I agree with @rarkins. Do y'all have an example of how you produce an app suitable for deployment that removes all of the devDependencies? But still allows for the lock file to make sure that all the deps are solid? This is the biggest issue that we face with npm's shrinkwrap. We want production deps to be locked but devDependencies to be free floating so that they are updated more easily as they tend to change more rapidly.

**Comment by erulabs** [comment]
```
yarn install
# run tests
yarn install --production
```

Seems to work fine - the downside is I can't figure out how to get yarn to not "build fresh packages" (ie: rebuild native modules). What I really need is `yarn install --production --prefer-not-fresh` or something 📦

**Comment by chetanddesai** [comment]
@erulabs what order would you run those things in?  

```
$ yarn install
$ <run tests>
$ <remove node_modules?>
$ yarn install --production --ignore-scripts --prefer-offline
$ deploy?
```
I'm having trouble getting the equivalent to `npm prune --production`.  The use-case is ripping out any build time `node_modules` so they don't get deployed out with the running service that only needs the runtime dependencies.

**Comment by erulabs** [comment]
@chetanddesai You don't need to wipe out the `node_modules` directory - just:

```
$ yarn
$ <test>
$ yarn install --production --ignore-scripts --prefer-offline
```

Remember that if you're trying to do this stuff in a container - yarn keeps its cache outside the `node_modules` dir, so you'll need to `yarn cache clean` if you want to really cleanup everything in the environment.

**Comment by Diokuz** [comment]
```
yarn install --production
```
It is not very intuitive. I dot not want to (re)install production packages, I want to remove dev packages. Is it hard to implement an alias `yarn prune --production`?

**Comment by abhiaiyer91** [comment]
Does Yarn not remove files when using `--force`. For the `prune` suggestions above, I went ahead and installed some extraneous dependencies. Then ran `yarn install --force`, everything was fine in both `package.json` and my `yarn.lock`, but unfortunately the files in `node_modules` were still present. This could potentially be an issue if you're using a mono-repo and your extraneous dependency is an incorrect parent repository dependency.

**Comment by sdbondi** [comment]
As @abhiaiyer91 says `yarn install --production --ignore-scripts --prefer-offline` still leaves the packages. I'm just using `npm prune --production --quiet`

**Comment by pxwise** [comment]
[Running this script](https://gist.github.com/pxwise/c4833557930a5141c4e3c752347e2f2e) gets me close to `npm prune --production` for docker builds.

```javascript
const exec = require('child_process').exec;
const devDependencies = Object.keys(require('../../package.json').devDependencies).join(' ');
const command = 'yarn remove ' + devDependencies;

const child = exec(command, (err, stdout, stderr) => {
  if (err) throw err;
  console.log(`stdout: \n${stdout}`);
  console.log(`stderr: \n${stderr}`);
});
```

**Comment by tech4him1** [comment]
For me `yarn install --production --ignore-scripts --prefer-offline` doesn't clean up all the dependencies.  Is there a particular reason that you don't want to add a `prune` command, or do you just need someone to step up and add it?

**Comment by rockymadden** [comment]
@tech4him1 I found the same, try adding `--force` and it does clean them up.

**Comment by arcanis** [comment]
I can't reproduce this bug. If you still experience it on the latest Yarn release, please update the script below to make it a viable reproduction, and reopen the issue.

```
#!/usr/bin/env bash

YARN=${YARN:-yarn}

TEMP="$(mktemp -d)"
trap 'rm -rf "$TEMP"' EXIT

echo $TEMP
cd "$TEMP"

printf '{ "name": "main", "version": "1.0.0", "license": "MIT", "dependencies": {} }' > package.json

$YARN add --dev babel-core
$YARN add left-pad

$YARN install
$YARN install --production

ls -l node_modules node_modules/*
```

**Comment by Diokuz** [comment]
Another issue here: some packages are private, so docker cannot install them. I want to copy all the stuff to docker context, then just _remove_ devDeps. No reinstall – it fails.

**Comment by vladgolubev** [comment]
@Diokuz Docker can install private packages if you provide `NPM_TOKEN` environment variable in Dockerfile

**Comment by Diokuz** [comment]
@vladgolubev in my case it was not possible because our private npm server (not an npm.org) was physically unreachable from docker.

**Comment by loopmode** [comment]
> [Running this script](https://gist.github.com/pxwise/c4833557930a5141c4e3c752347e2f2e) gets me close to `npm prune --production` for docker builds.
> 
> ```js
> const exec = require('child_process').exec;
> const devDependencies = Object.keys(require('./package.json').devDependencies).join(' ');
> const command = 'yarn remove ' + devDependencies;
> 
> const child = exec(command, (err, stdout, stderr) => {
>   if (err) throw err;
>   console.log(`stdout: \n${stdout}`);
>   console.log(`stderr: \n${stderr}`);
> });
> ```

Of course this becomes more complicated when you use yarn workspaces, as in my case.
One needs to get a list of package.json files e.g. via some sort of glob, then run the "delete devDependencies" trick over them. I like the approach, but I hope I can avoid it altogether.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
My `jq` usage solution is,

```sh
$ yarn remove $(cat package.json | jq -r '.devDependencies | keys | join(" ")')
```

**Comment by lucaspiller** [comment]
For anyone still desiring this feature, all of the current workarounds require the yarn command to work online. In my case I have private packages from GitHub, and don't want the access credentials to be accessible in the final image.

With `npm prune` this can be done, as I can use a multi-stage Docker build. The first image has access to the credentials and installs all packages (for compilation). Then in the second image which doesn't have access to the credentials, I can copy the `node_modules` folder from the first image and prune it.

None of the current solutions work with the `--offline` flag (which could be a separate bug, as the dependencies are up to date according to `yarn install`), so I can't use yarn for this.

**Comment by patarapolw** [comment]
My solution, using `jq` for Docker is

```dockerfile
RUN echo $(cat package.json | jq 'del(.devDependencies)') > package.json
RUN yarn --frozen-lockfile
```

**Comment by loopmode** [comment]
@patarapolw isn't that equivalent to `yarn install --production --frozen-lockfile`? What's the benefit?

**Comment by gaggle** [comment]
> @patarapolw isn't that equivalent to `yarn install --production --frozen-lockfile`? What's the benefit?

I can't speak for @patarapolw but when I run `yarn install --production --frozen-lockfile` I get all the dev-dependencies as well. There may be some subtle differences but as I can conclude `--prod` does nothing 🤷 

(This is for a workspaces enabled project if that makes a difference)

**Comment by sebmellen** [comment]
@gaggle running into the same issue now in a workspaces-enabled project. I've resorted to using [this fix](https://github.com/yarnpkg/yarn/issues/696#issuecomment-462014673) from @b6pzeusbc54tvhw5jgpyw8pwz2x6gs, which works. 

Note, however, that I'm installing all the dependencies in a Docker image after using [package-json-merge](https://www.npmjs.com/package/package-json-merge) to create one concatenated `fullpackage.json` from the many `package.json` files in the submodules of our workspace in a `/packages` folder (structured as `/packages/<NAME_OF_SUBMODULE>/`).

I have a script that runs before the Docker container gets any build context: `"merge-package.json-files": "package-json-merge ./packages/**/package*.json > fullpackage.json && sleep 5s",`. Then in the Dockerfile, I copy over the fullpackage.json as package.json (`COPY fullpackage.json ./package.json`) and then `RUN yarn remove $(cat package.json | jq -r '.devDependencies | keys | join(" ")')`. Then, I run `RUN yarn install --production --ignore-scripts --prefer-offline --force --frozen-lockfile`.

I hope this helps anyone using Docker & workspaces together. It works but it's a little messy.

_**I'm interested to know if you have found a cleaner setup since posting your comment?**_

**Comment by merceyz** [comment]
The easiest way to have a setup like that would be Yarn 2 /w `node_modules` and this plugin https://gitlab.com/Larry1123/yarn-contrib/-/tree/master/packages/plugin-production-install.

https://yarnpkg.com/getting-started/migration

**Comment by aprilmintacpineda** [comment]
I think a separate script to `prune dev dependencies` should be supported by yarn. This is our use case:

- `yarn` which will install all dependencies
- Build javascript
- Upload build together with node_modules

It would be ideal if we can do:

- `yarn` -- which will install all dependencies
- Build javascript
- yarn prune --production -- remove dev dependencies
- Upload build together with node_modules

So that the files to be uploaded will be fewer taking less time to upload.

**Comment by TakeshiDaveau** [comment]
I aggre with @aprilmintacpineda  for typescript project we can't use `yarn install --production` before it's transpiled, and after the transpilation we don't need `typescript` anymore

**Comment by benjamin-richardson-circular** [comment]
Running my Dockerfile like this seems to achieve the result I want. My node_modules drops from 190MB to 150MB and all Yarn has to do is prune rather than re-install everything.

```
FROM node:14-alpine

WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .

RUN yarn install

COPY . .

RUN yarn build

RUN rm -rf app/

# Prune off the dev dependencies after build step
RUN yarn install --production

CMD [ "yarn", "start" ]
```

**Comment by vcarl** [comment]
I haven't been able to get yarn to respect the cache during my docker build, it reliably fetches if I don't manually specify cache preservation. And because the cache is in a separate folder, it's being included in the final build. Currently migrating away from yarn (much to my chagrin! I prefer it over npm!) because I can't argue with 15% smaller bundles, see https://github.com/reactiflux/reactibot/pull/224
