### ISSUE TITLE
v14 and v15 not available in Homebrew

### ISSUE THREAD

**Issue by milesj** [yarnpkg/yarn#7097]
**Do you want to request a *feature* or report a *bug*?**

Bug?

**What is the current behavior?**

Homebrew Yarn has v13 as the latest, while v14 and v15 exist have been released: https://github.com/yarnpkg/yarn/releases

```
[12:14:44] Miles > brew upgrade yarn
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
kcov
==> Updated Formulae
needle

Error: yarn 1.13.0 already installed
```

```
[12:21:35] Miles > brew upgrade yarn --fetch-HEAD --force
Error: yarn 1.13.0 already installed
```

**What is the expected behavior?**

v14 and v15 are available.

**Please mention your node.js, yarn and operating system version.**

```
  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 2.53 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - ~/.nvm/versions/node/v10.14.1/bin/npm
```

**Comment by arcanis** [comment]
There's a quirk in our release pipeline that prevents me from marking 1.14 as stable, because 1.15 exists. I still marked them as stable in the Github releases because otherwise we have a bug in `set-policies` that prevents downloading them in the first place.

My plan is to move 1.15 to stable in a week or two, which should restore some sanity.

**Comment by milesj** [comment]
v15 is now available, going to close this. Thanks!
