### ISSUE TITLE
Run script for all workspaces without having to add every possible script to every workspace

### ISSUE THREAD

**Issue by Yzrsah** [yarnpkg/yarn#7121]
Workspaces have different requirements. They may be grouped into related packages that accept certain script commands appropriate for their functionality.

It is not possible to run a script for all workspaces without failing on the first workspace that does not have a script.

If there's some packages that use "apply", then we have to add: `"apply": "echo",` to every other package across the project, even if that script is meaningless for a given package.

It would be excellent if we could use `yarn workspaces run script` across all workspaces, while having the option to skip workspaces which do not have a script.

**Comment by Yzrsah** [comment]
I wanted `postinstall` to work with yarn workspaces,
```
      "postinstall": "yarn workspaces run postinstall"
```

So I had to add `postinstall` scripts to every package, even if they didn't need it.

It makes pages of scrolling:

```
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
$ yarn workspaces run postinstall
yarn workspaces v1.15.2
yarn run v1.15.2
✨  Done in 0.43s.
yarn run v1.15.2
$ echo

✨  Done in 0.10s.
yarn run v1.15.2
$ echo

✨  Done in 0.10s.
yarn run v1.15.2
$ echo

✨  Done in 0.09s.
yarn run v1.15.2
$ echo

✨  Done in 0.10s.
yarn run v1.15.2
$ echo

✨  Done in 0.12s.
yarn run v1.15.2
$ echo

✨  Done in 0.09s.
yarn run v1.15.2
$ echo

✨  Done in 0.10s.
yarn run v1.15.2
$ echo

✨  Done in 0.11s.
yarn run v1.15.2
$ echo

...
```

because only some of the packages have `postinstall`

**Comment by Yzrsah** [comment]
I wanted `postinstall` to work with yarn workspaces,
```
      "postinstall": "yarn workspaces run postinstall"
```

So I had to add `postinstall` scripts to every package, even if they didn't need it.

It makes pages of scrolling:

```
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
$ yarn workspaces run postinstall
yarn workspaces v1.15.2
yarn run v1.15.2
✨  Done in 0.43s.
yarn run v1.15.2
$ echo

✨  Done in 0.10s.
yarn run v1.15.2
$ echo

✨  Done in 0.10s.
yarn run v1.15.2
$ echo

✨  Done in 0.09s.
yarn run v1.15.2
$ echo

✨  Done in 0.10s.
yarn run v1.15.2
$ echo

✨  Done in 0.12s.
yarn run v1.15.2
$ echo

✨  Done in 0.09s.
yarn run v1.15.2
$ echo

✨  Done in 0.10s.
yarn run v1.15.2
$ echo

✨  Done in 0.11s.
yarn run v1.15.2
$ echo

...
```

**Comment by ProLoser** [comment]
# Teh Background

`yarn workspaces run [script]` fails if a package is missing the script. [These are the relevant lines of code](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/workspaces.js#L83-L86)

It's just a dead-simple iterator that tries to execute an arbitrary yarn command on a package. It has no knowledge of what the command is.

# Teh Problem

Adding checks to see if we're issuing an `npm run` esque command and then doing introspection would turn the `yarn workspaces` command into what I personally deem terribly organized code.

# Solutions
1. `yarn workspaces --error=early|late|never`  
  **early** is default, current behavior
  **late** finishes looping if any workspaces errors, but the result is an error (the first? an array?). Missing scripts will still result in an error
  **never** finishes looping, doesn't yield errors ever

2. `yarn run [script] --no-missing-error`  
  The basic script runner will get the seemingly useless flag to not throw errors if the specified script is missing. This means we simply use this flag in the `yarn workspaces` scenario. The `workspaces` command doesn't get cluttered with logic and checks specifically for `npm run`-like commands. `yarn run` gets a weird flag that's useless by itself.  
  This enables: `yarn workspaces run [script] --no-missing-error` but this flag would have to be passed every time you want a forgiving `yarn workspaces` command.

I could submit a PR but I'm interested in suggestions on how to refactor this to not be hella-ugly code.

**Thoughts?**

**Comment by hrougier** [comment]
Any news on this ? :)

**Comment by ProLoser** [comment]
@hrougier https://github.com/yarnpkg/berry/pull/163 which closes https://github.com/yarnpkg/berry/issues/62

berry is the yarn2 repo

**Comment by leoyli** [comment]
@ProLoser, So we can expect this comes out in yarn 2.  Does it only scoped to yarn 2, or could we have this as a minor feature release to v1, it looks super helpful! 💪

**Comment by gund** [comment]
I'm sorry but I would like to ask not to point to Yarn 2 being a solution as even the docs says - "[Yarn v2 is a very different software from the v1](https://next.yarnpkg.com/advanced/migration)".

I've tried to use Yarn 2 in my workspace project at it failed to install dependencies (first because of lack of git resolvers and then because it failed to list releases for who know what reasons) while NPM and Yarn v1 both installing without any issues.

So that being said - we would really love to see this behavior (running non failing scripts in workspace) in current Yarn v1 version.

**Comment by Acerbic** [comment]
I suggest using [Lerna](https://lerna.js.org/). It can be configured to work on top of Yarn Workspaces, so for all install needs it would actually call yarn. 

Then in Lerna you can:

```
lerna run postinstall
```

**Comment by PaulRBerg** [comment]
> I've tried to use Yarn 2 in my workspace project at it failed to install dependencies (first because of lack of git resolvers and then because it failed to list releases for who know what reasons)

@gund [there is a way](https://yarnpkg.com/advanced/migration#compatibility-table) to use Yarn 2 but keep the legacy "node_modules" resolution system, which should fix the installation issues you have.

**Comment by gund** [comment]
@PaulRBerg yes I'm aware of that and in fact I did use it and got those errors anyways just because Yarn v2 is doing things differently than v1 or NPM.

Even though I managed to update my project to work with Yarn v2 I think other project may not be able to do this or it might be just too much of an effort to migrate.

That is why I suggested not to rely on "fixed by Yarn v2" approach but add this feature right here on Yarn v1 workspaces.

**Comment by paul-soporan** [comment]
Closing as this feature has been implemented in the v2 (workspaces not listing the script are skipped by default).

> Does it only scoped to yarn 2, or could we have this as a minor feature release to v1, it looks super helpful! 💪

Since v2 was released, v1 has and will only received critical security fixes and fixes that make the migration easier. You should try migrating to v2, as it's much more stable.

https://yarnpkg.com/getting-started/migration
