### ISSUE TITLE
Plug'n'Play on Windows doesn't support the cache and project to be kept on separate drives

### ISSUE THREAD

**Issue by cveld** [yarnpkg/yarn#7138]
**Do you want to request a *feature* or report a *bug*?**
Somewhere in the middle

**What is the current behavior?**
Running a yarn pnp install with the cache on a separate drive results in the warning:
```Plug'n'Play on Windows doesn't support the cache and project to be kept on separate drives```

**What is the expected behavior?**
Cache and repo on separate drive should be supported.

**Please mention your node.js, yarn and operating system version.**
node -v
v8.11.4

npm -v
6.4.1

yarn -v
1.13.0

**Comment by arcanis** [comment]
Yep, I'm aware of this one since I've put the warning :p

I have some hopes to be able to fix it for the v2 but it's not super high in my priorities. The gist is that PnP uses relative paths between the project folder and the cache folder (so that it stays stable across systems), but that obviously cannot happen on Windows multi-drives.

**Comment by bluelovers** [comment]
anything is required in pnp, but windows can't ??

**Comment by merceyz** [comment]
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration
