### ISSUE TITLE
Incorrect hoisting with duplicate transitive dependency

### ISSUE THREAD

**Issue by mistic100** [yarnpkg/yarn#7203]
**Do you want to request a *feature* or report a *bug*?**
Bug

Note : this is **not** a report about transitives dependencies not being systematically hoisted, I am aware this is not intended to be the case.

**What is the current behavior?**

Here are three repositories :
https://github.com/mistic100/test-project
https://github.com/mistic100/test-common-dependencies-build
https://github.com/mistic100/test-common-dependencies-core

"project" depends on "common-dependencies-build" and "common-dependencies-core", and both of them depends on a bunch of modules to build an Angular app.

The important information here is that "@angular/core" is declared in both, it was a mistake but it allowed me to discover what seems to be a bug.

* Checkout "test-project" and run yarn to install everything.
* Run `ls node_modules/@angular` to list hoisted angular modules, you should see this
    ```
    animations cli compiler compiler-cli core
    ```
* Note that modules like "forms" and "common" has not been hoisted
* `ls node_modules/test-common-dependencies-core/node_modules/@angular` shows the missing modules are here
* If instead you use [this version](https://github.com/mistic100/test-common-dependencies-build/commit/f58e96be89c8409aaf4bd95a7c6f320685ad242c) of common-dependencies-build which does not depends on @angular/core, all Angular modules are correctly hoisted

What is really surprising is this :
```
$ yarn why @angular/common
yarn why v1.15.2
[1/4] Why do we have the module "@angular/common"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@angular/common@7.2.13"
info Reasons this module exists
   - "test-common-dependencies-core" depends on it
   - Hoisted from "test-common-dependencies-core#@angular#common"
Done in 0.60s.
```

It says that the depedency is being hoisted (but it's not) and the lines about disk size are missing.

Here the same command when using the "good" version of common-dependencies-build
```
yarn why v1.15.2
[1/4] Why do we have the module "@angular/common"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@angular/common@7.2.13"
info Reasons this module exists
   - "test-common-dependencies-core" depends on it
   - Hoisted from "test-common-dependencies-core#@angular#common"
info Disk size without dependencies: "18.39MB"
info Disk size with unique dependencies: "18.48MB"
info Disk size with transitive dependencies: "18.48MB"
info Number of shared dependencies: 1
Done in 0.69s.
```

"common-dependencies-build" not depending on @angular/common, I don't understand why it is not being hoisted, and why "yarn why" says it IS hoisted (I think it fails to print the disk size because it does not read the right directory).

Also why "@angular/animations" is hoisted but "@angular/common" is not ?

---

I know this is a bit tricky... feel free to ask for details.

**Comment by mike-phillips** [comment]
I ran into a very similar issue recently and did some investigation. While I suspect this won't be as helpful anymore since it's been a year since you originally posted, it might help some others.

From what I learned about the issue in a project I was working on, my guess it that `@angular/common` and `@angular/forms` aren't being hoisted due to having a `peerDependency` on `@angular/core` and there being duplicate, unhoisted copies of `@angular/core` blocking them from being hoisted.

In [src/package-hoister.js](https://github.com/yarnpkg/yarn/blob/a75dbe36ca7f6d881d291a7231676d00d523bb39/src/package-hoister.js#L381) there's a comment explaining that Yarn shouldn't hoist a package higher than its peer dependencies.

https://github.com/yarnpkg/yarn/pull/4086 is the PR where that logic was added and https://github.com/yarnpkg/yarn/issues/3933 is the issue that motivated the change.

For your example with the "test-project" repo (which appears to have been deleted), if you ran `ls node_modules/test-common-dependencies-core/node_modules/@angular` my guess is that you would have seen an entry for `core` alongside the entries for the missing, unhoisted `forms` and `common` modules.

If you're able to consolidate the duplicate installs of `@angular/core` into a single version that is hoisted to `node_modules/@angular/core`, I believe that would fix the hoisting of `@angular/forms` and `@angular/common` in your example.

**Comment by mistic100** [comment]
The base need was to have a BOM similar to Maven dependency management. I solved this my re-generating package.json files everytime for all our projects (35 and counting) and removing direct dependencies in shared packages.

But it's a pity yarn never acknowledged the issue.

**Comment by mistic100** [comment]
I encountered the problem again, but this time it even more dumb.

I have a library "common-grid" which depends on
- @ag-grid-community/angular
- @ag-grid-community/client-side-row-model

When using this library in an app, "@ag-grid-community/client-side-row-model" is installed in the root node_modules but "@ag-grid-community/angular" is installed in node_modules/common-grid/node_modules.

Hugh
