### ISSUE TITLE
An unexpected error occurred: "true is not iterable!"

### ISSUE THREAD

**Issue by solenoo** [yarnpkg/yarn#7334]
Hello,

I'm trying to migrate from **npm** to **yarn**, but for some reason when I run **yarn install** it fails with the following message **An unexpected error occurred: "true is not iterable!".**. I'm not sure if the problem is with me, if I have to do something more then just installing yarn via **msi** ?

| OS  | Windows 10 x64 |
| yarn        | v1.16.0        |
| node      |   v10.15.3     |

**Comment by rizkimcitra** [comment]
Hi, what's happening for suddenly close the issue, can u tell me how to solve it, I got the same issue

**Comment by binarybro** [comment]
Getting the same issue with yarn `1.22.19`

**Comment by binarybro** [comment]
In my case, the library I wanted to install had an entry `"bundleDependencies": true` in its `package.json`. 

As per documentation, for this property both a `boolean` value and an Array are allowed. But I guess only the latter is supported by `yarn`.

Fortunately I don't really need this feature. It was just an idea that I have since dismissed.

**Comment by laijackylai** [comment]
> Getting the same issue with yarn `1.22.19`

I had the same issue as well using yarn `1.22.19`
