### ISSUE TITLE
`yarn pack` adds unexpected files

### ISSUE THREAD

**Issue by guoyk93** [yarnpkg/yarn#7391]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

try run `yarn pack` in my project, the produced tgz file contains unexpected files.

It seems `.gitignore` take a higher priority over `files` field (white list) in `package.json`

* `package.json`

```js
{
  // ...
  "files": [
    "index.js",
    "index.d.ts"
  ],
 // ...
}
```

* `.gitignore`

```plain
# ...
# typescript
*.js
!test/**/*.js
```

* result of `yarn pack`

```plain
package
package/LICENSE
package/README.md
package/index.d.ts
package/index.js
package/package.json
package/test
package/test/scripts
package/test/testScriptlet.js
package/test/scripts/bad.js
package/test/scripts/cache.js
package/test/scripts/func1.js
package/test/scripts/load.js
package/test/scripts/loadTarget.js
package/test/scripts/loops
package/test/scripts/staticBoolean.js
package/test/scripts/staticObject.js
package/test/scripts/staticString.js
package/test/scripts/loops/loop1.js
package/test/scripts/loops/loop2.js
package/test/scripts/loops/loop3.js
```

* result of `npm pack`

```plain
package/package.json
package/index.d.ts
package/index.js
package/LICENSE
package/README.md
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Please go and check my repo https://github.com/guoyk93/scriptlet

run `yarn pack` and `npm pack`, remember to run `tsc` before packaging.

**What is the expected behavior?**

I believe `yarn pack` should work identically as `npm pack`

**Please mention your node.js, yarn and operating system version.**

node v10.16.0
yarn 1.16.0
npm 6.9.0
os Linux Mint 19.1 (Ubuntu 18.04 LTS)

**Comment by guoyk93** [comment]
I checked `src/cli/commands/pack.js` and `util/filter.js`, it seems the logic is to load ignore files (`.npmignore`, if not found, load `.gitignore`) and then append rules to blacklist files in `files` field.

I think when `files` field is white list mode, ignore files (.gitignore, .npmignore, etc) should not be used

**Comment by fuxingloh** [comment]
I dug a little deeper (https://github.com/team-innovation/vue-sfc-rollup/issues/40), basically yarn implementation of blacklist and whitelist via 'files' and 'dot ignore files' is entirely different from npm. Afaik any negates in either `package.json#files`, `.gitignore` or `.npmignore` will add the entire project.

Possibly due to the code below:
https://github.com/yarnpkg/yarn/blob/a75dbe36ca7f6d881d291a7231676d00d523bb39/src/util/filter.js#L31-L37

https://github.com/yarnpkg/yarn/blob/a75dbe36ca7f6d881d291a7231676d00d523bb39/src/cli/commands/pack.js#L82-L93

https://github.com/yarnpkg/yarn/blob/a75dbe36ca7f6d881d291a7231676d00d523bb39/src/cli/commands/pack.js#L98-L105
