### ISSUE TITLE
Yarn PnP getting a lot of error regarding @babel/runtime

### ISSUE THREAD

**Issue by dutzi** [yarnpkg/yarn#7563]
I'm trying to use Yarn PnP in our project and I'm getting a lot of error saying: 

```
xxx is trying to require the package "@babel/runtime"
```

And 

```
xxx is trying to require the package "core-js"
```

I have a feeling I had missed something in my configuration, but have no idea what.

My webpack.config is available here: https://pastebin.com/MKFRxttn

**Comment by arcanis** [comment]
Various packages require `@babel/runtime` and `core-js` without actually declaring them in their dependencies, which is forbidden by the PnP policy (because the behaviour in such a case is entirely undefined). I suggest opening an issue on the relevant packages to let them know the problem (a PR is better!).

**Comment by dutzi** [comment]
Got it, thank you!

**Comment by dutzi** [comment]
@arcanis, is there some sort of sorcery happening in Create React App? I'm asking because it _does_ support PnP.
