### ISSUE TITLE
Failed to create .yarn-integrity file in a bower project

### ISSUE THREAD

**Issue by laubstein** [yarnpkg/yarn#757]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
After run `yarn` in a simple bower project, I receive: ```error ENOENT: no such file or directory, open '/tmp/b/node_modules/.yarn-integrity'
    at Error (native)```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
bower init (default options)
bower install --save jquery
rm -fr bower_components
yarn
```

**What is the expected behavior?**
bower_components created without error message

**Please mention your node.js, yarn and operating system version.**
Linux
```
yarn --version = 0.15.1
node --version = v6.4.0
```

**Comment by tony19** [comment]
### Workaround
Create `node_modules/` directory before running `yarn`.

### Bug Research
I think the issue is twofold:
 1. [`writeIntegrityHash()`](https://github.com/yarnpkg/yarn/blob/b880d40/src/cli/commands/install.js#L636) does not create the intermediate directories in the specified path, and `fs.writeFile()` throws an error for a path with a missing intermediate directory.
 2. [`getIntegrityHashLocation()`](https://github.com/yarnpkg/yarn/blob/b880d40/src/cli/commands/install.js#L612-L615) inserts `node_modules/` into the first slot of `possibleFolders[]`, but this directory never existed (as this is strictly a Bower project). This function returns the first slot by default if `.yarn-integrity` was not found in `possibleFolders[]`. For a Bower project, the first slot should really be `bower_components/`.

**Comment by Th3Mouk** [comment]
This workaround is ok

**Comment by tony19** [comment]
For some reason, I can't reproduce this error any longer, but I think this workaround might be even better (in that a pre-existing `node_modules/` isn't needed):

```sh
yarn install --modules-folder bower_components
```

Let me know if this works for you.

**Comment by kittens** [comment]
We've removed support for Bower, see #1441.
