### ISSUE TITLE
Don't timeout as long as download is making progress

### ISSUE THREAD

**Issue by jedwards1211** [yarnpkg/yarn#7625]
I really think there should be a more comprehensive solution to this than the workaround of increasing the timeout.

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
Packages fail to download if they're so big it takes longer than the network timeout to download them.

**If the current behavior is a bug, please provide the steps to reproduce.**

Install `@material-ui/icons` on a slow network connection.

**What is the expected behavior?**
The download should only timeout if it's been that long since *any data was received*, rather than *since the download has started*.  As long as the download is slowly making progress there's no need to time out.

**Please mention your node.js, yarn and operating system version.**
yarn 1.19.0, node 10.15.0, macOS whatever

**Comment by merceyz** [comment]
Fixed in v2

https://yarnpkg.com/getting-started/migration

**Comment by jedwards1211** [comment]
Fixed...except for anyone who uses TS or Flow right?  Since they aren't compatible with PnP?

**Comment by paul-soporan** [comment]
@jedwards1211

TS is compatible with PnP because we transparently patch it.

If you use Flow or another incompatible package, you can use the `node-modules` linker. We even recommend to first migrate to v2 with the `node-modules` linker in the migration guide and only then upgrade to PnP if you can and want.

By reading the [migration guide](https://yarnpkg.com/getting-started/migration), more than 99% of users should be able to migrate to v2 with the `node-modules` linker quickly and painlessly.

**Comment by jedwards1211** [comment]
Okay, glad to hear that this is fixed for the `node-modules` linker too, thanks!
