### ISSUE TITLE
Add option to ignore some dependency when using yarn outdated

### ISSUE THREAD

**Issue by VincentLanglet** [yarnpkg/yarn#7676]
There should be an option to ignore one or multiple specific dependency when using yarn outdated. Something like
```
yarn outdated --ignore=bootstrap --ignore==jquery
```
And maybe the same for yarn upgrade-interactive.

You can have good reason to not updating a dependency but still looking for new versions for others dependencies.

**Comment by dehy** [comment]
Use case in React Native : React Native has fixed dependencies for React and some others. Theses dependencies are upgraded only with React Native upgrades and should not be upgraded separately.

**Comment by joshuapinter** [comment]
Yes please. I think this makes great sense. In our case, we have a few dependencies that cannot be upgraded for longer stretches of time, sometimes because they are our fork of a project, or they are dependent on another package being upgraded, etc. 

Having an option to just ignore these from our typical `yarn outdated --check` CI checks would be absolutely ideal. 

What we really want is to have `yarn outdated --check` catch the routine and security upgrades that we may not know about without us having to run this command manually all the time.

I'm happy to do a PR if there is some traction/approval from the core team.

**Comment by fluff** [comment]
I would also like this. Even better, an option such as `--ignore-major=vue` that would ignore newer major versions for that particular package `vue`, but still warn on newer minor releases. For example, if vue is locked to 2.6.13, it should show 2.6.14 as an available upgrade, but if vue is locked to 2.6.14, it should say it is up to date (and ignore all the 3.x releases). This would make tracking security updates much easier for a project that is in maintenance mode and cannot afford a full vue 2->3 upgrade/rewrite, for example.

**Comment by joshuapinter** [comment]
@fluff Yup, agree with that. Could add a lot more value to ignoring all but critical upgrades.
