### ISSUE TITLE
Stop pruning dot folders in node_modules

### ISSUE THREAD

**Issue by timsuchanek** [yarnpkg/yarn#7683]
In yarn 2, aka `berry`, I can create `node_modules/.some-folder`, which won't be touched when I do a `yarn install`.

In yarn 1, this folder is being pruned away.

We're building a library called [Photon.js](https://github.com/prisma/photonjs/), which leverages code generation. As of now, we generate the code into the package itself via a postinstall hook, into `node_modules/@prisma/photon`.

However, in order to make it possible for yarn 2 to cache that package, we would like to generate into a directory called `node_modules/.prisma`.

It would be great to see that behavior matched yarn 1 aswell.

Thanks!

**Comment by arcanis** [comment]
Agreed 👍

**Comment by ArgonAlex** [comment]
Personally, I think purging the cache on yarn installs is the desired behavior. It's at least a much safer option. Packages that cache things in the .cache folder don't necessarily include the versions/hashes of every single possible dependency in their cache key.

Take Webpack's cache-loader, for example. With this change, simply upgrading a dependent loader could result in stale cache entries being used. Even indirect dependency changes could result in different output that would not be covered by the cache key.

cc @evilebottnawi have you seen any issues because of this yet?

**Comment by ArgonAlex** [comment]
As a bonus side effect, purging .cache folders on installs also keeps caches from infinitely growing and taking up large amounts of disk space. Of course that's completely dependent on how often installs are performed, but still maybe worth mentioning.

**Comment by evilebottnawi** [comment]
@ArgonAlex What is problem you have? Yarn v2 do not create node-modules, but it is not mean what we can't store cache in that directory

**Comment by arcanis** [comment]
They meant that when running `yarn install` we don't remove the `node_modules/.cache` folder anymore (neither on 1.x nor 2.x), and they'd prefer us to keep remove it.

I think there are fine arguments for both approaches, but ultimately it isn't our role to ensure that the cache contains the expected data. Consider this an implementation detail 🙂

**Comment by evilebottnawi** [comment]
We use hashes and other meta information to understand whether it is a valid cache or not, so it makes no difference where we store the cache, we always validate it before use
