### ISSUE TITLE
Please update changelog

### ISSUE THREAD

**Issue by friederbluemle** [yarnpkg/yarn#7760]
Version `1.21.1` has been released, but the [Changelog](https://github.com/yarnpkg/yarn/blob/master/CHANGELOG.md) has not been updated. What are the changes/fixes/updates? Also I could not find information on why `1.20` was skipped from public release. Where can I find this information? Thanks.

**Comment by DeeDeeG** [comment]
> Also I could not find information on why 1.20 was skipped from public release. Where can I find this information? Thanks.

I don't know, but 1.20 and 1.21 were committed within about two minutes of each-other. I think the commits for 1.20 must have been published to GitHub, then the maintainer must have realized an updated 1.21 was desirable to publish instead, with more commits (some CI/test fixes and code fixes).

> What are the changes/fixes/updates?

I recommend cloning this repo and looking at the commit history. For example, running the following if you have `gitk` installed: `gitk v1.19.2 v1.20.0 v1.21.1`

Here's what the commit history looks like:

![git history yarn 1.19.x to 1.21.1](https://user-images.githubusercontent.com/20157115/71423748-724fd200-2659-11ea-88c8-9c161dc7240b.png)

I'd note the v1.20.0 git tag was missing two commits from v1.19.2, so that might be another reason why 1.20 wasn't published to the npm package registry.

**Comment by olingern** [comment]
Next release, we'll have something figured out here.

**Comment by smarts** [comment]
@olingern  `1.22.0` is out and there's still nothing in the changelog referencing that version…

**Comment by intelliot** [comment]
The changelog needs to be updated for yarn version 1.22.0.

**Comment by DeeDeeG** [comment]
Related issue: https://github.com/yarnpkg/yarn/issues/7735

**Comment by merceyz** [comment]
Closing as the changelog has been updated

**Comment by luismtzrmz** [comment]
H
