### ISSUE TITLE
[question] yarn prevents issues with non deterministic directory layouts?

### ISSUE THREAD

**Issue by likwid** [yarnpkg/yarn#781]
In the blog post introducing yarn, under the architecture subheading the following quote is found:

> The npm client installs dependencies into the node_modules directory non-deterministically.  This means that based on the order dependencies are installed, the structure of a node_modules directory could be different from one person to another. These differences can cause “works on my machine” bugs that take a long time to hunt down.

In the following blog post describing npm 3, the following quote is found:

> In short? npm3 does not install dependencies in a deterministic way. That's probably not a comforting statement to read, but in this article we'll discuss why this happens, as well as assure you that it has no implications for your application, as well as explain the steps to reliably (re)create a single, consistent, node_modules directory, should you want to do that.

Those quotes seem to be in direct contradiction with each other. 

Is there an example you can point to that highlights any findings that demonstrate the problem that yarn solves?

Are you stating that the npm post is incorrect?

**Comment by hpurmann** [comment]
I can't see the contradiction 🤔  Both say that npm is not deterministic.

**Comment by busches** [comment]
@likwid as @hpurmann pointed out both say `npm` is not deterministic, can you provide further follow-up or can this issue be closed?

**Comment by rzeigler** [comment]
The issue is under yarn
"These differences can cause “works on my machine” bugs that take a long time to hunt down."

and npm
"...as well as assure you that it has no implications for your application, as well as explain the steps to reliably (re)create a single, consistent, node_modules directory, should you want to do that."

Yarn documentation asserts that non-determinism in npm installs is a source of bugs. NPM documentation asserts that it doesn't matter.

**Comment by ljharb** [comment]
What I think would be very compelling is for yarn's documentation to provide a concrete, reproduceable example of when npm produces bugs but yarn does not.
