### ISSUE TITLE
How can i use yarn without internet?

### ISSUE THREAD

**Issue by DanielWLam** [yarnpkg/yarn#787]
Request a feature: totally offline;
Current behavior: If i can't connect to internet, then i am unable to use yarn for the first time, which is not a real 'OFFLINE'.
node:6.0.0
OS: window 7 SP1

**Comment by callmevlad** [comment]
@DanielWLam By your definition, no "offline" app can ever be offline for the first time without first pulling down what it depends on.

The only way to make it usable for the first time without an internet connection is to clone the entire npm registry during the initial yarn install, which I imagine won't fit on most machines since it's takes up [at least a terabyte of space](https://npme.npmjs.com/docs/up-and-running/requirements.html).

**Comment by Daniel15** [comment]
Hi @DanielWLam! @callmevlad is exactly right - There's a very large number of packages on npm, and we don't know which ones you want to use :)
What would you expect to happen if you try to use Yarn while offline?

**Comment by DanielWLam** [comment]
Ah, i see now. it's just because out company's computer can't connect to the 'OUTSIDE' internet. so every time i want to use npm or something need to connect to internet i have to use other computer etc, which  isn't elegant.

**Comment by JoshCheek** [comment]
So I can't point it at a directory with a bunch of packages and have it install from there? Internet access is somehow baked into it at structural level?

**Comment by devdavidkarlsson** [comment]
you can point towards a nexus where you host your packages in your company environment or even running in a local docker container...
