### ISSUE TITLE
Could not install globally in yarn 2

### ISSUE THREAD

**Issue by levirs565** [yarnpkg/yarn#7884]
I have install yarn. However, i cannot install package globally. You can see this output

```
PS E:\DaunKoder\daunkoder> yarn global add @gridsome/cli
Usage Error: Couldn't find a script named "global".

$ yarn run <scriptName> ...
```

I cannot find way to install package globally on yarn 2. Please help

**Comment by rromanv** [comment]
I have the same issue

**Comment by cspotcode** [comment]
It looks like they removed this functionality in yarn 2.  The install guide says to keep yarn 1 installed globally, then install yarn 2 locally on a project-by-project basis.  https://next.yarnpkg.com/getting-started/install

This is interesting, because it means I can't `yarn global add` when I'm inside a project's directory.  I have to `cd .. ; yarn global add foobar ; cd ./back-into-my-project`.

Is that the intended usage?  Are we supposed to use `npm` for global installs and `yarn` for project-local stuff?  Is there a plugin that re-adds `global` functionality?

**Comment by lvfxbr** [comment]
Same error.

```
C:\mypath>yarn global add @vue/cli
Usage Error: No project found in /C:/mypath

$ yarn run [--inspect] [--inspect-brk] <scriptName> ...
```

**Comment by hiepxanh** [comment]
`yarn dlx @vue/cli` should do the job
https://yarnpkg.com/getting-started/migration#use-yarn-dlx-instead-of-yarn-global

**Comment by merceyz** [comment]
Closing as this is documented in https://yarnpkg.com/getting-started/migration#use-yarn-dlx-instead-of-yarn-global

**Comment by moghaazi** [comment]
just replace `global` with `dlx`
https://yarnpkg.com/getting-started/migration#use-yarn-dlx-instead-of-yarn-global
