### ISSUE TITLE
Ubuntu 18.04 installs cmdtest instead of yarn

### ISSUE THREAD

**Issue by dqlopez** [yarnpkg/yarn#7892]
### Bug description

**Command**

```sh
sudo apt update && sudo apt-get install --no-install-recommends yarn
```

**What is the current behavior?**

Even if you uninstall `cmdtest` first hand, it will always end in this:
```
Note, selecting 'cmdtest' instead of 'yarn'
The following NEW packages will be installed:
  cmdtest
```

**What is the expected behavior?**

Should install `yarn` not the `cmdtest`

**Steps to Reproduce**

1. Just follow the installation procedure here https://classic.yarnpkg.com/en/docs/install/#debian-stable

**Environment**

- Node Version: Now using node v13.8.0 (npm v6.13.6)
- OS and version:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Comment by tatsujb** [comment]
why is this closed??? this is still happening

**Comment by mberneti** [comment]
I have this issue too.

**Comment by GrantPayneDenver** [comment]
Maybe try looking at
https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365

**Comment by tatsujb** [comment]
> Maybe try looking at [#2821 (comment)](https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365)

that's really not the question. until the cmdtest and yarn devs that debian-based distros are real distros with real human beings using them (a majority of linux users, mind you) the issue remains open. 

the package name is not the same. that it gets pulled instead is NOT by design, yes it IS a bug and switching to arch isn't the solution.

**Comment by Hightmar** [comment]
I ran into the same problem today. I found the comment that solves the problem by searching on google. But @tatsujb is right. Just because you can find the solution doesn't mean it's not a problem. It's completely stupid that when you want to install `yarn` you end up with `cmdtest`. Still, if it worked... But it doesn't.

**Comment by Eliot6001** [comment]
What the-, 
I ran `sudo apt install yarn` it installed cmdtest. again wth? 
I did it in Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
