### ISSUE TITLE
passing --json no longer produces a clean JSON string

### ISSUE THREAD

**Issue by davidwkeith** [yarnpkg/yarn#7923]
### Bug description
Previously running a command like `yarn workspaces info --json` would only return JSON, now it is prefixed with a version string and suffixed with the execution time, breaking a lot of scripts.

**Command**

```sh
yarn workspaces info --json
```

**What is the current behavior?**
Output is as follows:
```sh
yarn workspaces v1.22.0
{
  // ... JSON data
}
✨  Done in 0.07s.
```

**What is the expected behavior?**
Previous to 1.22.0 it was
```sh
{
  // ... JSON data
}
```

**Steps to Reproduce**
The following node JS used to parse the output
```js
const { execSync } = require('child_process');
const workspaces = JSON.parse(
  JSON.parse(execSync('yarn workspaces info --json').toString()).data
)
```

**Environment**

- Node Version: `v10.16.0`
- Yarn v1 Version: `1.22.0` 
- OS and version: `macOS 10.15.2 (19C57)`

**Comment by alexghr** [comment]
Hey, we encountered the same issue after upgrading to Yarn 1.22.0. We fixed after adding the `--silent` flag:
```
yarn --silent workspaces info
```

**Note**:  It matters where you put the flag, it needs to be after `yarn` or `workspaces`. If you add it after `info` then it will be ignored (it's probably because the info script is quite simple and doesn't parse flags).

**Comment by davidwkeith** [comment]
Thanks @alexghr! That fixed it for us as well.
