### ISSUE TITLE
Yarn doesn't allow install by commit

### ISSUE THREAD

**Issue by mschipperheyn** [yarnpkg/yarn#7984]
### Bug description
I have a monorepo and I need to install an unreleased version of a library and want to install by commit
I've added the dependency in devDependencies
```
"babel-loader": "git@github.com/DylanPiercey/babel-loader.git#663bdc5",
```
**Command**

```sh
yarn install
```

**What is the current behavior?**
It forces me to choose from a list of released versions

**What is the expected behavior?**
It should just install what I ask it to install

**Steps to Reproduce**

1. Add `"babel-loader": "git@github.com/DylanPiercey/babel-loader.git#663bdc5",` to package.json
2. run yarn install

**Environment**

- Node Version: `12.16.1`
- Yarn v1 Version: `1.22.1` 
- OS and version: Mac Mojave

**Comment by antonin-lebrard** [comment]
It's still an issue for me, even without the specific branch/commit/tag behind `#`, yarn still ask for a specific version.
And from my tests I can deduce yarn still fetch the list of version from the https://yarnpkg.com/ repository, as the package I want to install is from a fork of an existing package without the new tags, as it has not been updated for quite some time.

**Comment by antonin-lebrard** [comment]
For a quick resolution, yarn seems to do perfectly its job when using the `git+ssh://git@<url>#<branch/commit/tag>` url scheme.
I would have guessed that there was no difference between the two. But at least returning an error (network error I can guess in this case) instead of letting the user choose the version would at least let known that yarn could not access the git package.

**Comment by merceyz** [comment]
`git@github.com/DylanPiercey/babel-loader.git` is not valid as you can see with 
```
git ls-remote --refs git@github.com/DylanPiercey/babel-loader.git
```
