### ISSUE TITLE
Fsevents@2 does not use gyp. Yarn thinks it does

### ISSUE THREAD

**Issue by paulmillr** [yarnpkg/yarn#8052]
See the title. Not appropriate to write the “implicit” warning at all.

**Comment by merceyz** [comment]
The `package.json` of `fsevents` seems to disagree with your statement, specifically this part
```
"install": "node-gyp rebuild"
```
https://registry.yarnpkg.com/fsevents/2.2.0

See the npm documentation for why its there https://docs.npmjs.com/cli/v6/using-npm/scripts#default-values

**Comment by arcanis** [comment]
Closing, since as @merceyz mentioned `fsevents` does have an implicit dependency on `fsevents` - the presence of a `binding.gyp` is enough to cause `node-gyp` to be an implicit dependency. I know that because, you know, I actually wrote the code that implicitly add support for that in Yarn, together with the documentation that explains it. 

As an aside, I generally don't appreciate being told to [screw myself](https://github.com/fsevents/fsevents/issues/316#issuecomment-612434472). Please reconsider this kind of interactions in the future.

**Comment by arcanis** [comment]
Interestingly, `fsevents` [doesn't contain `binding.gyp` anymore](https://cdn.jsdelivr.net/npm/fsevents@2.2.1/), and thus probably shouldn't cause the warning. **However**, it seems there's a bug on the npm registry (that we have no control over) that still adds the `node-gyp rebuild` postinstall script:

![image](https://user-images.githubusercontent.com/1037931/100611716-09b1b080-3312-11eb-88e3-79c149596d69.png)

As a result, since Yarn is getting erroneous data, we have no choice but to show the warning. I suggest opening an issue on one of the npm feedback repos, since the registry is their responsibility.
