### ISSUE TITLE
yarn --version should some info about yarnrc

### ISSUE THREAD

**Issue by muescha** [yarnpkg/yarn#8070]
### Bug description

**Command**

```sh
$ which yarn
/usr/local/bin/yarn
$ ll /usr/local/bin/yarn
[...] /usr/local/bin/yarn -> ../Cellar/yarn/1.22.4/bin/yarn
$ yarn --version
1.21.0
```

**What is the current behavior?**

it shows a different version 1.21.0 than my installed version 1.22.4

**What is the expected behavior?**

it should somehow print that this version is from `.yarnrc`

**Steps to Reproduce**

- install yarn via homebrew installed 1.22.4 (or `brew upgrade yarn` -> `Warning: yarn 1.22.4 already installed`) 
- change directory to a repo with `.yarnrc` file
- run `yarn --version`

**Environment**

- Node Version: `v12.13.1`
- Nvm Version: `0.35.3`
- Yarn v1 Version: `1.21.0`
- OS and version: 
  - ProductName:	Mac OS X
  - ProductVersion:	10.15.3
  - BuildVersion:	19D76

**Comment by paul-soporan** [comment]
Closing this as a wontfix:

1) We can't change the behavior of the `yarn --version` command because external tools already expect it to print a valid semver version and nothing more.
2) You can already use `yarn config get yarn-path` (or `yarn config get yarnPath` in the v2) to see if this version is from a Yarnrc or not.
