### ISSUE TITLE
Suggestion: add "vscode" as a valid engine

### ISSUE THREAD

**Issue by iliazeus** [yarnpkg/yarn#8072]
Visual Studio Code [requires](https://github.com/microsoft/vscode/blob/master/extensions/html/package.json#L9) its extensions to include a `"vscode"` property in the `"engines"` field in `package.json`. However, `yarn` does not know it can be a valid engine, and issues a warning:

```
yarn add v1.22.4
[1/5] Validating package.json...
warning my-extension@0.0.1: The engine "vscode" appears to be invalid.
```

**Comment by latipun7** [comment]
Yes please.

```log
❯ yarn --check-files
yarn install v1.22.4
[1/5] 🔍  Validating package.json...
warning ext@0.0.0: The engine "vscode" appears to be invalid.
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 6.04s.
```

**Comment by allansson** [comment]
Why not skip all engines that yarn does not understand, perhaps with an option `engine-strict` like NPM? The code has a list of engines which it should ignore: https://github.com/yarnpkg/yarn/blob/ac21dbf1/src/package-compatibility.js#L50
Adding new entries to this for each new engine seems like a lot of extra work.

The reason that I am interested in this issue is that I work on the load testing tool k6 and I would love to add package support for it, but we need to be able to distinguish which packages support the k6 runtime and which do not.

**Comment by patarapolw** [comment]
I would also want to add PNPM as a valid engine...

But my better thought is, why not skip `engines` validation in the first place? You only need to read `engines.node` and `engines.yarn`, BTW; not the `engines` object itself.

https://dev.to/patarapolw/enginestrict-true-in-package-json-is-problematic-don-t-3cli

**Comment by paul-soporan** [comment]
Closing as fixed in v2, where we completely skip engines validation.

https://yarnpkg.com/getting-started/migration
