### ISSUE TITLE
yarn config doesn't support `--global` mentioned in the doc

### ISSUE THREAD

**Issue by h4x3rotab** [yarnpkg/yarn#8262]
### Bug description

**Command**

```sh
yarn config set httpProxy 'http://127.0.0.1:8080' --global
```

**What is the current behavior?**

```text
Unknown Syntax Error: Unsupported option name ("--global").
```

**What is the expected behavior?**
As mentioned in the doc here: <https://classic.yarnpkg.com/en/docs/cli/config/#toc-yarn-config-set-g-global>
It should support `--global`

**Steps to Reproduce**

1. Start an empty yarn project
2. Run `yarn config set httpProxy 'http://127.0.0.1:8080' --global`

**Environment**

- Node Version: `v12.18.3`
- Yarn v1 Version: `2.0.0-rc.33` 
- OS and version: Ubuntu 18.04

**Comment by LudwikJaniuk** [comment]
I can't reproduce your bug. Fresh install of yarn, `yarn --version` outputs `1.12.3`, and when I create a new directory, cd into it, run `yarn init`, accept all defaults, and then: 
```
$ yarn config set httpProxy 'http://127.0.0.1:8080' --global
yarn config v1.12.3
success Set "httpProxy" to "http://127.0.0.1:8080".
Done in 0.03s.
```
I don't think I matched your yarn version exactly but my OS is the same and at least the bug is not present. Tbh I don't know what version "Yarn v1 Version: 2.0.0-rc.33" refers to? It's not one of the branches or one of the releses here in github as far as I can see...

**Comment by h4x3rotab** [comment]
It turned out I was running yarn 2.0. Closing for now
