### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (true)

### ISSUE THREAD

**Issue by yh0210** [yarnpkg/yarn#8331]
I didn't run yarn cache clean [< module]_ name...>]
Run the yarn config set cache folder directly
Then execute yarn - V again
The following error appears. How to fix it

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (true)
    at validateString (internal/validators.js:122:11)
    at resolve (path.js:139:9)
    at loadRcFile (C:\file\node\node_modules\node_modules\yarn\lib\cli.js:56953:58)
    at C:\file\node\node_modules\node_modules\yarn\lib\cli.js:56917:14
    at C:\file\node\node_modules\node_modules\yarn\lib\cli.js:100892:14
    at Array.map (<anonymous>)
    at parseRcPaths (C:\file\node\node_modules\node_modules\yarn\lib\cli.js:100890:78)
    at Object.findRc (C:\file\node\node_modules\node_modules\yarn\lib\cli.js:100904:10)
    at getRcConfigForCwd (C:\file\node\node_modules\node_modules\yarn\lib\cli.js:56916:74)
    at C:\file\node\node_modules\node_modules\yarn\lib\cli.js:92255:56

**Comment by heiyeyehuipawo** [comment]
这个咋搞

**Comment by heiyeyehuipawo** [comment]
I also encounter this problem, how to solve it

**Comment by merceyz** [comment]
You have invalid values in your `~/.yarnrc` file

**Comment by plainnany** [comment]
try to remove ~/.yarnrc , reinstall

**Comment by jpaulin** [comment]
@yh0210 @heiyeyehuipawo In addition to the project-local .yarnrc file, you might also want to check *global*
yarn registry. This is a file typically in place reported by:

$yarn config bin
(type that in shell, you'll get file location)

If not, if yarn is that broken, search google for the location. It varies a bit depending on system. 

Easy way to just check whether this is due to global file, is to move it temporarily out of the folder where it is now. 
If this resolved the problem, good. If not, you can always move the backup file back to its original place. 
Hope it helps!
