### ISSUE TITLE
Download link is not working

### ISSUE THREAD

**Issue by jessejiang0214** [yarnpkg/yarn#8699]
The link which downloads the latest version of Yarn 1.0x is not working 
https://yarnpkg.com/latest.msi
https://github.com/yarnpkg/yarn/releases/download/v1.22.13/yarn-1.22.13.msi

**Comment by arcanis** [comment]
ping @Daniel15 - I guess this is related to the Windows CI not running anymore?

**Comment by codebarz** [comment]
Any update on this? This link https://yarnpkg.com/downloads/1.22.10/yarn-v1.22.10.tar.gz. is also not working on Netlify. @jessejiang0214, where you able to fix the issue?

**Comment by brancz** [comment]
Same for https://yarnpkg.com/downloads/1.22.4/yarn-v1.22.4.tar.gz on netlify

**Comment by erezrokah** [comment]
Hi all 👋 , Erez from Netlify here, we've posted an update on our status page https://www.netlifystatus.com/

**Comment by arcanis** [comment]
@erezrokah do you have some details? Did something break in Yarn's infra, or is it just something from Netlify's one?

(Note that the initial issue in the OP is about msi builds, nothing to do with the tgz tarballs or ssh)

**Comment by Daniel15** [comment]
> 
> 
> ping @Daniel15 - I guess this is related to the Windows CI not running anymore?

Hmm it *should* still work. My guess would be that the CircleCI build failed. If all else fails I can manually build it.

**Comment by Daniel15** [comment]
@arcanis  Looks like the build failed: https://ci.appveyor.com/project/kittens/yarn/builds/40963544. I'll just manually build it myself.

**Comment by erezrokah** [comment]
> @erezrokah do you have some details? Did something break in Yarn's infra, or is it just something from Netlify's one?

The Netlify failures are a separate issue related to Netlify's infra and specific build images. We'll post another update soon.

**Comment by Daniel15** [comment]
I've manually built an MSI installer, signed it with our Authenticode cert, and attached it to the most recent release. https://classic.yarnpkg.com/latest.msi URL works now, and installs successfully. 

```
PS C:\Users\danlo> yarn --version
1.22.15
```

@arcanis Please feel free to ping me if that's needed for future releases too :)

Since that's now fixed, and that was the original issue in the OP, I'm going to close this issue. The Netlify issue is a separate issue and you should follow up with Netlify's team for updates on that (since the Yarn team members unfortunately can't help with things that are at Netlify's end)

**Comment by ehmicky** [comment]
A fix has been implemented for Netlify users. The mitigation is automatic on Xenial, but Trusty sites will have to [update to Xenial or Focal](https://docs.netlify.com/configure-builds/get-started/#build-image-selection) in order to mitigate. We'll continue to monitor for a while before resolving the incident.

**Comment by Haroenv** [comment]
Could this be related to the issue I'm seeing here: https://github.com/algolia/vue-instantsearch/pull/1067 (curl: (60) SSL certificate problem: certificate has expired for `curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0`)

**Comment by ehmicky** [comment]
This might be related. Many providers and projects have been experiencing issues since yesterday due to [Let's Encrypt root certificate expiry](https://portswigger.net/daily-swig/device-breakage-concerns-persist-days-before-lets-encrypt-root-cert-expiry).

**Comment by AyoCodess** [comment]
i'm having this issue now too
