### ISSUE TITLE
Fork of Yarn 1.x?  What is the community's opinion on using a fork?

### ISSUE THREAD

**Issue by icywolfy** [yarnpkg/yarn#8726]
Should the community work around a fork of yarn 1.x ?
I ask, I am making a fork for personal use, and to better support 10+ years of projects, in which no-one involved wants to update their tooling stack back to npm, or to venture into pnpm.     As I am working on this anyway, I am unsure whether tho make plans to make my fork available to a wider audience.  

I'm in the process of learning the yarn codebase in preparation to support it longer term for use with existing projects.
My goal would be to mainly stabilze features, and improve reliability. 
The second goal, is to work to incrementally ensure a clean migration path back towards npm.

There will be less emphasis on new feature work -- until the repository is more understandable and architecture documented.

**Comment by thatsmydoing** [comment]
I would certainly appreciate more work done for yarn 1 to fix all the outstanding bugs that are just marked as "fixed in yarn 2"

**Comment by arcanis** [comment]
One of the reasons bugs are not fixed in 1.x is that the codebase is complex enough that any bugfix comes with a large risk of breaking something else somewhere else, requiring more and more spaghetti and constantly raising the maintenance cost. There's a reason why I eventually decided three years ago that Yarn had to start anew, and why we still push back against any non-security-related hotfix.

While you certainly can fork the Yarn codebase if you want (although there are a few that already exist, like [this one](https://github.com/VincentBailly/yarn) used by a few people at Microsoft), we cannot recommend any one of them:

- **We're already at Yarn 3.1, and it's highly unlikely that it suffers from any bug you may have with Classic 1.x**; making a fork is relatively pointless, it'd be quite more productive and welcome to help improve the most up-to-date releases than painfully try to fix something even their maintainers deemed to unstable too change.

- It's highly probable such forks will cease to be maintained even a few months after their creation. Again, there's a reason why we decided to take more than a year to redesign and rewrite the codebase. I still remember fondly [Jarn](https://github.com/jaredpalmer/jarn), which a certain someone opened right after we announced the 2.0 stable, in January 2020. It didn't receive a single commit since then, who could have guessed. The joke was hilarious though.

- Forks being outside our realm of influence, we have to way to guarantee their quality / stability / security (especially over medium-long term, see point above).

For these reasons, while I won't outright lock this thread, I believe advertisements for any single fork are best avoided to avoid giving the wrong impression. Yarn's maintainers' recommendation if you want to address bugs is still to upgrade to 3.1+, and report problems you may have (on the [modern repository](https://github.com/yarnpkg/berry)).
