### ISSUE TITLE
Windows Installer download link is broken.

### ISSUE THREAD

**Issue by wonsuc** [yarnpkg/yarn#8766]
I tried to download this but it is broken.  

https://github.com/yarnpkg/yarn/releases/download/v1.22.13/yarn-1.22.13.msi  

It seems like this is the same issue with [this](https://github.com/yarnpkg/yarn/issues/8699)?  

But, I'm not sure if it's the same problem or a different reason.

**Comment by merceyz** [comment]
cc @Daniel15

**Comment by JakeThurman** [comment]
CC @arcanis

**Comment by Daniel15** [comment]
Sorry I missed this! The MSI should be published automatically for every version as it's part of the build process, but sometimes the build process fails since there's a bunch of old infra that doesn't work as well as it used to. Yarn v1 releases aren't very frequent, so no work has gone towards improving this.

As of the time I'm writing this, the latest version does have an MSI. You can hit the URL https://classic.yarnpkg.com/downloads/1.22.18/yarn-1.22.18.msi to download v1.22.18 specifically. If future releases are missing one, please feel free to reach out to me directly via email, Twitter, or Facebook, as I don't check things on GitHub very often. 😃

**Comment by JakeThurman** [comment]
No problem! I can certainly relate to that problem. Thanks @Daniel15

**Comment by merceyz** [comment]
Closing as 1.22.18 has a Windows installer
