### ISSUE TITLE
yarn home

### ISSUE THREAD

**Issue by hildjj** [yarnpkg/yarn#897]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Not implemented

**What is the expected behavior?**
`yarn home [pkgname]` uses [opn](https://github.com/sindresorhus/opn) to open the default browser at the URL from the `homepage` key in package.json of the specified package.  Default package is ".".   For extra credit at npm compatibility, provide the mostly-useless `--browser` parameter to select a browser.

**Please mention your node.js, yarn and operating system version.**
node: v6.7.0
yarn: 0.15.1
OS: OSX 10.12

**Comment by hildjj** [comment]
I'm working on a PR.

**Comment by jeffbski** [comment]
Thanks @hildjj this is one of my favorite features of npm, so it will be great to have it in yarn.

**Comment by kittens** [comment]
We wont be including utility commands such as `home` and `search` in Yarn. See my comment in #914 for the detailed reasoning:

> I'm going to reject the inclusion of `yarn search` and `yarn home` for the timebeing. It adds a lot of machinery and complexity around an operation that's generally super easy to perform: opening a URL. There's lots of questions to ask that makes it clear that the complexity isn't worth it:
>
> 1. How do we detect what browser to open?
> 2. Should we have a way to specify the browser?
> 3. How does this work across operating systems?
> 4. etc etc
>
> Even if there are modules that can perform these sorts of operations it still increases our surface area significantly. I hope you understand and this wont prevent you from contributing in the future as we really appreciate any and all contributions. Thank you so much for the work you've put into this!

**Comment by jeffbski** [comment]
I thank you for responding back on your decision along with the reasoning. If you will allow me, I am going to respectfully try to make a counterpoint for why I still believe the `home` feature should be added (that it's benefit outweigh the complexity/risk increase). I do understand the need to push back on some features and weighing the benefits and at the end of the day, so regardless I will respect the team's choice.

This is a problem that npm already has solved nicely and has proved to be a very valuable time saver for me. **Yarn can be the replacement for npm client, but it does need to have the important features.** Obviously we disagree on what are the important features and that is fine, but I would at least like to make a case for this. I'm not advocating that yarn copy all of npm's features but this one is a big win IMO.

## Why add the home feature?


Q: How often do you need to look up some details, config, api, etc about a module you haven't used in a while? 
A: Countless times each day in my case

### Manually navigating to a homepage or repo for an npm package

Q: How many steps does it take a normal user to find the homepage or repo for a npm package manually when you don't know where it lives?
A: Multi-step process of 4-7+ steps
 1. open http://npmjs.org in a browser (launch browser if I don't already have one up)
 2. search for package like 'joi'
 3. it comes back with 382 results to look through and the actual package 'joi' is not on the first page, so I have to click next and scan through each page to see if it has the actual package. Currently it is on the third page of results with all the other plugins in front of it.
 4. Finally once I have found the package, I click on the link and bring up npm's version of the README which may or may not give me all the details I want. 
 5. I still may need to click once more to go to the actual homepage or repo

Q: Is there a way to shortcut this? 
A: Well maybe if you know how npm's urls work you could type
https://npmjs.org/package/joi but that is not something you would expect normal users to know and remember and you still have to navigate from there to get to the actual homepage/repo. So it is still a minimum of 2 steps.

Sometimes google will help you get there quicker, but that can be difficult for short package names that match common words.

I guess another alternative flow would be to use `yarn info joi` searching for homepage or repo links, then copy and pasting that into a browser window. It's ugly and painful on a large package.json but it is another alternative.

### Contrasting the process using the proposed `yarn home` feature

Now compare how it would it work with the `home` feature?
 1. `yarn home joi`

Done. I didn't have to have a browser up and I didn't need to remember any npm site structure for the URL.

Once you have used this a few times you'll be sold on how useful and how much time it saves. 

## Regarding complexity

This is already a solved problem. The `opn` package already solves all of your questions in a cross platform way, so it really is simply calling the opn function with the url from the registry.

If you are delegating opening of the browser to opn, then it seems that you are simply confirming that this new function is passed the home URL from the registry which doesn't seem to be a difficult test.

Other than adding additional tests, the PR completes this functionality with less than 60 lines of code (and the actual code is only a small portion of that). 

## Conclusion

**It is my opinion that `yarn home` would be a very valuable feature that is easily implemented and simply delegates to an active dedicated module for most of its work.** The time saving benefits would seem to justify the simple feature addition. 

**I will however respect the team's opinions on what is best for this project**, I know that open source project maintainers have an impossible task to keep up with the requests and push back on bloat. 

**I'll just have to keep `npm` around to do all of my doc lookups since `yarn` will be missing this feature.** **When I train people, if I teach them to use yarn** for most of their package related activities, I'll have to tell them to **go back to npm for this particular feature**. It will be a bit confusing, and they won't like that answer but it is the best I can do with the way things are.

**I am still excited about `yarn` as a tool, but disappointed** that it won't have this somewhat standard feature that all package mangers should have.

Thanks for all you do. All the best.

**Comment by thejameskyle** [comment]
@jeffbski While I appreciate your enthusiasm, please try to keep comments a little bit shorter than that. We're getting hundreds of comments a day and we're still growing the team so having to read something that long is counter-productive.

Aside from that, I don't think this command is an immediate priority, especially since yarn is not npm specific. If anything it should be `yarn npm-home [package]`

**Comment by Daniel15** [comment]
> this somewhat standard feature that all package mangers should have.

Excluding npm, do any other package managers (NuGet, RubyGems, PyPI, Composer, dpkg/apt-get, etc.) have this feature?

**Comment by g-patel** [comment]
I hate to realize that yarn doesn't have `docs`/`home` cli. 😞
