### ISSUE TITLE
devDependencies and hoisting problem

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#91]
Npm3 does not hoist devDependencies because hoisting of devDependencies will affect the overall node_modules structure of regular dependencies.
Then npm install --prod and --dev may have possibly different application node_modules and it may cause unexpected app behaviour.

Any idea if this issue affects us and whether we should do the same?

**Comment by bdentino** [comment]
sorry to drudge up an old issue, but was there ever any further discussion of this? is it possibly related to #1462? There seems to be a discrepancy between how yarn and npm hoist modules that are shared by packages specified in dependencies and devDependencies when installing with `--production`. I've been running into situations where `yarn install --prod` results in 'module not found' errors because a dependency of a dependency isn't pulled to the top-level like it is with npm.
