### ISSUE TITLE
"304 Not Modified" responses from the registry

### ISSUE THREAD

**Issue by mangeshpatiln** [yarnpkg/yarn#9118]
We are using yarn 1.22.22. Facing following issue due to the buffer-xor-1.0.3.tgz is not available on path.
[2/4] Fetching packages...
error Error: https://registry.yarnpkg.com/buffer-xor/-/buffer-xor-1.0.3.tgz: Request failed "304 Not Modified"
    at ResponseError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:696:66)
    at new ResponseError (/usr/lib/node_modules/yarn/lib/cli.js:802:124)
    at Request.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:66750:16)
    at Request.emit (node:events:518:28)
    at module.exports.Request.onRequestResponse (/usr/lib/node_modules/yarn/lib/cli.js:142287:10)
    at ClientRequest.emit (node:events:518:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:698:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:540:22)
    at TLSSocket.emit (node:events:518:28)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

When we try to access buffer-xor-1.0.2.tgz and buffer-xor-2.0.2.tgz it is available.

**Comment by shailendrasingh** [comment]
We are trying to install the yarn on a remote server on AWS cloud, it was working fine till yesterday evening. We have started experiencing this issue from today morning onwards.

**Comment by arcanis** [comment]
Some other reports on Twitter/X:

<img width="612" alt="Image" src="https://github.com/user-attachments/assets/7afe29b2-c8d9-49b3-9fa5-a3a2f90d4117" />

**Comment by Yash17Agrawal** [comment]
➕

**Comment by i-am-gg** [comment]
+1 to this, we are facing this issue too

This is from our jenkins server hosted in ap-south-1

![Image](https://github.com/user-attachments/assets/3b736795-222c-4846-8707-16e1d09c3240)

**Comment by ShellXploit** [comment]
+1 @arcanis would you be able to suggest any workarounds we could hit-and-try as we have been facing this issue as well.

**Comment by arcanis** [comment]
> +1 [@arcanis](https://github.com/arcanis) would you be able to suggest any workarounds we could hit-and-try as we have been facing this issue as well.

In the future you probably should consider enabling the offline mirror (see [this blog post](https://classic.yarnpkg.com/blog/2016/11/24/offline-mirror/) for 1.x, or [this page](https://yarnpkg.com/features/caching#offline-mirror) for 2.x/3.x/4.x) to avoid having your builds rely on the npm registry, which is known to be flaky every once in a while.

Unfortunately that's something you need to do ahead of time, so it won't help in the present case. Right now, unless you have a perfect mirror available (I don't have any to recommend, especially since it has security implications), I don't have a workaround to suggest.

**Comment by arcanis** [comment]
Seems to affect npm as well btw: https://github.com/npm/cli/issues/7986

**Comment by sachinjthakur** [comment]
Facing same issue since yesterday. <img width="990" alt="Image" src="https://github.com/user-attachments/assets/83e9b789-c0d1-46d3-af23-f43882cfa310" />

**Comment by chiragramimi** [comment]
Use the following command to change the Yarn registry to a mirror, which can help avoid potential issues:

yarn config set registry https://registry.npmmirror.com/

**Comment by arcanis** [comment]
Please note that using a registry you don't control can be dangerous. For instance, being a chinese entity, npmmirror.com is likely subject to the [National Intelligence Law](https://en.wikipedia.org/wiki/National_Intelligence_Law_of_the_People%27s_Republic_of_China). For this reason I'd prefer to avoid suggestions of alternate registries hidden on this repository, to not give the impression the Yarn project is endorsing them.

> Remove yarn lock first then

Or migrate to modern releases of Yarn. We haven't stored the registry url in the lockfile for the past six years. If you remove the lockfile, your dependencies will all be upgraded, which may lead to unexpected breakages.

**Comment by shailendrasingh** [comment]
I have solved the issue by using the mirror registry url as follows -

1. Created .yarnrc file
2.  Added `registry : https://registry.npmmirror.com` 

ran `rm yarn.lock` to remove existing yarn.lock file
ran `yarn config list` to verify your registry

**Comment by ShellXploit** [comment]
> I have solved the issue by using the mirror registry url as follows -
> 
> 1. Created .yarnrc file
> 2. Added `registry : https://registry.npmmirror.com`
> 
> ran `rm yarn.lock` to remove existing yarn.lock file ran `yarn config list` to verify your registry

Duplicate, and this is a Chinese repository, please add relevant disclaimers before recommending any solutions/workarounds as mentioned [here](https://github.com/yarnpkg/yarn/issues/9118#issuecomment-2548164053)

**Comment by mahyah-00** [comment]
I have been troubleshooting this issue since several hours, trying to install pm2 on Amazon Linux using Docker. 

The errors encountered were TAR_BAD_ARCHIVE: Unrecognized archive format during npm install -g pm2 and Request failed "304 Not Modified" during yarn. 

Attempted several fixes, including clearing the npm cache with npm cache clean --force, updating both npm and Yarn to the latest versions, and verifying the npm registry configuration.

Tried switching Node.js versions. Despite these efforts, the errors still persisted.

Unfortunately, the issue remained unresolved. :(

**Comment by musadiqpeerzada-refyne** [comment]
the issue is tracked here: https://github.com/npm/cli/issues/7986

**Comment by musadiqpeerzada-refyne** [comment]
> It seems like something broke on the registry. It's strange that every report so far seem to originate from India - could that somehow come from a proxy you'd all be using? I pinged the npm folks on the OpenJS slack, but they're on US timezone, so that may take some time.

The issue is with Mumbai, India region. working fine at other places

**Comment by AravinthK820** [comment]
> > It seems like something broke on the registry. It's strange that every report so far seem to originate from India - could that somehow come from a proxy you'd all be using? I pinged the npm folks on the OpenJS slack, but they're on US timezone, so that may take some time.
> 
> The issue is with Mumbai, India region. working fine at other places

No The Issue is from TamilNadu, India Region also. I am also getting the issue which unrelated Modules getting 304 Nod Modified Error.

**Comment by musadiqpeerzada-refyne** [comment]
> > > It seems like something broke on the registry. It's strange that every report so far seem to originate from India - could that somehow come from a proxy you'd all be using? I pinged the npm folks on the OpenJS slack, but they're on US timezone, so that may take some time.
> > 
> > 
> > The issue is with Mumbai, India region. working fine at other places
> 
> No The Issue is from TamilNadu, India Region also. I am also getting the issue which unrelated Modules getting 304 Not Modified Error.

Bengaluru, India it is working fine. Any chance you're running it on a remote instance in Mumbai?

**Comment by AravinthK820** [comment]
> > > > It seems like something broke on the registry. It's strange that every report so far seem to originate from India - could that somehow come from a proxy you'd all be using? I pinged the npm folks on the OpenJS slack, but they're on US timezone, so that may take some time.
> > > 
> > > 
> > > The issue is with Mumbai, India region. working fine at other places
> > 
> > 
> > No The Issue is from TamilNadu, India Region also. I am also getting the issue which unrelated Modules getting 304 Not Modified Error.
> 
> Bengaluru, India it is working fine. Any chance you're running it on a remote instance in Mumbai?

yes, i am running my instance with a mumbai region  is that anyother way to resolve this issue ?

**Comment by musadiqpeerzada-refyne** [comment]
> > > > > It seems like something broke on the registry. It's strange that every report so far seem to originate from India - could that somehow come from a proxy you'd all be using? I pinged the npm folks on the OpenJS slack, but they're on US timezone, so that may take some time.
> > > > 
> > > > 
> > > > The issue is with Mumbai, India region. working fine at other places
> > > 
> > > 
> > > No The Issue is from TamilNadu, India Region also. I am also getting the issue which unrelated Modules getting 304 Not Modified Error.
> > 
> > 
> > Bengaluru, India it is working fine. Any chance you're running it on a remote instance in Mumbai?
> 
> yes, i am running my instance with a mumbai region is that anyother way to resolve this issue ?

Mumbai is the affected region, seems some cdn issue with packages

**Comment by AravinthK820** [comment]
> > > > > > It seems like something broke on the registry. It's strange that every report so far seem to originate from India - could that somehow come from a proxy you'd all be using? I pinged the npm folks on the OpenJS slack, but they're on US timezone, so that may take some time.
> > > > > 
> > > > > 
> > > > > The issue is with Mumbai, India region. working fine at other places
> > > > 
> > > > 
> > > > No The Issue is from TamilNadu, India Region also. I am also getting the issue which unrelated Modules getting 304 Not Modified Error.
> > > 
> > > 
> > > Bengaluru, India it is working fine. Any chance you're running it on a remote instance in Mumbai?
> > 
> > 
> > yes, i am running my instance with a mumbai region is that anyother way to resolve this issue ?
> 
> Mumbai is the affected region, seems some cdn issue with packages

thus the Yarn community support will resolve it or otherwise i have to do anything ?

**Comment by musadiqpeerzada-refyne** [comment]
> > > > > > > It seems like something broke on the registry. It's strange that every report so far seem to originate from India - could that somehow come from a proxy you'd all be using? I pinged the npm folks on the OpenJS slack, but they're on US timezone, so that may take some time.
> > > > > > 
> > > > > > 
> > > > > > The issue is with Mumbai, India region. working fine at other places
> > > > > 
> > > > > 
> > > > > No The Issue is from TamilNadu, India Region also. I am also getting the issue which unrelated Modules getting 304 Not Modified Error.
> > > > 
> > > > 
> > > > Bengaluru, India it is working fine. Any chance you're running it on a remote instance in Mumbai?
> > > 
> > > 
> > > yes, i am running my instance with a mumbai region is that anyother way to resolve this issue ?
> > 
> > 
> > Mumbai is the affected region, seems some cdn issue with packages
> 
> thus the Yarn community support will resolve it or otherwise i have to do anything ?

I think npmjs will resolve it.
https://github.com/yarnpkg/yarn/issues/9118#issuecomment-2548170326 is a workaround but not advisable though.

**Comment by gayathrivandana15** [comment]
> > > > > > > > It seems like something broke on the registry. It's strange that every report so far seem to originate from India - could that somehow come from a proxy you'd all be using? I pinged the npm folks on the OpenJS slack, but they're on US timezone, so that may take some time.
> > > > > > > 
> > > > > > > 
> > > > > > > The issue is with Mumbai, India region. working fine at other places
> > > > > > 
> > > > > > 
> > > > > > No The Issue is from TamilNadu, India Region also. I am also getting the issue which unrelated Modules getting 304 Not Modified Error.
> > > > > 
> > > > > 
> > > > > Bengaluru, India it is working fine. Any chance you're running it on a remote instance in Mumbai?
> > > > 
> > > > 
> > > > yes, i am running my instance with a mumbai region is that anyother way to resolve this issue ?
> > > 
> > > 
> > > Mumbai is the affected region, seems some cdn issue with packages
> > 
> > 
> > thus the Yarn community support will resolve it or otherwise i have to do anything ?
> 
> I think npmjs will resolve it. [#9118 (comment)](https://github.com/yarnpkg/yarn/issues/9118#issuecomment-2548170326) is a workaround but not advisable though.

do you know how much time it would take to be resolved?

**Comment by ShellXploit** [comment]
Solution that is working for us:
- Deployed a squid proxy in `us-east-1` region
- Configured the proxy to forward all the requests for YARN and NPM official registry
- Updated the yarn proxy using `yarn config set proxy <url>` and `yarn config set https-proxy <url>` -- here the URL is of the squid proxy

Since we were using Jenkins with custom runners we have added the yarn config commands to the init script of those nodes to propagate this change across all the pipelines.

Context:
The issue seems to be impacting India and UAE regions based on the two threads in [yarn](https://github.com/yarnpkg/yarn/issues/9118) and [npm](https://github.com/npm/cli/issues/7986) and by setting up the proxy in `us-east-1` all the traffic is being directed to US mirrors.

Disclaimer:
- There will be an increase in the cost from the new resource and the data transfers being done via us-east-1 region
- If you have any private mirrors you will have to whitelist them from the proxy, and even add a routing for them in the squid config
- There will be a significant increase in the latency due to this additional cross-region hop
- While configuring the proxy ensure it's not publicly accessible and you enforce security measures (WAF, inbound rules, etc) to prevent any malicious activity
- Please ensure your compliance doesn't blocks you from routing requests via US servers

**Comment by ShellXploit** [comment]
Solution that is working for us:
- Deployed a squid proxy in `us-east-1` region
- Configured the proxy to forward all the requests for YARN and NPM official registry
- Updated the yarn proxy using `yarn config set proxy <url>` and `yarn config set https-proxy <url>` -- here the URL is of the squid proxy

Since we were using Jenkins with custom runners we have added the yarn config commands to the init script of those nodes to propagate this change across all the pipelines.

Context:
The issue seems to be impacting India region based on the two threads in [yarn](https://github.com/yarnpkg/yarn/issues/9118) and [npm](https://github.com/npm/cli/issues/7986) and by setting up the proxy in `us-east-1` all the traffic is being directed to US mirrors.

Disclaimer:
- There will be an increase in the cost from the new resource and the data transfers being done via us-east-1 region
- If you have any private mirrors you will have to whitelist them from the proxy, and even add a routing for them in the squid config
- There will be a significant increase in the latency due to this additional cross-region hop
- While configuring the proxy ensure it's not publicly accessible and you enforce security measures (WAF, inbound rules, etc) to prevent any malicious activity
- Please ensure your compliance doesn't blocks you from routing requests via US servers

**Comment by AravinthK820** [comment]
> Solution that is working for us:
> 
> * Deployed a squid proxy in `us-east-1` region
> * Configured the proxy to forward all the requests for YARN and NPM official registry
> * Updated the yarn proxy using `yarn config set proxy <url>` and `yarn config set https-proxy <url>` -- here the URL is of the squid proxy
> 
> Since we were using Jenkins with custom runners we have added the yarn config commands to the init script of those nodes to propagate this change across all the pipelines.
> 
> Context: The issue seems to be impacting India region based on the two threads in [yarn](https://github.com/yarnpkg/yarn/issues/9118) and [npm](https://github.com/npm/cli/issues/7986) and by setting up the proxy in `us-east-1` all the traffic is being directed to US mirrors.
> 
> Disclaimer:
> 
> * There will be an increase in the cost from the new resource and the data transfers being done via us-east-1 region
> * If you have any private mirrors you will have to whitelist them from the proxy, and even add a routing for them in the squid config
> * There will be a significant increase in the latency due to this additional cross-region hop
> * While configuring the proxy ensure it's not publicly accessible and you enforce security measures (WAF, inbound rules, etc) to prevent any malicious activity
> * Please ensure your compliance doesn't blocks you from routing requests via US servers

is there any alternative as i don't use any proxy ?

**Comment by arcanis** [comment]
An [incident](https://status.npmjs.org/incidents/bxvmmvlqzfds) has been opened on the npm side. I'll close & lock this issue as there's nothing the Yarn team can do. Please follow the incident for updates.
