### ISSUE TITLE
Installation Problem: Windows 8.1 not able to install yarn the via MSI, as symantec (anti-virus) blocks the installtion

### ISSUE THREAD

**Issue by bboysathish** [yarnpkg/yarn#967]
**Which operating system are you using:**

Windows 8.1

**Please describe the steps you took when trying to install Yarn and what went wrong:**

Just downloaded the msi from website, version - 0.15.0

Snapshots of Error:

![symentec_yarn](https://cloud.githubusercontent.com/assets/8023447/19338776/d359e80c-913c-11e6-8da3-cd3c9cfcaa31.PNG)

![yarn_pg_1](https://cloud.githubusercontent.com/assets/8023447/19338781/d8e2b3ee-913c-11e6-93fa-193dc924bfe6.PNG)

**Comment by rjmunro** [comment]
Surely this is a bug in Symantec anti-virus?

**Comment by peinearydevelopment** [comment]
Threat description: https://www.symantec.com/theme/star
"The applications being deployed on our customer's machines (each application is uniquely identified by its SHA2 hash).
    Where applications came from on the web.
    Whether or not the applications are digitally signed.
    How old the applications are.
    A host of other attributes.

We add to this data from our Global Intelligence Network, our Security Response organization, and legitimate software vendors who provide application instances to Symantec."
Remediation:
"WHITE-LISTING
Software developers who want to accelerate the reputation building process for their new software applications should submit new applications to the Symantec white-listing program. Details of that program can be found here. "
https://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99&tabid=3

It doesn't appear to be a bug in Symantec exactly, but possibly since this is still new, it needs to "build its reputation". It seems possible that having one of the core team members submit a new application to their white-listing program might do the trick.

**Comment by Daniel15** [comment]
This should have been fixed when we added an Authenticode signature to the installer. Please let us know if you still see this.
