### ISSUE TITLE
Yarn removes needed files

### ISSUE THREAD

**Issue by bart** [yarnpkg/yarn#974]
First of all, yarn is lightning fast, I pretty love it. I removed a package from my package.json file and tried to use the ```yarn clean``` command. After this I ran my gulp task - boom. Some files were gone. In detail, it's the package ```"bootstrap-datepicker": "^1.6.4"```. It seems like yarn removed the locales under dist/locales. Do you have any idea whats wrong here and how I can prevent this?

Thanks a lot!

**Comment by kittens** [comment]
`yarn clean` is used to remove redundant files that may have been accidently included in `node_modules`. We have some heuristics to do this. Why are you under the assumption that this is the command you should be using? We should probably rename it if it's causing confusion. Instead of running `yarn clean` after a change to `package.json`, just use `yarn install`.

**Comment by bart** [comment]
I like to have a clean environment, only with files I really need. I didn't know that a simple ```yarn``` also cleans up packages. Thanks @kittens
